-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
create or replace view digest.event_registrations_live as
 SELECT roster_record_id,
    event_at_id,
    member_at_id,
    email,
    full_name,
    order_date,
    ticket_type,
    source,
    app_event_id,
    app_user_id,
    synced_at,
    ticket_status,
    ticket_for
   FROM digest.event_registrations r
  WHERE ticket_status IS DISTINCT FROM 'Unconfirmed'::text AND ticket_status IS DISTINCT FROM 'No Show'::text;
