-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
create or replace view digest.fb_activity as
 SELECT 'post'::text AS kind,
    p.post_id,
    NULL::text AS comment_id,
    p.created_time,
    p.author_uid,
    COALESCE(mp.full_name, m.profile_name_fb, p.author_name) AS author,
    m.at_member_id,
    COALESCE(mp.status, m.at_status) AS member_status,
    p.text,
    ((('https://www.facebook.com/groups/'::text || COALESCE(p.group_slug, 'milliondollarsellers'::text)) || '/posts/'::text) || p.post_id) || '/'::text AS fb_url,
    p.post_id AS thread_post_id,
    p.last_seen
   FROM digest.fb_posts p
     LEFT JOIN digest.fb_member_map m ON m.fb_uid = p.author_uid
     LEFT JOIN digest.member_profiles mp ON mp.at_member_id = m.at_member_id
UNION ALL
 SELECT 'comment'::text AS kind,
    c.post_id,
    c.comment_id,
    c.created_time,
    c.author_uid,
    COALESCE(mp.full_name, m.profile_name_fb, c.author_name) AS author,
    m.at_member_id,
    COALESCE(mp.status, m.at_status) AS member_status,
    c.text,
    (((('https://www.facebook.com/groups/'::text || COALESCE(p.group_slug, 'milliondollarsellers'::text)) || '/posts/'::text) || c.post_id) || '/?comment_id='::text) || COALESCE(c.legacy_id, ''::text) AS fb_url,
    c.post_id AS thread_post_id,
    c.last_seen
   FROM digest.fb_comments c
     JOIN digest.fb_posts p ON p.post_id = c.post_id
     LEFT JOIN digest.fb_member_map m ON m.fb_uid = c.author_uid
     LEFT JOIN digest.member_profiles mp ON mp.at_member_id = m.at_member_id;
