-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
create or replace view digest.fb_report_member_mix as
 SELECT author_uid,
    max(author_name) AS member,
    count(*) AS posts,
    count(*) FILTER (WHERE post_type = 'ask'::text) AS asks,
    count(*) FILTER (WHERE post_type = 'give'::text) AS gives,
    count(*) FILTER (WHERE post_type = 'value_add'::text) AS value_adds,
    round(count(*) FILTER (WHERE post_type = ANY (ARRAY['give'::text, 'value_add'::text]))::numeric / NULLIF(count(*) FILTER (WHERE post_type IS NOT NULL), 0)::numeric, 2) AS give_share,
    sum(( SELECT count(*) AS count
           FROM digest.fb_comments c
          WHERE c.post_id = p.post_id)) AS comments_received,
    round(avg(reach)) AS avg_reach,
    max(created_time) AS last_post
   FROM digest.fb_posts p
  WHERE author_uid IS NOT NULL
  GROUP BY author_uid;
