-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
create or replace view digest.fb_report_partner_sentiment as
 SELECT partner_id,
    max(partner_name) AS partner,
    count(*) FILTER (WHERE verdict = 'complaint'::text) AS complaints,
    count(*) FILTER (WHERE verdict = 'praise'::text) AS praise,
    count(*) FILTER (WHERE verdict = 'neutral'::text) AS neutral,
    max(occurred_at) AS last_mention,
    (array_agg(quote ORDER BY (verdict = 'complaint'::text) DESC, occurred_at DESC))[1] AS latest_quote
   FROM digest.fb_partner_mentions m
  GROUP BY partner_id;
