-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
create or replace view digest.fb_report_hashtags as
 SELECT tag.tag,
    count(*) AS posts,
    count(DISTINCT p.author_uid) AS members,
    max(p.created_time) AS last_used
   FROM digest.fb_posts p,
    LATERAL unnest(p.hashtags) tag(tag)
  GROUP BY tag.tag;
