-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
create or replace view digest.fb_report_weekly as
 WITH p AS (
         SELECT date_trunc('week'::text, fb_posts.created_time)::date AS week,
            fb_posts.post_id,
            fb_posts.post_type,
            fb_posts.reach,
            fb_posts.author_uid
           FROM digest.fb_posts
          WHERE fb_posts.created_time IS NOT NULL
        ), c AS (
         SELECT date_trunc('week'::text, fb_comments.created_time)::date AS week,
            count(*) AS comments
           FROM digest.fb_comments
          WHERE fb_comments.created_time IS NOT NULL
          GROUP BY (date_trunc('week'::text, fb_comments.created_time)::date)
        )
 SELECT p.week,
    count(*) AS posts,
    count(*) FILTER (WHERE p.post_type = 'ask'::text) AS asks,
    count(*) FILTER (WHERE p.post_type = 'give'::text) AS gives,
    count(*) FILTER (WHERE p.post_type = 'value_add'::text) AS value_adds,
    COALESCE(max(c.comments), 0::bigint) AS comments,
    count(*) FILTER (WHERE NOT (EXISTS ( SELECT 1
           FROM digest.fb_comments fc
          WHERE fc.post_id = p.post_id))) AS unanswered,
    round(avg(p.reach)) AS avg_reach,
    count(DISTINCT p.author_uid) AS active_members
   FROM p
     LEFT JOIN c ON c.week = p.week
  GROUP BY p.week;
