-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
create or replace view digest.form_answers_latest as
 SELECT DISTINCT ON (fr.member_at_id, fr.form_id, a.key) fr.member_at_id,
    fr.form_id,
    fr.form_name,
    a.key AS ref,
    COALESCE(m.canonical_key, a.key) AS canonical_key,
    a.value ->> 'q'::text AS question,
    a.value ->> 't'::text AS answer_type,
    a.value -> 'v'::text AS value,
    fr.submitted_at
   FROM digest.form_responses fr
     CROSS JOIN LATERAL jsonb_each(fr.answers) a(key, value)
     LEFT JOIN digest.form_field_map m ON m.form_id = fr.form_id AND m.ref = a.key
  WHERE fr.member_at_id IS NOT NULL
  ORDER BY fr.member_at_id, fr.form_id, a.key, fr.submitted_at DESC;
