-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
create or replace view digest.knowledge_graph as
 SELECT member_edges.a_id,
    'member'::text AS a_kind,
    member_edges.b_id,
    'member'::text AS b_kind,
    member_edges.edge_type,
    NULL::date AS valid_from,
    NULL::date AS valid_to,
    member_edges.weight,
    member_edges.evidence,
    'member_edges'::text AS source
   FROM digest.member_edges
UNION ALL
 SELECT web_edges.a_id,
    web_edges.a_kind,
    web_edges.b_id,
    web_edges.b_kind,
    web_edges.edge_type,
    web_edges.valid_from,
    web_edges.valid_to,
    web_edges.weight,
    web_edges.evidence,
    'web_edges'::text AS source
   FROM digest.web_edges;
