-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
create or replace view digest.member_fact_conflicts as
 SELECT c.at_member_id,
    mp.full_name,
    'location'::text AS field,
    mp.at_fields ->> 'City'::text AS ours,
    c.location AS web,
    c.source_url,
    c.fetched_at
   FROM digest.member_web_profile_current c
     JOIN digest.member_profiles mp ON mp.at_member_id = c.at_member_id
  WHERE c.location IS NOT NULL AND COALESCE(mp.at_fields ->> 'City'::text, ''::text) <> ''::text AND lower(c.location) !~~ (('%'::text || lower(mp.at_fields ->> 'City'::text)) || '%'::text)
UNION ALL
 SELECT e.a_id AS at_member_id,
    mp.full_name,
    'company'::text AS field,
    mp.at_fields ->> 'Brand Name'::text AS ours,
    e.evidence ->> 'company_name'::text AS web,
    e.source_url,
    e.fetched_at
   FROM digest.web_edges e
     JOIN digest.member_profiles mp ON mp.at_member_id = e.a_id
  WHERE e.a_kind = 'member'::text AND (e.edge_type = ANY (ARRAY['works_at'::text, 'founded'::text])) AND e.valid_to IS NULL AND COALESCE(mp.at_fields ->> 'Brand Name'::text, ''::text) <> ''::text AND POSITION((lower(e.evidence ->> 'company_name'::text)) IN (lower(mp.at_fields ->> 'Brand Name'::text))) = 0;
