-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
create or replace view digest.member_links as
 SELECT at_member_id,
    digest.member_link(at_member_id) AS link
   FROM digest.member_profiles mp;
