-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
create or replace view digest.member_fact_population as
 SELECT f.member_at_id,
    f.concept,
    f.yr,
    f.submitted_at,
    f.form_id,
    f.form_name,
    f.question,
    f.answer_type,
    f.value,
    f.num,
    f.banded,
    f.open_top_band
   FROM digest.member_fact_num f
     JOIN digest.form_population p ON p.form_id = f.form_id AND p.class = 'population'::text;
