-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
create or replace view digest.member_web_profile_current as
 SELECT DISTINCT ON (at_member_id) at_member_id,
    source_url,
    source_kind,
    fetch_status,
    fetched_at,
    headline,
    location,
    industry,
    headcount,
    entity_id,
    work_history,
    education,
    raw,
    source_hash,
    model,
    confidence
   FROM digest.member_web_profile
  ORDER BY at_member_id, fetched_at DESC;
