-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
create or replace view digest.member_fact_num as
 SELECT f.member_at_id,
    f.concept,
    f.yr,
    f.submitted_at,
    f.form_id,
    f.form_name,
    f.question,
    f.answer_type,
    f.value,
        CASE
            WHEN c.value_kind = ANY (ARRAY['percent'::text, 'number'::text, 'score'::text]) THEN digest.pct_from_answer(f.value, f.answer_type)
            WHEN c.value_kind = 'money'::text AND jsonb_typeof(f.value) = 'number'::text THEN (f.value #>> '{}'::text[])::numeric
            ELSE NULL::numeric
        END AS num,
    (f.answer_type = ANY (ARRAY['choice'::text, 'choices'::text])) AND (c.value_kind = ANY (ARRAY['percent'::text, 'number'::text, 'score'::text])) AS banded,
        CASE
            WHEN (f.answer_type = ANY (ARRAY['choice'::text, 'choices'::text])) AND (f.value #>> '{}'::text[]) ~ '\+\s*$'::text THEN true
            ELSE false
        END AS open_top_band
   FROM digest.member_fact f
     JOIN digest.form_concept c ON c.concept = f.concept;
