-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
create or replace view digest.member_fact as
 SELECT DISTINCT ON (r.member_at_id, m.concept_final, (EXTRACT(year FROM r.submitted_at)::integer)) r.member_at_id,
    m.concept_final AS concept,
    EXTRACT(year FROM r.submitted_at)::integer AS yr,
    r.submitted_at,
    r.form_id,
    r.form_name,
    e.value ->> 'q'::text AS question,
    e.value ->> 't'::text AS answer_type,
    e.value -> 'v'::text AS value
   FROM digest.form_responses r
     CROSS JOIN LATERAL jsonb_each(r.answers) e(key, value)
     JOIN LATERAL ( SELECT COALESCE(fm.override_concept, fm.concept) AS concept_final
           FROM digest.form_question_map fm
          WHERE fm.form_id = r.form_id AND fm.question = (e.value ->> 'q'::text)) m ON true
  WHERE r.member_at_id IS NOT NULL AND m.concept_final IS NOT NULL
  ORDER BY r.member_at_id, m.concept_final, (EXTRACT(year FROM r.submitted_at)::integer), r.submitted_at DESC;
