-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
create or replace view digest.member_phones as
 WITH src AS (
         SELECT p.at_member_id,
            "right"(regexp_replace(v.ph, '\D'::text, ''::text, 'g'::text), 10) AS phone10,
            v.src AS source
           FROM digest.member_profiles p
             CROSS JOIN LATERAL ( VALUES (p.at_fields ->> 'Preferred Phone Number'::text,'at_preferred'::text), (p.at_fields ->> 'WhatsApp Number'::text,'at_whatsapp'::text)) v(ph, src)
          WHERE length(regexp_replace(COALESCE(v.ph, ''::text), '\D'::text, ''::text, 'g'::text)) >= 10
        UNION
         SELECT m.at_member_id,
            "right"(regexp_replace(m.phone, '\D'::text, ''::text, 'g'::text), 10) AS "right",
            'wa_layer'::text
           FROM digest.members m
          WHERE m.at_member_id IS NOT NULL AND length(regexp_replace(COALESCE(m.phone, ''::text), '\D'::text, ''::text, 'g'::text)) >= 10
        )
 SELECT s.at_member_id,
    s.phone10,
    s.source,
    a.full_name,
    a.membership_status,
    digest.is_active_member_status(a.membership_status) AS is_active
   FROM src s
     JOIN digest.member_attributes a ON a.at_member_id = s.at_member_id;
