-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
create or replace view digest.member_identity as
 SELECT m.airtable_id,
    m.at_member_id,
    m.phone,
    m.email,
    m.name,
    m.full_name,
    m.membership_status,
    m.channels_present,
    m.crm_member_id
   FROM digest.members m
UNION ALL
 SELECT NULL::text AS airtable_id,
    i.at_member_id,
    min(i.phone10) AS phone,
    NULL::text AS email,
    NULL::text AS name,
    min(a.full_name) AS full_name,
    min(a.membership_status) AS membership_status,
    '{}'::text[] AS channels_present,
    NULL::text AS crm_member_id
   FROM digest.member_phone_index i
     JOIN digest.member_attributes a ON a.at_member_id = i.at_member_id
  WHERE digest.is_active_member_status(a.membership_status) AND NOT (EXISTS ( SELECT 1
           FROM digest.members m2
          WHERE m2.at_member_id = i.at_member_id))
  GROUP BY i.at_member_id;
