-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
create or replace view digest.metric_lineage as
 SELECT d.metric_id,
    d.slide,
    d.label,
    d.concept,
    d.agg,
    d.basis,
    d."precision",
    f.form_id,
    f.form_name,
    count(DISTINCT f.member_at_id) AS members,
    min(f.submitted_at)::date AS first_answer,
    max(f.submitted_at)::date AS last_answer,
    p.class AS source_class
   FROM digest.deck_metric d
     LEFT JOIN digest.member_fact f ON f.concept = d.concept AND f.yr = 2026
     LEFT JOIN digest.form_population p ON p.form_id = f.form_id
  GROUP BY d.metric_id, d.slide, d.label, d.concept, d.agg, d.basis, d."precision", f.form_id, f.form_name, p.class;
