-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
create or replace view digest.personas_stats as
 SELECT e.at_member_id,
    e.topic,
    t.parent,
    round(COALESCE(e.pct, 0::numeric) * 100::numeric)::integer AS value,
        CASE
            WHEN e.score > 0::numeric AND e.peak_score > e.score THEN LEAST(100::numeric, round(round(COALESCE(e.pct, 0::numeric) * 100::numeric) * e.peak_score / e.score))::integer
            ELSE round(COALESCE(e.pct, 0::numeric) * 100::numeric)::integer
        END AS peak,
        CASE
            WHEN e.score IS NULL OR e.score = 0::numeric THEN 'none'::text
            WHEN e.score >= e.peak_score THEN 'peak'::text
            WHEN e.score >= (0.85 * e.peak_score) THEN 'holding'::text
            ELSE 'fading'::text
        END AS badge,
    e.rank_in_topic AS rank,
    e.weakness_score AS weakness,
    e.evidence,
    round(e.score, 2) AS score_today,
    round(e.peak_score, 2) AS score_peak,
    agg.pool,
    round(agg.topic_top, 2) AS topic_top,
    round(agg.topic_median, 2) AS topic_median
   FROM digest.member_expertise e
     JOIN digest.expertise_topics t ON t.topic = e.topic
     JOIN ( SELECT member_expertise.topic,
            count(*)::integer AS pool,
            max(member_expertise.score) AS topic_top,
            percentile_cont(0.5::double precision) WITHIN GROUP (ORDER BY (member_expertise.score::double precision))::numeric AS topic_median
           FROM digest.member_expertise
          GROUP BY member_expertise.topic) agg ON agg.topic = e.topic;
