-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
-- digest.at_field_catalog: row level security DISABLED
-- digest.call_attendance: row level security DISABLED
-- digest.calls: row level security DISABLED
alter table digest.chapters_catalog enable row level security;
-- digest.chats: row level security DISABLED
-- digest.city_aliases: row level security DISABLED
-- digest.concept_rule: row level security DISABLED
alter table digest.content_items enable row level security;
-- digest.deck_metric: row level security DISABLED
-- digest.doc_entries: row level security DISABLED
-- digest.docs: row level security DISABLED
-- digest.entity_dossier: row level security DISABLED
alter table digest.event_registrations enable row level security;
-- digest.event_series_profile: row level security DISABLED
alter table digest.events_catalog enable row level security;
-- digest.expertise_topics: row level security DISABLED
alter table digest.fb_comments enable row level security;
-- digest.fb_group_posts: row level security DISABLED
alter table digest.fb_member_map enable row level security;
-- digest.fb_partner_mentions: row level security DISABLED
alter table digest.fb_post_images enable row level security;
alter table digest.fb_post_links enable row level security;
-- digest.fb_post_overrides: row level security DISABLED
alter table digest.fb_posts enable row level security;
-- digest.form_concept: row level security DISABLED
-- digest.form_field_map: row level security DISABLED
-- digest.form_population: row level security DISABLED
-- digest.form_question_map: row level security DISABLED
-- digest.form_responses: row level security DISABLED
-- digest.form_scope: row level security DISABLED
alter table digest.member_attributes enable row level security;
-- digest.member_edges: row level security DISABLED
alter table digest.member_email_alias enable row level security;
alter table digest.member_events enable row level security;
-- digest.member_expertise: row level security DISABLED
-- digest.member_niches: row level security DISABLED
-- digest.member_personas: row level security DISABLED
-- digest.member_personas_history: row level security DISABLED
-- digest.member_phone_index: row level security DISABLED
-- digest.member_photos: row level security DISABLED
alter table digest.member_profile_embeddings enable row level security;
-- digest.member_profiles: row level security DISABLED
alter table digest.member_sessions enable row level security;
-- digest.member_state_snapshot: row level security DISABLED
-- digest.member_wa_ids: row level security DISABLED
alter table digest.members enable row level security;
alter table digest.olivia_alarm_config enable row level security;
alter table digest.olivia_alarm_state enable row level security;
alter table digest.olivia_billing_nudges enable row level security;
-- digest.olivia_feedback: row level security DISABLED
alter table digest.olivia_intros enable row level security;
alter table digest.olivia_job_heartbeats enable row level security;
-- digest.olivia_messages: row level security DISABLED
-- digest.olivia_question_labels: row level security DISABLED
alter table digest.olivia_question_topics enable row level security;
-- digest.olivia_recommendations: row level security DISABLED
-- digest.olivia_reports: row level security DISABLED
alter table digest.olivia_requests enable row level security;
-- digest.olivia_seen: row level security DISABLED
-- digest.olivia_sends: row level security DISABLED
-- digest.olivia_webhook_events: row level security DISABLED
alter table digest.partner_reviews enable row level security;
-- digest.partner_web_profile: row level security DISABLED
alter table digest.partners_catalog enable row level security;
-- digest.speaker_aliases: row level security DISABLED
-- digest.speakers: row level security DISABLED
alter table digest.summaries enable row level security;
alter table digest.video_access enable row level security;
alter table digest.video_files enable row level security;
-- digest.video_partner_links: row level security DISABLED
-- digest.video_speaker_letters: row level security DISABLED
-- digest.video_speaker_links: row level security DISABLED
alter table digest.video_speakers enable row level security;
alter table digest.videos_catalog enable row level security;
alter table digest.wa_messages enable row level security;
-- digest.zoom_name_alias: row level security DISABLED
