-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
-- digest.at_field_catalog
--   name                               text not null
--   field_type                         text
--   position                           integer
--   synced_at                          timestamp with time zone not null default now()
alter table digest.at_field_catalog add constraint at_field_catalog_pkey PRIMARY KEY (name);
CREATE UNIQUE INDEX at_field_catalog_pkey ON digest.at_field_catalog USING btree (name);

-- digest.call_attendance
--   id                                 bigint not null default nextval('digest.call_attendance_id_seq'::regclass)
--   call_uuid                          text not null
--   display_name                       text not null
--   name_folded                        text not null
--   joined_at                          timestamp with time zone
--   left_at                            timestamp with time zone
--   seconds                            integer
--   at_member_id                       text
--   synced_at                          timestamp with time zone not null default now()
alter table digest.call_attendance add constraint call_attendance_call_uuid_display_name_joined_at_key UNIQUE (call_uuid, display_name, joined_at);
alter table digest.call_attendance add constraint call_attendance_call_uuid_fkey FOREIGN KEY (call_uuid) REFERENCES digest.calls(call_uuid) ON DELETE CASCADE;
alter table digest.call_attendance add constraint call_attendance_pkey PRIMARY KEY (id);
CREATE INDEX call_attendance_call ON digest.call_attendance USING btree (call_uuid);
CREATE INDEX call_attendance_folded ON digest.call_attendance USING btree (name_folded);
CREATE INDEX call_attendance_member ON digest.call_attendance USING btree (at_member_id) WHERE (at_member_id IS NOT NULL);
CREATE UNIQUE INDEX call_attendance_call_uuid_display_name_joined_at_key ON digest.call_attendance USING btree (call_uuid, display_name, joined_at);
CREATE UNIQUE INDEX call_attendance_pkey ON digest.call_attendance USING btree (id);

-- digest.calls
--   call_uuid                          text not null
--   meeting_id                         bigint
--   topic                              text
--   call_type                          text
--   host_email                         text
--   started_at                         timestamp with time zone
--   ended_at                           timestamp with time zone
--   duration_min                       integer
--   participant_count                  integer
--   has_recording                      boolean not null default false
--   has_transcript                     boolean not null default false
--   is_member_facing                   boolean not null default false
--   groupos_video_id                   text
--   recording_start                    timestamp with time zone
--   raw                                jsonb
--   synced_at                          timestamp with time zone not null default now()
--   link_method                        text
alter table digest.calls add constraint calls_pkey PRIMARY KEY (call_uuid);
CREATE INDEX calls_started ON digest.calls USING btree (started_at DESC);
CREATE INDEX calls_type ON digest.calls USING btree (call_type, started_at DESC);
CREATE INDEX calls_video ON digest.calls USING btree (groupos_video_id) WHERE (groupos_video_id IS NOT NULL);
CREATE UNIQUE INDEX calls_pkey ON digest.calls USING btree (call_uuid);

-- digest.chapters_catalog
--   chapter                            text not null
--   site_name                          text
--   slug                               text
--   page_url                           text
--   region                             text
--   geo                                text
--   about                              text
--   leads                              jsonb not null default '[]'::jsonb
--   categories                         text[] not null default '{}'::text[]
--   site_stats                         jsonb not null default '{}'::jsonb
--   scraped_at                         timestamp with time zone
alter table digest.chapters_catalog add constraint chapters_catalog_pkey PRIMARY KEY (chapter);
alter table digest.chapters_catalog add constraint chapters_catalog_slug_key UNIQUE (slug);
CREATE UNIQUE INDEX chapters_catalog_pkey ON digest.chapters_catalog USING btree (chapter);
CREATE UNIQUE INDEX chapters_catalog_slug_key ON digest.chapters_catalog USING btree (slug);

-- digest.chats
--   chat_name                          text not null
--   chat_id                            text
--   invite_url                         text
--   updated_at                         timestamp with time zone not null default now()
--   verification_required              boolean
--   requirement_text                   text
--   verification_form                  text
--   optin_form                         text
--   call_schedule                      text
--   zoom_link                          text
--   moderators                         text
alter table digest.chats add constraint chats_pkey PRIMARY KEY (chat_name);
CREATE UNIQUE INDEX chats_pkey ON digest.chats USING btree (chat_name);

-- digest.city_aliases
--   alias                              text not null
--   canonical                          text not null
alter table digest.city_aliases add constraint city_aliases_pkey PRIMARY KEY (alias);
CREATE UNIQUE INDEX city_aliases_pkey ON digest.city_aliases USING btree (alias);

-- digest.concept_rule
--   id                                 integer not null default nextval('digest.concept_rule_id_seq'::regclass)
--   concept                            text not null
--   priority                           integer not null
--   match_re                           text not null
--   exclude_re                         text
--   note                               text
alter table digest.concept_rule add constraint concept_rule_concept_fkey FOREIGN KEY (concept) REFERENCES digest.form_concept(concept);
alter table digest.concept_rule add constraint concept_rule_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX concept_rule_pkey ON digest.concept_rule USING btree (id);

-- digest.content_items
--   id                                 bigint not null
--   source                             text not null
--   kind                               text not null
--   source_id                          text not null
--   title                              text
--   tl_dr                              text
--   body                               text
--   occurred_at                        timestamp with time zone not null
--   url                                text
--   access_rule                        jsonb not null
--   sensitivity                        digest.content_sensitivity not null default 'normal'::digest.content_sensitivity
--   search_extra                       text
--   meta                               jsonb not null default '{}'::jsonb
--   ingested_at                        timestamp with time zone not null default now()
--   search_tsv                         tsvector default to_tsvector('english'::regconfig, ((((COALESCE(tl_dr, ''::text) || ' '::text) || COALESCE(body, ''::text)) || ' '::text) || COALESCE(search_extra, ''::text)))
--   embedding                          extensions.vector(1024)
alter table digest.content_items add constraint content_items_pkey PRIMARY KEY (id);
alter table digest.content_items add constraint content_items_source_id_uq UNIQUE (source, source_id);
CREATE INDEX content_items_access_chat_idx ON digest.content_items USING btree (((access_rule ->> 'chat'::text)));
CREATE INDEX content_items_embedding_hnsw ON digest.content_items USING hnsw (embedding extensions.vector_cosine_ops);
CREATE INDEX content_items_occurred_idx ON digest.content_items USING btree (occurred_at DESC);
CREATE INDEX content_items_source_kind_occurred_idx ON digest.content_items USING btree (source, kind, occurred_at DESC);
CREATE INDEX content_items_tsv_idx ON digest.content_items USING gin (search_tsv);
CREATE UNIQUE INDEX content_items_pkey ON digest.content_items USING btree (id);
CREATE UNIQUE INDEX content_items_source_id_uq ON digest.content_items USING btree (source, source_id);

-- digest.deck_metric
--   metric_id                          text not null
--   slide                              text not null
--   label                              text not null
--   concept                            text
--   agg                                text not null
--   threshold                          numeric
--   basis                              text not null default 'population'::text
--   precision                          text not null default 'all'::text
--   fallback                           text
--   note                               text
alter table digest.deck_metric add constraint deck_metric_agg_check CHECK ((agg = ANY (ARRAY['median'::text, 'share_at_or_above'::text, 'share_above_zero'::text, 'share_of_answers'::text, 'count'::text, 'manual'::text])));
alter table digest.deck_metric add constraint deck_metric_basis_check CHECK ((basis = ANY (ARRAY['population'::text, 'any'::text])));
alter table digest.deck_metric add constraint deck_metric_concept_fkey FOREIGN KEY (concept) REFERENCES digest.form_concept(concept);
alter table digest.deck_metric add constraint deck_metric_pkey PRIMARY KEY (metric_id);
alter table digest.deck_metric add constraint deck_metric_precision_check CHECK (("precision" = ANY (ARRAY['all'::text, 'exact_only'::text])));
CREATE UNIQUE INDEX deck_metric_pkey ON digest.deck_metric USING btree (metric_id);

-- digest.entity_dossier
--   kind                               text not null
--   entity_id                          text not null
--   name                               text
--   topic_profile                      jsonb not null default '{}'::jsonb
--   reception                          jsonb not null default '{}'::jsonb
--   strength_note                      text
--   weak_signal                        numeric
--   refreshed_at                       timestamp with time zone not null default now()
alter table digest.entity_dossier add constraint entity_dossier_kind_check CHECK ((kind = ANY (ARRAY['video'::text, 'partner'::text, 'event'::text, 'chapter'::text])));
alter table digest.entity_dossier add constraint entity_dossier_pkey PRIMARY KEY (kind, entity_id);
CREATE UNIQUE INDEX entity_dossier_pkey ON digest.entity_dossier USING btree (kind, entity_id);

-- digest.event_registrations
--   roster_record_id                   text not null
--   event_at_id                        text not null
--   member_at_id                       text
--   email                              text
--   full_name                          text
--   order_date                         date
--   ticket_type                        text
--   source                             text
--   app_event_id                       text
--   app_user_id                        text
--   synced_at                          timestamp with time zone not null default now()
--   ticket_status                      text
--   ticket_for                         text[]
alter table digest.event_registrations add constraint event_registrations_pkey PRIMARY KEY (roster_record_id);
CREATE INDEX event_registrations_event_idx ON digest.event_registrations USING btree (event_at_id);
CREATE INDEX event_registrations_member_idx ON digest.event_registrations USING btree (member_at_id);
CREATE UNIQUE INDEX event_registrations_pkey ON digest.event_registrations USING btree (roster_record_id);

-- digest.events_catalog
--   at_record_id                       text not null
--   name                               text not null
--   start_at                           timestamp with time zone
--   end_at                             timestamp with time zone
--   event_type                         text
--   phase                              text
--   guests_policy                      text
--   chapter_area                       text
--   chapter_hint                       text
--   venue_capacity                     integer
--   location                           text
--   city_state                         text
--   member_reg_link                    text
--   guest_reg_link                     text
--   chapter_member_reg_link            text
--   public_page_url                    text
--   app_event_id                       text
--   app_title                          text
--   app_starts_at                      timestamp with time zone
--   app_timezone                       text
--   app_city                           text
--   app_is_public                      boolean
--   app_url                            text
--   synced_at                          timestamp with time zone not null default now()
--   chapter_ids                        text[]
--   style                              text
--   embedding                          extensions.vector(1024)
--   thumbnail_url                      text
alter table digest.events_catalog add constraint events_catalog_pkey PRIMARY KEY (at_record_id);
CREATE INDEX events_catalog_start_idx ON digest.events_catalog USING btree (start_at);
CREATE UNIQUE INDEX events_catalog_pkey ON digest.events_catalog USING btree (at_record_id);

-- digest.expertise_topics
--   topic                              text not null
--   terms                              text[] not null
alter table digest.expertise_topics add constraint expertise_topics_pkey PRIMARY KEY (topic);
CREATE UNIQUE INDEX expertise_topics_pkey ON digest.expertise_topics USING btree (topic);

-- digest.fb_comments
--   comment_id                         text not null
--   legacy_id                          text
--   post_id                            text not null
--   parent_comment_id                  text
--   author_uid                         text
--   author_name                        text
--   text                               text
--   depth                              integer default 0
--   reactions                          integer
--   created_time                       timestamp with time zone
--   first_seen                         timestamp with time zone not null default now()
--   last_seen                          timestamp with time zone not null default now()
alter table digest.fb_comments add constraint fb_comments_pkey PRIMARY KEY (comment_id);
alter table digest.fb_comments add constraint fb_comments_post_id_fkey FOREIGN KEY (post_id) REFERENCES digest.fb_posts(post_id) ON DELETE CASCADE;
CREATE INDEX fb_comments_author_idx ON digest.fb_comments USING btree (author_uid);
CREATE INDEX fb_comments_created_idx ON digest.fb_comments USING btree (created_time);
CREATE INDEX fb_comments_post_idx ON digest.fb_comments USING btree (post_id);
CREATE UNIQUE INDEX fb_comments_pkey ON digest.fb_comments USING btree (comment_id);

-- digest.fb_member_map
--   fb_uid                             text not null
--   at_member_id                       text
--   profile_name_fb                    text
--   at_status                          text
--   vanity_url                         text
--   synced_at                          timestamp with time zone not null default now()
--   is_primary                         boolean not null default true
alter table digest.fb_member_map add constraint fb_member_map_pkey PRIMARY KEY (fb_uid);
CREATE INDEX fb_member_map_member_idx ON digest.fb_member_map USING btree (at_member_id);
CREATE UNIQUE INDEX fb_member_map_one_primary ON digest.fb_member_map USING btree (at_member_id) WHERE ((at_member_id IS NOT NULL) AND is_primary);
CREATE UNIQUE INDEX fb_member_map_pkey ON digest.fb_member_map USING btree (fb_uid);

-- digest.fb_post_images
--   id                                 bigint not null default nextval('digest.fb_post_images_id_seq'::regclass)
--   post_id                            text not null
--   idx                                integer not null default 0
--   local_path                         text
--   source_url                         text
--   storage_path                       text
--   ocr_text                           text
--   description                        text
--   vision_model                       text
--   analyzed_at                        timestamp with time zone
--   created_at                         timestamp with time zone not null default now()
alter table digest.fb_post_images add constraint fb_post_images_pkey PRIMARY KEY (id);
alter table digest.fb_post_images add constraint fb_post_images_post_id_idx_key UNIQUE (post_id, idx);
CREATE INDEX fb_post_images_post_id ON digest.fb_post_images USING btree (post_id);
CREATE UNIQUE INDEX fb_post_images_pkey ON digest.fb_post_images USING btree (id);
CREATE UNIQUE INDEX fb_post_images_post_id_idx_key ON digest.fb_post_images USING btree (post_id, idx);

-- digest.fb_posts
--   post_id                            text not null
--   group_slug                         text
--   author_uid                         text
--   author_name                        text
--   text                               text
--   created_time                       timestamp with time zone
--   first_seen                         timestamp with time zone not null default now()
--   last_seen                          timestamp with time zone not null default now()
--   comment_checked_at                 timestamp with time zone
--   reactions                          integer
alter table digest.fb_posts add constraint fb_posts_pkey PRIMARY KEY (post_id);
CREATE INDEX fb_posts_author_idx ON digest.fb_posts USING btree (author_uid);
CREATE INDEX fb_posts_created_idx ON digest.fb_posts USING btree (created_time);
CREATE UNIQUE INDEX fb_posts_pkey ON digest.fb_posts USING btree (post_id);

-- digest.form_concept
--   concept                            text not null
--   label                              text not null
--   family                             text not null
--   window_note                        text
--   value_kind                         text not null
--   notes                              text
alter table digest.form_concept add constraint form_concept_pkey PRIMARY KEY (concept);
alter table digest.form_concept add constraint form_concept_value_kind_check CHECK ((value_kind = ANY (ARRAY['number'::text, 'percent'::text, 'money'::text, 'choice'::text, 'choices'::text, 'text'::text, 'score'::text])));
CREATE UNIQUE INDEX form_concept_pkey ON digest.form_concept USING btree (concept);

-- digest.form_field_map
--   form_id                            text not null
--   ref                                text not null
--   canonical_key                      text not null
--   note                               text
alter table digest.form_field_map add constraint form_field_map_pkey PRIMARY KEY (form_id, ref);
CREATE UNIQUE INDEX form_field_map_pkey ON digest.form_field_map USING btree (form_id, ref);

-- digest.form_population
--   form_id                            text not null
--   class                              text not null
--   why                                text
alter table digest.form_population add constraint form_population_class_check CHECK ((class = ANY (ARRAY['population'::text, 'selected'::text])));
alter table digest.form_population add constraint form_population_pkey PRIMARY KEY (form_id);
CREATE UNIQUE INDEX form_population_pkey ON digest.form_population USING btree (form_id);

-- digest.form_question_map
--   form_id                            text not null
--   question                           text not null
--   answer_type                        text
--   answers                            integer
--   concept                            text
--   override_concept                   text
alter table digest.form_question_map add constraint form_question_map_concept_fkey FOREIGN KEY (concept) REFERENCES digest.form_concept(concept);
alter table digest.form_question_map add constraint form_question_map_override_concept_fkey FOREIGN KEY (override_concept) REFERENCES digest.form_concept(concept);
alter table digest.form_question_map add constraint form_question_map_pkey PRIMARY KEY (form_id, question);
CREATE UNIQUE INDEX form_question_map_pkey ON digest.form_question_map USING btree (form_id, question);

-- digest.form_responses
--   token                              text not null
--   form_id                            text not null
--   form_name                          text not null
--   member_at_id                       text
--   email                              text
--   submitted_at                       timestamp with time zone not null
--   answers                            jsonb not null
--   raw                                jsonb not null
--   synced_at                          timestamp with time zone not null default now()
alter table digest.form_responses add constraint form_responses_pkey PRIMARY KEY (token);
CREATE INDEX form_responses_form_idx ON digest.form_responses USING btree (form_id, submitted_at DESC);
CREATE INDEX form_responses_member_idx ON digest.form_responses USING btree (member_at_id, submitted_at DESC);
CREATE UNIQUE INDEX form_responses_pkey ON digest.form_responses USING btree (token);

-- digest.form_scope
--   form_id                            text not null
--   scope                              text not null
--   note                               text
alter table digest.form_scope add constraint form_scope_pkey PRIMARY KEY (form_id);
alter table digest.form_scope add constraint form_scope_scope_check CHECK ((scope = ANY (ARRAY['profile'::text, 'event_trend'::text])));
CREATE UNIQUE INDEX form_scope_pkey ON digest.form_scope USING btree (form_id);

-- digest.member_attributes
--   at_member_id                       text not null
--   full_name                          text
--   membership_status                  text
--   city                               text
--   state                              text
--   country                            text
--   rev_band                           text
--   under_30                           boolean
--   age_band                           text
--   categories                         text[] not null default '{}'::text[]
--   sells_supplements                  boolean not null default false
--   business_model                     text[] not null default '{}'::text[]
--   channel_mix                        text[] not null default '{}'::text[]
--   sku_count                          integer
--   large_sku                          boolean not null default false
--   brands_count                       integer
--   started_year                       integer
--   title                              text
--   expertise                          text
--   main_niche                         text
--   fun_fact                           text
--   tiktok_seller                      boolean not null default false
--   provenance                         jsonb not null default '{}'::jsonb
--   refreshed_at                       timestamp with time zone not null default now()
--   chapter_affiliation                text[]
--   chapter_ids                        text[]
alter table digest.member_attributes add constraint member_attributes_pkey PRIMARY KEY (at_member_id);
CREATE UNIQUE INDEX member_attributes_pkey ON digest.member_attributes USING btree (at_member_id);

-- digest.member_edges
--   a_id                               text not null
--   b_id                               text not null
--   edge_type                          text not null
--   weight                             numeric not null
--   evidence                           jsonb not null default '{}'::jsonb
--   refreshed_at                       timestamp with time zone not null default now()
alter table digest.member_edges add constraint member_edges_check CHECK ((a_id < b_id));
alter table digest.member_edges add constraint member_edges_pkey PRIMARY KEY (a_id, b_id, edge_type);
CREATE INDEX member_edges_b_idx ON digest.member_edges USING btree (b_id);
CREATE UNIQUE INDEX member_edges_pkey ON digest.member_edges USING btree (a_id, b_id, edge_type);

-- digest.member_events
--   id                                 bigint not null
--   member                             text
--   event_type                         text not null
--   meta                               jsonb
--   occurred_at                        timestamp with time zone not null default now()
--   at_member_id                       text
--   source                             text
--   cadence                            text
--   captured_at                        timestamp with time zone not null default now()
alter table digest.member_events add constraint member_events_member_fkey FOREIGN KEY (member) REFERENCES digest.members(airtable_id);
alter table digest.member_events add constraint member_events_pkey PRIMARY KEY (id);
CREATE INDEX member_events_member_idx ON digest.member_events USING btree (member, occurred_at DESC);
CREATE INDEX member_events_member_occurred_idx ON digest.member_events USING btree (at_member_id, occurred_at DESC);
CREATE INDEX member_events_type_occurred_idx ON digest.member_events USING btree (event_type, occurred_at DESC);
CREATE UNIQUE INDEX member_events_pkey ON digest.member_events USING btree (id);

-- digest.member_expertise
--   at_member_id                       text not null
--   topic                              text not null
--   score                              numeric not null default 0
--   rank_in_topic                      integer
--   pct                                numeric
--   weakness_score                     numeric not null default 0
--   evidence                           jsonb not null default '{}'::jsonb
--   refreshed_at                       timestamp with time zone not null default now()
alter table digest.member_expertise add constraint member_expertise_pkey PRIMARY KEY (at_member_id, topic);
CREATE INDEX member_expertise_topic_rank_idx ON digest.member_expertise USING btree (topic, rank_in_topic);
CREATE UNIQUE INDEX member_expertise_pkey ON digest.member_expertise USING btree (at_member_id, topic);

-- digest.member_niches
--   at_member_id                       text not null
--   niche                              text not null
--   is_main_niche                      boolean not null default false
--   source                             text not null
--   raw_value                          text
--   derived_at                         timestamp with time zone not null default now()
alter table digest.member_niches add constraint member_niches_pkey PRIMARY KEY (at_member_id, niche);
CREATE INDEX member_niches_main_idx ON digest.member_niches USING btree (at_member_id) WHERE is_main_niche;
CREATE INDEX member_niches_niche_idx ON digest.member_niches USING btree (niche);
CREATE UNIQUE INDEX member_niches_pkey ON digest.member_niches USING btree (at_member_id, niche);

-- digest.member_personas
--   at_member_id                       text not null
--   version                            integer not null default 1
--   persona                            jsonb not null
--   signals_hash                       text not null
--   signals_summary                    jsonb
--   model                              text
--   built_at                           timestamp with time zone not null default now()
alter table digest.member_personas add constraint member_personas_pkey PRIMARY KEY (at_member_id);
CREATE UNIQUE INDEX member_personas_pkey ON digest.member_personas USING btree (at_member_id);

-- digest.member_personas_history
--   at_member_id                       text not null
--   version                            integer not null
--   persona                            jsonb not null
--   signals_hash                       text
--   model                              text
--   built_at                           timestamp with time zone
--   archived_at                        timestamp with time zone not null default now()
alter table digest.member_personas_history add constraint member_personas_history_pkey PRIMARY KEY (at_member_id, version);
CREATE UNIQUE INDEX member_personas_history_pkey ON digest.member_personas_history USING btree (at_member_id, version);

-- digest.member_phone_index
--   phone10                            text not null
--   at_member_id                       text not null
--   source                             text not null
--   refreshed_at                       timestamp with time zone not null default now()
alter table digest.member_phone_index add constraint member_phone_index_pkey PRIMARY KEY (phone10);
CREATE INDEX member_phone_index_member ON digest.member_phone_index USING btree (at_member_id);
CREATE UNIQUE INDEX member_phone_index_pkey ON digest.member_phone_index USING btree (phone10);

-- digest.member_profile_embeddings
--   at_member_id                       text not null
--   profile_text                       text not null
--   embedding                          extensions.vector(1024)
--   built_at                           timestamp with time zone not null default now()
alter table digest.member_profile_embeddings add constraint member_profile_embeddings_pkey PRIMARY KEY (at_member_id);
CREATE UNIQUE INDEX member_profile_embeddings_pkey ON digest.member_profile_embeddings USING btree (at_member_id);

-- digest.member_profiles
--   at_member_id                       text not null
--   full_name                          text
--   email                              text
--   status                             text
--   plan_name                          text
--   subscription_status                text
--   subscription_started               text
--   join_date                          date
--   paid_date                          date
--   next_renewal                       date
--   next_renewal_amount                numeric
--   scheduled_cancel                   date
--   collection_paused                  boolean
--   mrr                                numeric
--   membership_fee                     numeric
--   billing_cycle                      text
--   stripe_customer_id                 text
--   stripe_subscription_id             text
--   engagement_score                   numeric
--   score_breakdown                    jsonb
--   score_updated                      date
--   at_fields                          jsonb
--   application                        jsonb
--   application_at                     timestamp with time zone
--   synced_at                          timestamp with time zone not null default now()
--   application_form                   text
--   lifetime_paid                      numeric
--   lifetime_paid_first_payment        date
--   lifetime_paid_payments             integer
--   lifetime_paid_synced_at            timestamp with time zone
--   rough_benchmark_paid               numeric
--   lifetime_paid_vs_benchmark_pct     numeric
alter table digest.member_profiles add constraint member_profiles_pkey PRIMARY KEY (at_member_id);
CREATE INDEX member_profiles_email_idx ON digest.member_profiles USING btree (lower(email));
CREATE UNIQUE INDEX member_profiles_pkey ON digest.member_profiles USING btree (at_member_id);

-- digest.member_sessions
--   token_hash                         text not null
--   member                             text
--   created_at                         timestamp with time zone not null default now()
--   last_seen_at                       timestamp with time zone not null default now()
--   ended_at                           timestamp with time zone
--   expires_at                         timestamp with time zone
--   ip                                 text
--   user_agent                         text
--   browser                            text
--   os                                 text
--   device                             text
alter table digest.member_sessions add constraint member_sessions_member_fkey FOREIGN KEY (member) REFERENCES digest.members(airtable_id);
alter table digest.member_sessions add constraint member_sessions_pkey PRIMARY KEY (token_hash);
CREATE INDEX member_sessions_member_idx ON digest.member_sessions USING btree (member, last_seen_at DESC);
CREATE UNIQUE INDEX member_sessions_pkey ON digest.member_sessions USING btree (token_hash);

-- digest.member_state_snapshot
--   at_member_id                       text not null
--   membership_status                  text
--   chapter_affiliation                text
--   rev_band                           text
--   main_niche                         text
--   city                               text
--   state                              text
--   snapped_at                         timestamp with time zone not null default now()
alter table digest.member_state_snapshot add constraint member_state_snapshot_pkey PRIMARY KEY (at_member_id);
CREATE UNIQUE INDEX member_state_snapshot_pkey ON digest.member_state_snapshot USING btree (at_member_id);

-- digest.members
--   airtable_id                        text not null
--   phone                              text
--   email                              text
--   name                               text
--   crm_member_id                      text
--   membership_status                  text
--   email_subscribed                   boolean
--   channel_subscriptions              jsonb
--   channels_present                   text[]
--   email_format_preference            text
--   digest_min_activity                text
--   msgs_7d                            integer default 0
--   msgs_30d                           integer default 0
--   wa_last_active_at                  timestamp with time zone
--   portal_last_seen_at                timestamp with time zone
--   session_count                      integer default 0
--   synced_at                          timestamp with time zone not null default now()
--   otp_code_hash                      text
--   otp_expires_at                     timestamp with time zone
--   delivery_email                     text
--   delivery_email_verified            boolean
--   onboarding_scope                   text
--   onboarding_complete                boolean
--   onboarding_banner_dismissed        boolean
--   delivery_otp_hash                  text
--   delivery_otp_expires_at            timestamp with time zone
--   at_member_id                       text
--   full_name                          text
--   olivia_welcomed_at                 timestamp with time zone
--   olivia_interactions                integer not null default 0
--   olivia_last_used_at                timestamp with time zone
--   olivia_optout_at                   timestamp with time zone
alter table digest.members add constraint members_phone_key UNIQUE (phone);
alter table digest.members add constraint members_pkey PRIMARY KEY (airtable_id);
CREATE INDEX members_email_idx ON digest.members USING btree (lower(email));
CREATE INDEX members_phone_idx ON digest.members USING btree (phone);
CREATE UNIQUE INDEX members_phone_key ON digest.members USING btree (phone);
CREATE UNIQUE INDEX members_pkey ON digest.members USING btree (airtable_id);

-- digest.olivia_alarm_config
--   k                                  text not null
--   v                                  text not null
alter table digest.olivia_alarm_config add constraint olivia_alarm_config_pkey PRIMARY KEY (k);
CREATE UNIQUE INDEX olivia_alarm_config_pkey ON digest.olivia_alarm_config USING btree (k);

-- digest.olivia_alarm_state
--   kind                               text not null
--   is_firing                          boolean not null default false
--   last_alert_at                      timestamp with time zone
--   last_ok_at                         timestamp with time zone
--   detail                             text
--   ping_request_id                    bigint
alter table digest.olivia_alarm_state add constraint olivia_alarm_state_pkey PRIMARY KEY (kind);
CREATE UNIQUE INDEX olivia_alarm_state_pkey ON digest.olivia_alarm_state USING btree (kind);

-- digest.olivia_billing_nudges
--   at_member_id                       text not null
--   last_nudged_at                     timestamp with time zone not null default now()
alter table digest.olivia_billing_nudges add constraint olivia_billing_nudges_pkey PRIMARY KEY (at_member_id);
CREATE UNIQUE INDEX olivia_billing_nudges_pkey ON digest.olivia_billing_nudges USING btree (at_member_id);

-- digest.olivia_feedback
--   wamid                              text not null
--   phone                              text not null
--   emoji                              text
--   reacted_at                         timestamp with time zone not null default now()
--   updated_at                         timestamp with time zone not null default now()
--   cleared_at                         timestamp with time zone
alter table digest.olivia_feedback add constraint olivia_feedback_pkey PRIMARY KEY (wamid, phone);
CREATE UNIQUE INDEX olivia_feedback_pkey ON digest.olivia_feedback USING btree (wamid, phone);

-- digest.olivia_job_heartbeats
--   job                                text not null
--   last_run_at                        timestamp with time zone
--   last_success_at                    timestamp with time zone
--   status                             text
--   detail                             text
--   max_age_hours                      integer not null default 26
alter table digest.olivia_job_heartbeats add constraint olivia_job_heartbeats_pkey PRIMARY KEY (job);
CREATE UNIQUE INDEX olivia_job_heartbeats_pkey ON digest.olivia_job_heartbeats USING btree (job);

-- digest.olivia_messages
--   id                                 bigint not null default nextval('digest.olivia_messages_id_seq'::regclass)
--   phone                              text not null
--   member                             text
--   role                               text not null
--   text                               text
--   wamid                              text
--   route                              text
--   focus_chat                         text
--   latency_ms                         integer
--   created_at                         timestamp with time zone not null default now()
--   plan                               jsonb
alter table digest.olivia_messages add constraint olivia_messages_member_fkey FOREIGN KEY (member) REFERENCES digest.members(airtable_id);
alter table digest.olivia_messages add constraint olivia_messages_pkey PRIMARY KEY (id);
alter table digest.olivia_messages add constraint olivia_messages_role_check CHECK ((role = ANY (ARRAY['member'::text, 'olivia'::text])));
CREATE INDEX olivia_messages_created_idx ON digest.olivia_messages USING btree (created_at DESC);
CREATE INDEX olivia_messages_phone_time_idx ON digest.olivia_messages USING btree (phone, created_at DESC);
CREATE UNIQUE INDEX olivia_messages_pkey ON digest.olivia_messages USING btree (id);

-- digest.olivia_question_labels
--   message_id                         bigint not null
--   topic                              text not null
--   labeled_at                         timestamp with time zone not null default now()
--   model                              text
alter table digest.olivia_question_labels add constraint olivia_question_labels_message_id_fkey FOREIGN KEY (message_id) REFERENCES digest.olivia_messages(id) ON DELETE CASCADE;
alter table digest.olivia_question_labels add constraint olivia_question_labels_pkey PRIMARY KEY (message_id);
CREATE INDEX olivia_question_labels_topic_idx ON digest.olivia_question_labels USING btree (topic);
CREATE UNIQUE INDEX olivia_question_labels_pkey ON digest.olivia_question_labels USING btree (message_id);

-- digest.olivia_question_topics
--   id                                 bigint not null
--   period_start                       date not null
--   period_end                         date not null
--   topic                              text not null
--   question_count                     integer not null
--   example_questions                  text[] not null default '{}'::text[]
--   askers                             integer
--   generated_at                       timestamp with time zone not null default now()
alter table digest.olivia_question_topics add constraint olivia_question_topics_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX olivia_question_topics_pkey ON digest.olivia_question_topics USING btree (id);

-- digest.olivia_reports
--   id                                 bigint not null
--   phone                              text not null
--   member_name                        text
--   at_member_id                       text
--   report_text                        text not null
--   context                            text
--   status                             text not null default 'new'::text
--   created_at                         timestamp with time zone not null default now()
--   cleared_at                         timestamp with time zone
alter table digest.olivia_reports add constraint olivia_reports_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX olivia_reports_pkey ON digest.olivia_reports USING btree (id);

-- digest.olivia_requests
--   id                                 bigint not null
--   phone                              text not null
--   member_name                        text
--   at_member_id                       text
--   request                            text not null
--   status                             text not null default 'new'::text
--   created_at                         timestamp with time zone not null default now()
--   context                            text
--   summary                            text
--   cleared_at                         timestamp with time zone
alter table digest.olivia_requests add constraint olivia_requests_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX olivia_requests_pkey ON digest.olivia_requests USING btree (id);

-- digest.olivia_seen
--   wamid                              text not null
--   phone                              text
--   seen_at                            timestamp with time zone not null default now()
alter table digest.olivia_seen add constraint olivia_seen_pkey PRIMARY KEY (wamid);
CREATE UNIQUE INDEX olivia_seen_pkey ON digest.olivia_seen USING btree (wamid);

-- digest.olivia_sends
--   wamid                              text not null
--   to_phone                           text
--   status                             text
--   error_code                         integer
--   error_title                        text
--   conversation_id                    text
--   conversation_origin                text
--   first_seen_at                      timestamp with time zone not null default now()
--   status_at                          timestamp with time zone
--   updated_at                         timestamp with time zone not null default now()
alter table digest.olivia_sends add constraint olivia_sends_pkey PRIMARY KEY (wamid);
CREATE INDEX olivia_sends_phone_idx ON digest.olivia_sends USING btree (to_phone);
CREATE INDEX olivia_sends_status_idx ON digest.olivia_sends USING btree (status);
CREATE UNIQUE INDEX olivia_sends_pkey ON digest.olivia_sends USING btree (wamid);

-- digest.olivia_webhook_events
--   id                                 bigint not null
--   received_at                        timestamp with time zone not null default now()
--   msg_type                           text not null
--   from_phone                         text
--   wamid                              text
--   payload                            jsonb not null
alter table digest.olivia_webhook_events add constraint olivia_webhook_events_pkey PRIMARY KEY (id);
CREATE INDEX olivia_webhook_events_received ON digest.olivia_webhook_events USING btree (received_at DESC);
CREATE INDEX olivia_webhook_events_type ON digest.olivia_webhook_events USING btree (msg_type, received_at DESC);
CREATE UNIQUE INDEX olivia_webhook_events_pkey ON digest.olivia_webhook_events USING btree (id);

-- digest.partner_reviews
--   review_id                          text not null
--   partner_id                         text not null
--   rating                             integer
--   review_text                        text
--   app_user_id                        text
--   reviewed_at                        timestamp with time zone
--   synced_at                          timestamp with time zone not null default now()
alter table digest.partner_reviews add constraint partner_reviews_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES digest.partners_catalog(partner_id) ON DELETE CASCADE;
alter table digest.partner_reviews add constraint partner_reviews_pkey PRIMARY KEY (review_id);
CREATE INDEX partner_reviews_partner_idx ON digest.partner_reviews USING btree (partner_id);
CREATE UNIQUE INDEX partner_reviews_pkey ON digest.partner_reviews USING btree (review_id);

-- digest.partners_catalog
--   partner_id                         text not null
--   name                               text not null
--   description_text                   text
--   offer_value                        text
--   categories                         text[] not null default '{}'::text[]
--   featured                           boolean not null default false
--   fresh_deal                         boolean not null default false
--   rating_avg                         numeric
--   rating_count                       integer not null default 0
--   review_count                       integer not null default 0
--   claim_count                        integer not null default 0
--   page_view_count                    integer not null default 0
--   status                             text not null default 'published'::text
--   access_restriction                 text not null default 'public'::text
--   access_detail                      jsonb
--   app_created_at                     timestamp with time zone
--   app_updated_at                     timestamp with time zone
--   synced_at                          timestamp with time zone not null default now()
--   category_names                     text[] not null default '{}'::text[]
--   search_tsv                         tsvector default (((setweight(to_tsvector('english'::regconfig, COALESCE(name, ''::text)), 'A'::"char") || setweight(to_tsvector('english'::regconfig, COALESCE(offer_value, ''::text)), 'B'::"char")) || setweight(to_tsvector('english'::regconfig, digest.immutable_text_array_join(category_names)), 'B'::"char")) || setweight(to_tsvector('english'::regconfig, COALESCE(description_text, ''::text)), 'C'::"char"))
--   embedding                          extensions.vector(1024)
--   logo_url                           text
alter table digest.partners_catalog add constraint partners_catalog_pkey PRIMARY KEY (partner_id);
CREATE INDEX partners_catalog_tsv_idx ON digest.partners_catalog USING gin (search_tsv);
CREATE UNIQUE INDEX partners_catalog_pkey ON digest.partners_catalog USING btree (partner_id);

-- digest.summaries
--   airtable_id                        text not null
--   summary_key                        text not null
--   date                               date not null
--   chat_id                            text
--   chat_name                          text not null
--   period_type                        text not null
--   tl_dr                              text
--   summary_text                       text
--   topics                             text
--   notable_members                    text
--   links_shared                       text
--   msg_count                          integer
--   participant_count                  integer
--   prompt_version                     text
--   synced_at                          timestamp with time zone not null default now()
alter table digest.summaries add constraint summaries_period_type_check CHECK ((period_type = ANY (ARRAY['daily'::text, 'weekly'::text])));
alter table digest.summaries add constraint summaries_pkey PRIMARY KEY (airtable_id);
alter table digest.summaries add constraint summaries_summary_key_key UNIQUE (summary_key);
CREATE INDEX summaries_chat_date_idx ON digest.summaries USING btree (chat_name, date DESC);
CREATE INDEX summaries_date_idx ON digest.summaries USING btree (date DESC);
CREATE INDEX summaries_period_idx ON digest.summaries USING btree (period_type);
CREATE UNIQUE INDEX summaries_pkey ON digest.summaries USING btree (airtable_id);
CREATE UNIQUE INDEX summaries_summary_key_key ON digest.summaries USING btree (summary_key);

-- digest.video_files
--   file_key                           text not null
--   video_id                           text not null
--   ordinal                            integer not null
--   file_name                          text not null
--   storage_path                       text
--   file_kind                          text not null default 'unknown'::text
--   extracted_text                     text
--   extracted_at                       timestamp with time zone
--   page_count                         integer
--   synced_at                          timestamp with time zone not null default now()
--   storage_object                     text
--   description                        text
--   described_at                       timestamp with time zone
alter table digest.video_files add constraint video_files_pkey PRIMARY KEY (file_key);
alter table digest.video_files add constraint video_files_video_id_fkey FOREIGN KEY (video_id) REFERENCES digest.videos_catalog(video_id) ON DELETE CASCADE;
CREATE INDEX video_files_video_idx ON digest.video_files USING btree (video_id);
CREATE UNIQUE INDEX video_files_pkey ON digest.video_files USING btree (file_key);

-- digest.video_speakers
--   user_id                            text not null
--   display_name                       text not null
--   email                              text
--   member_record_id                   text
--   member_type                        text
--   tier_name                          text
--   status                             text
--   joined_at                          timestamp with time zone
--   last_seen_at                       timestamp with time zone
--   synced_at                          timestamp with time zone not null default now()
alter table digest.video_speakers add constraint video_speakers_pkey PRIMARY KEY (user_id);
CREATE UNIQUE INDEX video_speakers_pkey ON digest.video_speakers USING btree (user_id);

-- digest.videos_catalog
--   video_id                           text not null
--   title                              text not null
--   description_text                   text
--   duration                           text
--   duration_sec                       integer
--   category_ids                       text[] not null default '{}'::text[]
--   category_names                     text[] not null default '{}'::text[]
--   tag_names                          text[] not null default '{}'::text[]
--   speaker_ids                        text[] not null default '{}'::text[]
--   event_ids                          text[] not null default '{}'::text[]
--   view_count                         integer not null default 0
--   like_count                         integer not null default 0
--   comment_count                      integer not null default 0
--   status                             text not null
--   access_restriction                 text not null
--   app_created_at                     timestamp with time zone
--   app_updated_at                     timestamp with time zone
--   synced_at                          timestamp with time zone not null default now()
--   cliff_notes                        text
--   subcategory_ids                    text[] not null default '{}'::text[]
--   file_names                         text[] not null default '{}'::text[]
--   deleted_at                         timestamp with time zone
--   speaker_names                      text[] not null default '{}'::text[]
--   files_text                         text
--   call_type                          text
--   embedding                          extensions.vector(1024)
--   thumbnail_url                      text
--   summary                            text
--   summary_source                     text
--   search_tsv                         tsvector default ((((((((setweight(to_tsvector('english'::regconfig, COALESCE(title, ''::text)), 'A'::"char") || setweight(to_tsvector('english'::regconfig, digest.immutable_text_array_join(speaker_names)), 'A'::"char")) || setweight(to_tsvector('english'::regconfig, COALESCE(call_type, ''::text)), 'A'::"char")) || setweight(to_tsvector('english'::regconfig, digest.immutable_text_array_join(category_names)), 'B'::"char")) || setweight(to_tsvector('english'::regconfig, digest.immutable_text_array_join(tag_names)), 'B'::"char")) || setweight(to_tsvector('english'::regconfig, COALESCE(cliff_notes, ''::text)), 'B'::"char")) || setweight(to_tsvector('english'::regconfig, COALESCE(summary, ''::text)), 'B'::"char")) || setweight(to_tsvector('english'::regconfig, COALESCE(files_text, ''::text)), 'B'::"char")) || setweight(to_tsvector('english'::regconfig, COALESCE(description_text, ''::text)), 'C'::"char"))
--   zoom_recording_stamp               text
alter table digest.videos_catalog add constraint videos_catalog_pkey PRIMARY KEY (video_id);
CREATE INDEX videos_catalog_call_type_idx ON digest.videos_catalog USING btree (call_type);
CREATE INDEX videos_catalog_created_idx ON digest.videos_catalog USING btree (app_created_at DESC);
CREATE INDEX videos_catalog_embedding_hnsw ON digest.videos_catalog USING hnsw (embedding extensions.vector_cosine_ops);
CREATE INDEX videos_catalog_tsv ON digest.videos_catalog USING gin (search_tsv);
CREATE INDEX videos_catalog_zoom_stamp ON digest.videos_catalog USING btree (zoom_recording_stamp) WHERE (zoom_recording_stamp IS NOT NULL);
CREATE UNIQUE INDEX videos_catalog_pkey ON digest.videos_catalog USING btree (video_id);

-- digest.wa_messages
--   id                                 text not null
--   chat_id                            text not null
--   chat_name                          text
--   sender_phone                       text
--   sender_member                      text
--   sent_at                            timestamp with time zone not null
--   type                               text
--   text                               text
--   reply_to                           text
--   raw                                jsonb
--   ingested_at                        timestamp with time zone not null default now()
alter table digest.wa_messages add constraint wa_messages_pkey PRIMARY KEY (id);
alter table digest.wa_messages add constraint wa_messages_sender_member_fkey FOREIGN KEY (sender_member) REFERENCES digest.members(airtable_id);
CREATE INDEX wa_messages_chat_time_idx ON digest.wa_messages USING btree (chat_id, sent_at DESC);
CREATE INDEX wa_messages_member_chat_idx ON digest.wa_messages USING btree (sender_member, chat_id, sent_at DESC);
CREATE UNIQUE INDEX wa_messages_pkey ON digest.wa_messages USING btree (id);

-- digest.zoom_name_alias
--   name_folded                        text not null
--   at_member_id                       text
--   confidence                         text not null default 'auto'::text
--   decided_by                         text
--   decided_at                         timestamp with time zone not null default now()
--   note                               text
alter table digest.zoom_name_alias add constraint zoom_name_alias_pkey PRIMARY KEY (name_folded);
CREATE INDEX zoom_alias_member ON digest.zoom_name_alias USING btree (at_member_id) WHERE (at_member_id IS NOT NULL);
CREATE UNIQUE INDEX zoom_name_alias_pkey ON digest.zoom_name_alias USING btree (name_folded);
