-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.app_member_feed(p_email text, p_recent_queries text[] DEFAULT NULL::text[], p_interest_embedding text DEFAULT NULL::text, p_limit_each integer DEFAULT 5)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare
  v_email text := lower(nullif(trim(p_email), ''));
  v_n int; v_atid text; v_phone text; v_name text; v_key_id text;
  v_city text; v_state text; v_chapter text; v_niche text; v_expertise text;
  v_persona jsonb; v_persona_built timestamptz;
  v_terms text[] := '{}'; v_avoid text[] := '{}'; v_query text;
  v_lim int := least(greatest(coalesce(p_limit_each, 5), 1), 10);
  q text;
begin
  if v_email is null then return '{}'::jsonb; end if;

  -- resolution 1: the members mirror (richest row). resolution 2: the AT profiles mirror
  -- (Preferred Email) for members the WA-shaped mirror never held. Fail-closed both ways.
  select count(distinct m.at_member_id) into v_n
  from digest.members m
  where lower(m.email) = v_email and m.at_member_id is not null and digest.is_active_member_status(m.membership_status);
  if v_n = 1 then
    select m.at_member_id, m.phone, coalesce(m.full_name, m.name)
      into v_atid, v_phone, v_name
    from digest.members m
    where lower(m.email) = v_email and m.at_member_id is not null and digest.is_active_member_status(m.membership_status)
    order by (m.phone is not null) desc
    limit 1;
  elsif v_n = 0 then
    select count(distinct ma.at_member_id) into v_n
    from digest.member_attributes ma
    join digest.member_profiles mp on mp.at_member_id = ma.at_member_id
    where lower(trim(mp.at_fields->>'Preferred Email')) = v_email
      and digest.is_active_member_status(ma.membership_status);
    if v_n <> 1 then return '{}'::jsonb; end if;
    select ma.at_member_id, ma.full_name into v_atid, v_name
    from digest.member_attributes ma
    join digest.member_profiles mp on mp.at_member_id = ma.at_member_id
    where lower(trim(mp.at_fields->>'Preferred Email')) = v_email
      and digest.is_active_member_status(ma.membership_status)
    limit 1;
    select m.phone into v_phone from digest.members m
    where m.at_member_id = v_atid and m.phone is not null limit 1;
  else
    return '{}'::jsonb;
  end if;

  v_key_id := case when nullif(trim(v_phone), '') is null then v_atid end;

  select ma.city, ma.state, ma.chapter_affiliation, ma.main_niche, ma.expertise
    into v_city, v_state, v_chapter, v_niche, v_expertise
  from digest.member_attributes ma where ma.at_member_id = v_atid;

  select mp.persona, mp.built_at into v_persona, v_persona_built
  from digest.member_personas mp where mp.at_member_id = v_atid;

  if v_persona is not null then
    select coalesce(array_agg(distinct t), '{}') into v_avoid from (
      select lower(w) as t
      from jsonb_array_elements(coalesce(v_persona->'avoid', '[]'::jsonb)) a,
           regexp_split_to_table(coalesce(a->>'item', ''), '[^A-Za-z0-9]+') w
      where length(w) >= 4
    ) x;
    select coalesce(array_agg(t), '{}') into v_terms from (
      select distinct lower(w) as t
      from jsonb_array_elements(coalesce(v_persona->'focus', '[]'::jsonb)) f,
           regexp_split_to_table(coalesce(f->>'item', ''), '[^A-Za-z0-9]+') w
      where length(w) >= 4 and not (lower(w) = any(v_avoid))
      limit 10
    ) x;
    v_query := nullif(left((
      select string_agg(f->>'item', ' ')
      from jsonb_array_elements(coalesce(v_persona->'focus', '[]'::jsonb)) f), 300), '');
  end if;
  if coalesce(array_length(v_terms, 1), 0) = 0 then
    select coalesce(array_agg(t), '{}') into v_terms from (
      select distinct lower(t) as t from (
        select unnest(coalesce((select ma.categories from digest.member_attributes ma where ma.at_member_id = v_atid), '{}'::text[])) as t
        union all
        select w from regexp_split_to_table(coalesce(v_niche, '') || ' ' || coalesce(v_expertise, ''), '[^A-Za-z0-9]+') w
      ) raw
      where length(t) >= 4
      limit 8
    ) x;
  end if;
  if v_query is null then
    v_query := nullif(trim(coalesce(v_niche, '') || ' ' || coalesce(v_expertise, '')), '');
  end if;
  if p_recent_queries is not null then
    for q in select unnest(p_recent_queries) limit 5 loop
      q := lower(regexp_replace(coalesce(q, ''), '[^A-Za-z0-9 ]+', ' ', 'g'));
      q := nullif(trim(q), '');
      if q is not null and length(q) >= 4 and not (q = any(v_terms)) then
        v_terms := v_terms || q;
      end if;
    end loop;
  end if;

  return jsonb_build_object(
    'member', jsonb_build_object(
      'name', v_name, 'city', v_city, 'state', v_state, 'chapter', v_chapter),
    'persona', coalesce(
      jsonb_build_object(
        'summary', v_persona->>'summary',
        'focus', v_persona->'focus',
        'avoid', v_persona->'avoid',
        'preferences', v_persona->'preferences',
        'built_at', v_persona_built,
        'interest_terms', to_jsonb(v_terms)),
      (select jsonb_build_object(
          'main_niche', ma.main_niche, 'expertise', ma.expertise, 'categories', ma.categories,
          'business_model', ma.business_model, 'channel_mix', ma.channel_mix,
          'interest_terms', to_jsonb(v_terms))
        from digest.member_attributes ma where ma.at_member_id = v_atid)),
    'events_near', case when coalesce(v_city, v_state) is not null then
        (select coalesce(jsonb_agg(x.j), '[]'::jsonb) from (
           select to_jsonb(e) as j
           from digest.event_lookup(v_phone, null, coalesce(v_city, v_state), null, false, 8, null, v_key_id) e
           where e.starts_at >= now()
           order by e.starts_at
           limit 3) x)
      else '[]'::jsonb end,
    'events', (select coalesce(jsonb_agg(to_jsonb(e)), '[]'::jsonb)
               from digest.event_lookup(v_phone, null, null, null, false, v_lim, null, v_key_id) e),
    'videos', (select coalesce(jsonb_agg(to_jsonb(v)), '[]'::jsonb)
               from digest.video_search(v_phone, v_query, v_lim, p_interest_embedding, v_key_id) v),
    'partners', (select coalesce(jsonb_agg(to_jsonb(p)), '[]'::jsonb)
                 from digest.partner_lookup(v_phone, v_query, v_lim, p_interest_embedding, v_key_id) p),
    'threads', (select coalesce(jsonb_agg(to_jsonb(c)), '[]'::jsonb)
                from digest.content_search_v2(
                  p_phone => v_phone, p_terms => v_terms,
                  p_sources => array['fb_post', 'wa_message'],
                  p_since => current_date - 14, p_limit => v_lim + 3,
                  p_embedding => p_interest_embedding, p_at_member_id => v_key_id) c)
  );
end $function$
