-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.attr_clean(v text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
AS $function$
  select nullif(nullif(nullif(nullif(trim(case when v like '["%"]'
              then replace(substring(v from 3 for greatest(length(v) - 4, 0)), '", "', ', ')
              else v end), ''), 'N/A'), 'n/a'), 'NA')
$function$
