-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.attr_list(j jsonb)
 RETURNS text[]
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO ''
AS $function$
  select coalesce(array_agg(distinct v order by v), '{}')
  from (
    select nullif(trim(both ' ''' from regexp_replace(e, '\s+', ' ', 'g')), '') as v
    from jsonb_array_elements_text(case when jsonb_typeof(j) = 'array' then j else '[]'::jsonb end) e
  ) x where v is not null
$function$
