-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.attr_text(j jsonb, k text)
 RETURNS text
 LANGUAGE plpgsql
 IMMUTABLE
 SET search_path TO 'digest'
AS $function$
declare v text;
begin
  if j is null then return null; end if;
  if jsonb_typeof(j->k) = 'array' then
    return nullif(array_to_string(digest.attr_list(j->k), ', '), '');
  end if;
  v := nullif(trim(j->>k), '');
  if v is null then return null; end if;
  if v ~ '^\s*\[' then
    begin
      return nullif(array_to_string(digest.attr_list(v::jsonb), ', '), '');
    exception when others then return v;
    end;
  end if;
  return v;
end $function$
