-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.attr_num(t text)
 RETURNS numeric
 LANGUAGE plpgsql
 IMMUTABLE
 SET search_path TO ''
AS $function$
begin
  return nullif(regexp_replace(coalesce(t, ''), '[^0-9.]', '', 'g'), '')::numeric;
exception when others then return null;
end $function$
