-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.chat_info(p_phone text, p_chat text DEFAULT NULL::text)
 RETURNS TABLE(chat_name text, is_member boolean, verification_required boolean, requirement text, call_schedule text, zoom_link text, moderators text, join_link text)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare
  v_n int; v_chats text[];
begin
  select case when digest.resolve_asker(p_phone) is not null then 1 else 0 end into v_n;
  if v_n <> 1 then return; end if;
  select coalesce(m.channels_present, '{}') into v_chats
    from digest.member_identity m where m.at_member_id = digest.resolve_asker(p_phone) and digest.is_active_member_status(m.membership_status);

  return query
  select c.chat_name,
         c.chat_name = any(v_chats) as is_member,
         coalesce(c.verification_required, false),
         c.requirement_text,
         c.call_schedule,
         -- zoom links only for chats they are actually in
         case when c.chat_name = any(v_chats) then c.zoom_link end as zoom_link,
         c.moderators,
         case
           when c.chat_name = any(v_chats) then c.invite_url
           when coalesce(c.verification_required, false) then c.verification_form
           else coalesce(nullif(nullif(trim(c.optin_form), 'None needed'), 'None needed '), c.invite_url)
         end as join_link
  from digest.chats c
  where c.invite_url is not null
    and (p_chat is null or c.chat_name ilike '%' || trim(p_chat) || '%')
  order by c.chat_name;
end $function$
