-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.chat_recommendations_v2(p_phone text)
 RETURNS TABLE(chat_name text, verification_required boolean, requirement text, qualifies boolean, join_link text, why text)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare v_atid text;
begin
  select digest.resolve_asker(p_phone) into v_atid;

  return query
  with v1 as (
    select t.* from digest.chat_recommendations(p_phone)
      with ordinality as t(chat_name, verification_required, requirement, qualifies, join_link, ord)
  ), topics as (
    select * from digest.member_topic_profile(v_atid)
  ), circle as (
    select g.b_id from digest.member_edges g
    where g.a_id = v_atid order by g.weight desc limit 12
  ), scored as (
    select v.*,
      (select tp.topic from topics tp
        where exists (select 1 from unnest(tp.words) w where v.chat_name ~* ('\m'||w||'\M'))
        order by tp.sort_score desc limit 1) as fit_topic,
      coalesce((select count(*) from digest.members mm
        where mm.at_member_id in (select b_id from circle)
          and v.chat_name = any(coalesce(mm.channels_present, '{}'))), 0) as circ
    from v1 v
  )
  select s.chat_name, s.verification_required, s.requirement, s.qualifies, s.join_link,
    case when s.fit_topic is not null then 'fits your focus: ' || s.fit_topic
         when s.circ >= 3 then 'several people you already know in MDS are in it'
         end as why
  from scored s
  order by (s.fit_topic is not null) desc, s.circ desc, s.ord;
end $function$
