-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.chat_recommendations(p_phone text)
 RETURNS TABLE(chat_name text, verification_required boolean, requirement text, qualifies boolean, join_link text)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare
  v_n int; v_atid text; v_chats text[]; me digest.member_attributes;
begin
  select count(*) into v_n from digest.members m where m.phone = p_phone and digest.is_active_member_status(m.membership_status);
  if v_n <> 1 then return; end if;
  select m.at_member_id, coalesce(m.channels_present, '{}') into v_atid, v_chats
    from digest.members m where m.phone = p_phone and digest.is_active_member_status(m.membership_status);
  select * into me from digest.member_attributes ma where ma.at_member_id = v_atid;

  return query
  select c.chat_name, coalesce(c.verification_required, false), c.requirement_text,
    q.qualifies,
    case when coalesce(c.verification_required, false) then c.verification_form
         else coalesce(nullif(nullif(trim(c.optin_form), 'None needed'), 'None needed '), c.invite_url) end
  from digest.chats c
  cross join lateral (select case c.chat_name
      when 'MDS Centurion 20M+' then (me.rev_band = '20M+')
      when 'MDS Under 30'       then me.under_30
      when 'MDS Supplements'    then me.sells_supplements
      when 'MDS TikTok'         then me.tiktok_seller
      when 'MDS Large SKU'      then me.large_sku
      when 'MDS Real Estate'    then null::boolean       -- no data field anywhere: describe only
      else true end as qualifies) q
  where c.invite_url is not null
    and not (c.chat_name = any(v_chats))
    and (q.qualifies is true or q.qualifies is null)
  order by coalesce(c.verification_required, false) desc, c.chat_name;
end $function$
