-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.community_info(p_phone text)
 RETURNS TABLE(active_members bigint, whatsapp_chats bigint, upcoming_events bigint, chapters bigint, chapter_breakdown jsonb, gender_split jsonb)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare v_n int;
begin
  select count(*) into v_n from digest.members m where m.phone = p_phone and digest.is_active_member_status(m.membership_status);
  if v_n <> 1 then return; end if;
  return query
  with member_chapters as (
    select trim(ch.one) as chapter
    from digest.member_profiles mp
    join digest.member_attributes ma on ma.at_member_id = mp.at_member_id
    cross join lateral regexp_split_to_table(
      coalesce(digest.attr_clean(mp.at_fields->>'Chapter Affiliation'), ''), ',[[:space:]]*') ch(one)
    where ma.membership_status in ('Current Member','New Member','Pending Group Entrance','Current Member- Not Renewing')
      and trim(ch.one) not in ('', 'No Chapter Affiliation', 'Chapter Leads')
  ),
  genders as (
    select case
             when lower(coalesce(nullif(trim(mp.at_fields->>'Gender'),''),'unspecified')) in ('male','female')
               then lower(trim(mp.at_fields->>'Gender'))
             else 'unspecified'
           end as g
    from digest.member_profiles mp
    join digest.member_attributes ma on ma.at_member_id = mp.at_member_id
    where ma.membership_status in ('Current Member','New Member','Pending Group Entrance','Current Member- Not Renewing')
  )
  select
    (select count(*) from digest.member_attributes ma
      where ma.membership_status in ('Current Member','New Member','Pending Group Entrance','Current Member- Not Renewing')),
    (select count(*) from digest.chats c where c.invite_url is not null),
    (select count(*) from digest.events_catalog c
      where coalesce(c.app_starts_at, c.start_at) >= now()
        and c.phase in ('Registration Open','Confirmed')),
    (select count(distinct mc.chapter) from member_chapters mc),
    (select coalesce(jsonb_object_agg(t.chapter, t.n order by t.n desc), '{}'::jsonb)
       from (select mc.chapter, count(*) as n from member_chapters mc group by 1) t),
    (select jsonb_build_object(
        'male', count(*) filter (where g.g='male'),
        'female', count(*) filter (where g.g='female'),
        'unspecified', count(*) filter (where g.g='unspecified'),
        'note', 'self-reported; not every member provides it — treat shares as approximate')
       from genders g);
end $function$
