-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.content_ingest_summary()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
begin
  insert into digest.content_items
    (source, kind, source_id, title, tl_dr, body, occurred_at, url,
     access_rule, sensitivity, search_extra, meta)
  values (
    'wa_digest',
    new.period_type,
    new.airtable_id,
    new.chat_name || ' — ' || new.period_type || ' digest (' || new.date || ')',
    new.tl_dr,
    new.summary_text,
    (new.date::timestamp at time zone 'utc'),
    null,
    jsonb_build_object('type', 'chat_member', 'chat', new.chat_name),
    'normal',
    new.topics,
    jsonb_strip_nulls(jsonb_build_object(
      'chat_name', new.chat_name,
      'chat_id', new.chat_id,
      'topics', new.topics,
      'links_shared', new.links_shared,
      'msg_count', new.msg_count,
      'participant_count', new.participant_count)))
  on conflict (source, source_id) do update set
    kind = excluded.kind,
    title = excluded.title,
    tl_dr = excluded.tl_dr,
    body = excluded.body,
    occurred_at = excluded.occurred_at,
    access_rule = excluded.access_rule,
    sensitivity = excluded.sensitivity,
    search_extra = excluded.search_extra,
    meta = excluded.meta,
    ingested_at = now();
  return new;
end $function$
