-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.content_search_v2(p_phone text, p_terms text[] DEFAULT '{}'::text[], p_sources text[] DEFAULT NULL::text[], p_kinds text[] DEFAULT NULL::text[], p_chat text DEFAULT NULL::text, p_since date DEFAULT NULL::date, p_limit integer DEFAULT 40, p_include_restricted boolean DEFAULT false, p_author text DEFAULT NULL::text, p_embedding text DEFAULT NULL::text, p_at_member_id text DEFAULT NULL::text)
 RETURNS TABLE(source text, kind text, source_id text, title text, tl_dr text, body text, occurred_at timestamp with time zone, url text, sensitivity text, meta jsonb, search_extra text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare
  v_chats text[]; v_atid text; v_n int; v_in_fb boolean; v_vec extensions.vector(1024);
  v_q tsquery; v_tq tsquery; v_t text; v_ann bigint[];
begin
  -- identity gate: verbatim content_search
  if p_at_member_id is not null then
    select count(*) into v_n from digest.member_attributes mz where mz.at_member_id = p_at_member_id and digest.is_active_member_status(mz.membership_status);
  else
    select count(*) into v_n from digest.members mz where mz.phone = p_phone and digest.is_active_member_status(mz.membership_status);
  end if;
  if v_n <> 1 then return; end if;
  select coalesce(m.channels_present, '{}'), m.at_member_id into v_chats, v_atid
    from digest.members m where (case when p_at_member_id is not null then m.at_member_id = p_at_member_id else m.phone = p_phone end) and digest.is_active_member_status(m.membership_status) order by (m.phone is not null) desc, m.airtable_id limit 1;
  if p_at_member_id is not null and v_atid is null then v_atid := p_at_member_id; end if;

  v_in_fb := v_atid is not null and exists (select 1 from digest.fb_member_map f where f.at_member_id = v_atid);
  begin
    v_vec := nullif(trim(coalesce(p_embedding, '')), '')::extensions.vector(1024);
  exception when others then
    v_vec := null;
  end;

  -- phase 1: pure ANN candidate ids (ids only — every access filter is applied in phase 2).
  if v_vec is not null then
    begin
      perform '[1]'::extensions.vector;
      perform set_config('hnsw.ef_search', '200', true);
      perform set_config('enable_seqscan', 'off', true);
      select array_agg(t.id order by t.d) into v_ann
      from (
        select ci.id, ci.embedding operator(extensions.<=>) v_vec as d
        from digest.content_items ci
        order by ci.embedding operator(extensions.<=>) v_vec
        limit 200
      ) t;
      perform set_config('enable_seqscan', 'on', true);
    exception when others then
      v_ann := null;
      perform set_config('enable_seqscan', 'on', true);
    end;
  end if;

  -- keyword tsquery: OR of per-term stemmed phrase queries (GIN-indexable)
  if p_terms is not null then
    foreach v_t in array p_terms loop
      v_tq := phraseto_tsquery('english', coalesce(v_t, ''));
      if numnode(v_tq) > 0 then
        v_q := case when v_q is null then v_tq else v_q || v_tq end;
      end if;
    end loop;
  end if;

  return query
  with kw_pool as (
    select ci.id, ci.search_tsv as tsv, ci.occurred_at as occ
    from digest.content_items ci
    where v_q is not null and ci.search_tsv @@ v_q
      and ci.sensitivity <> 'never_surface'
      and (p_include_restricted or ci.sensitivity <> 'restricted')
      and (
        (ci.access_rule->>'type' = 'public')
        or (ci.access_rule->>'type' = 'chat_member' and ci.access_rule->>'chat' = any(v_chats))
        or (ci.access_rule->>'type' = 'owner' and v_atid is not null and ci.access_rule->>'member' = v_atid)
        or (ci.access_rule->>'type' = 'fb_group' and v_in_fb)
      )
      and (p_sources is null or ci.source = any(p_sources))
      and (p_kinds is null or ci.kind = any(p_kinds))
      and (p_chat is null or ci.meta->>'chat_name' = p_chat or ci.meta->>'chat_name' is null)
      and (p_since is null or (ci.occurred_at at time zone 'utc')::date >= p_since)
      and (p_author is null
           or digest.name_fold(coalesce(ci.meta->>'author_name',
                (select coalesce(m2.full_name, m2.name) from digest.members m2
                  where m2.airtable_id = ci.meta->>'sender_member' limit 1)))
              like '%' || digest.name_fold(p_author) || '%'
           or (ci.source = 'fb_comment' and exists (
                 select 1 from digest.content_items pp
                 where pp.source = 'fb_post' and pp.source_id = ci.meta->>'post_id'
                   and digest.name_fold(pp.meta->>'author_name') like '%' || digest.name_fold(p_author) || '%')))
    order by ts_rank_cd(ci.search_tsv, v_q) desc, ci.occurred_at desc, ci.id desc
    limit 200
  ),
  kw as (
    select y.id, y.rk from (
      select x.id,
             row_number() over (order by x.cover desc, x.rnk desc, x.occ desc, x.id desc) as rk
      from (
        select kp.id, kp.occ,
               (select count(*) from unnest(p_terms) t
                where numnode(phraseto_tsquery('english', t)) > 0
                  and kp.tsv @@ phraseto_tsquery('english', t)) as cover,
               ts_rank_cd(kp.tsv, v_q) as rnk
        from kw_pool kp
      ) x
    ) y where y.rk <= 60
  ),
  vec as (
    select y.id, row_number() over (order by y.ord) as rk
    from (
      select a.id, a.ord
      from unnest(v_ann) with ordinality as a(id, ord)
      join digest.content_items ci on ci.id = a.id
      where ci.sensitivity <> 'never_surface'
        and (p_include_restricted or ci.sensitivity <> 'restricted')
        and (
          (ci.access_rule->>'type' = 'public')
          or (ci.access_rule->>'type' = 'chat_member' and ci.access_rule->>'chat' = any(v_chats))
          or (ci.access_rule->>'type' = 'owner' and v_atid is not null and ci.access_rule->>'member' = v_atid)
          or (ci.access_rule->>'type' = 'fb_group' and v_in_fb)
        )
        and (p_sources is null or ci.source = any(p_sources))
        and (p_kinds is null or ci.kind = any(p_kinds))
        and (p_chat is null or ci.meta->>'chat_name' = p_chat or ci.meta->>'chat_name' is null)
        and (p_since is null or (ci.occurred_at at time zone 'utc')::date >= p_since)
        and (p_author is null
             or digest.name_fold(coalesce(ci.meta->>'author_name',
                  (select coalesce(m2.full_name, m2.name) from digest.members m2
                    where m2.airtable_id = ci.meta->>'sender_member' limit 1)))
                like '%' || digest.name_fold(p_author) || '%'
             or (ci.source = 'fb_comment' and exists (
                   select 1 from digest.content_items pp
                   where pp.source = 'fb_post' and pp.source_id = ci.meta->>'post_id'
                     and digest.name_fold(pp.meta->>'author_name') like '%' || digest.name_fold(p_author) || '%')))
      order by a.ord
      limit 60
    ) y
  ),
  rec as (
    select z.id, row_number() over (order by z.occ desc, z.id desc) as rk
    from (
      select ci.id, ci.occurred_at as occ
      from digest.content_items ci
      where ci.sensitivity <> 'never_surface'
        and (p_include_restricted or ci.sensitivity <> 'restricted')
        and (
          (ci.access_rule->>'type' = 'public')
          or (ci.access_rule->>'type' = 'chat_member' and ci.access_rule->>'chat' = any(v_chats))
          or (ci.access_rule->>'type' = 'owner' and v_atid is not null and ci.access_rule->>'member' = v_atid)
          or (ci.access_rule->>'type' = 'fb_group' and v_in_fb)
        )
        and (p_sources is null or ci.source = any(p_sources))
        and (p_kinds is null or ci.kind = any(p_kinds))
        and (p_chat is null or ci.meta->>'chat_name' = p_chat or ci.meta->>'chat_name' is null)
        and (p_since is null or (ci.occurred_at at time zone 'utc')::date >= p_since)
        and (p_author is null
             or digest.name_fold(coalesce(ci.meta->>'author_name',
                  (select coalesce(m2.full_name, m2.name) from digest.members m2
                    where m2.airtable_id = ci.meta->>'sender_member' limit 1)))
                like '%' || digest.name_fold(p_author) || '%'
             or (ci.source = 'fb_comment' and exists (
                   select 1 from digest.content_items pp
                   where pp.source = 'fb_post' and pp.source_id = ci.meta->>'post_id'
                     and digest.name_fold(pp.meta->>'author_name') like '%' || digest.name_fold(p_author) || '%')))
      order by ci.occurred_at desc, ci.id desc
      limit 60
    ) z
  ),
  ttl as (
    select y.id, y.rk from (
      select z.id, row_number() over (order by z.cover desc, z.occ desc, z.id desc) as rk
      from (
        select kp.id, kp.occ,
               (select count(*) from unnest(p_terms) t
                 where numnode(phraseto_tsquery('english', t)) > 0
                   and to_tsvector('english', coalesce(cit.title, '')) @@ phraseto_tsquery('english', t)) as cover
        from kw_pool kp
        join digest.content_items cit on cit.id = kp.id
      ) z where z.cover > 0
    ) y where y.rk <= 40
  ),
  merged as (
    select kw.id from kw
    union
    select vec.id from vec
    union
    select rec.id from rec
    union
    select ttl.id from ttl
  ),
  scored as (
    select mg.id,
           coalesce(1.0/(60.0 + k.rk), 0)
         + coalesce(1.0/(60.0 + v.rk), 0)
         + coalesce(1.0/(60.0 + tt.rk), 0)
         + 0.5/(60.0 + row_number() over (order by ci.occurred_at desc nulls last, ci.id desc))
         + 0.25/(60.0 + row_number() over (order by au.score desc nulls last, ci.id desc))
           as fused
    from merged mg
    join digest.content_items ci on ci.id = mg.id
    left join kw k on k.id = mg.id
    left join vec v on v.id = mg.id
    left join ttl tt on tt.id = mg.id
    left join lateral (
      select mp.engagement_score as score
      from digest.members mm2
      join digest.member_profiles mp on mp.at_member_id = mm2.at_member_id
      where mm2.airtable_id = coalesce(ci.meta->>'sender_member', ci.meta->>'member')
      limit 1
    ) au on true
  )
  select fin.source, fin.kind, fin.source_id, fin.title, fin.tl_dr,
         -- #39: leading-addressee marker. Exact char-prefix compare (no LIKE — names could
         -- carry wildcards); the stripped head is re-stated inside the marker so nothing is lost.
         case when fin.source = 'fb_comment' and fin.post_author is not null
                   and length(fin.post_author) >= 3
                   and lower(left(fin.body, length(fin.post_author))) = lower(fin.post_author)
              then '[→ to ' || fin.post_author || '] '
                   || ltrim(substr(fin.body, length(fin.post_author) + 1), ' -–—,:;.!')
              else fin.body end,
         fin.occurred_at,
         case when fin.source = 'fb_comment' and fin.url is not null and fin.url not like '%comment_id=%'
                   and fin.source_id ~ '^[0-9]+$'
              then rtrim(fin.url, '/') || '/?comment_id=' || fin.source_id
              else fin.url end,
         fin.sensitivity::text,
         (case when fin.meta ? 'sender_member'
               then fin.meta || jsonb_strip_nulls(jsonb_build_object('sender_name',
                      (select coalesce(m3.full_name, m3.name) from digest.members m3
                        where m3.airtable_id = fin.meta->>'sender_member' limit 1)))
               else fin.meta end)
         || (case when fin.source = 'fb_comment' and fin.post_author is not null
               then jsonb_build_object('post_author', fin.post_author)
               else '{}'::jsonb end),
         fin.search_extra
  from (
    select ci2.id, ci2.source, ci2.kind, ci2.source_id, ci2.title, ci2.tl_dr, ci2.body,
           ci2.occurred_at, ci2.url, ci2.sensitivity, ci2.meta, ci2.search_extra, sc.fused,
           case when ci2.source = 'fb_comment' and (ci2.meta ? 'post_id') then
             (select pp.meta->>'author_name' from digest.content_items pp
               where pp.source = 'fb_post' and pp.source_id = ci2.meta->>'post_id'
               order by pp.id limit 1)
           else null end as post_author
    from scored sc
    join digest.content_items ci2 on ci2.id = sc.id
  ) fin
  order by fin.fused desc, fin.occurred_at desc, fin.id desc
  limit greatest(coalesce(p_limit, 40), 0);
end $function$
