-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.content_ingest_wa_message()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
begin
  insert into digest.content_items
    (source, kind, source_id, title, tl_dr, body, occurred_at, url,
     access_rule, sensitivity, search_extra, meta)
  values (
    'wa_message',
    coalesce(nullif(new.type, ''), 'message'),
    new.id,
    null,
    null,
    new.text,
    new.sent_at,
    null,
    jsonb_build_object('type', 'chat_member', 'chat', new.chat_name),
    'normal',
    null,
    jsonb_strip_nulls(jsonb_build_object(
      'chat_name', new.chat_name,
      'chat_id', new.chat_id,
      'sender_member', new.sender_member)))
  on conflict (source, source_id) do update set
    kind = excluded.kind,
    body = excluded.body,
    occurred_at = excluded.occurred_at,
    access_rule = excluded.access_rule,
    sensitivity = excluded.sensitivity,
    meta = excluded.meta,
    ingested_at = now();
  return new;
end $function$
