-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.content_lookup(p_phone text, p_source text, p_kind text DEFAULT NULL::text, p_chat text DEFAULT NULL::text, p_since date DEFAULT NULL::date, p_on date DEFAULT NULL::date, p_until date DEFAULT NULL::date, p_order_by text DEFAULT 'occurred_at'::text, p_limit integer DEFAULT 40, p_include_restricted boolean DEFAULT false)
 RETURNS TABLE(source text, kind text, source_id text, title text, tl_dr text, body text, occurred_at timestamp with time zone, url text, sensitivity text, meta jsonb)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare
  v_chats text[]; v_atid text; v_n int; v_in_fb boolean;
begin
  if p_order_by not in ('occurred_at', 'msg_count') then
    raise exception 'content_lookup: invalid p_order_by %', p_order_by;
  end if;
  select case when digest.resolve_asker(p_phone) is not null then 1 else 0 end into v_n;
  if v_n < 1 then return; end if;
  select coalesce((select array_agg(distinct c) from digest.member_identity mu, unnest(coalesce(mu.channels_present, '{}')) c where mu.at_member_id = m.at_member_id and digest.is_active_member_status(mu.membership_status)), '{}'), m.at_member_id into v_chats, v_atid
    from digest.member_identity m where m.at_member_id = digest.resolve_asker(p_phone) and digest.is_active_member_status(m.membership_status);

  v_in_fb := v_atid is not null and exists (select 1 from digest.fb_member_map f where f.at_member_id = v_atid);

  return query
  select ci.source, ci.kind, ci.source_id, ci.title, ci.tl_dr, ci.body,
         ci.occurred_at, ci.url, ci.sensitivity::text,
         case when ci.meta ? 'sender_member'
              then ci.meta || jsonb_strip_nulls(jsonb_build_object(
                     'sender_name', coalesce(mm.full_name, mm.name)))
              else ci.meta end as meta
  from digest.content_items ci
  left join digest.members mm on mm.airtable_id = ci.meta->>'sender_member'
  where ci.sensitivity <> 'never_surface'
    and (p_include_restricted or ci.sensitivity <> 'restricted')
    and (
      (ci.access_rule->>'type' = 'public')
      or (ci.access_rule->>'type' = 'chat_member' and ci.access_rule->>'chat' = any(v_chats))
      or (ci.access_rule->>'type' = 'owner' and v_atid is not null and ci.access_rule->>'member' = v_atid)
      or (ci.access_rule->>'type' = 'fb_group' and v_in_fb)
    )
    and ci.source = p_source
    and (p_kind is null or ci.kind = p_kind)
    and (p_chat is null or ci.meta->>'chat_name' = p_chat)
    and (p_since is null or (ci.occurred_at at time zone 'utc')::date >= p_since)
    and (p_on    is null or (ci.occurred_at at time zone 'utc')::date =  p_on)
    and (p_until is null or (ci.occurred_at at time zone 'utc')::date <= p_until)
  order by
    case when p_order_by = 'msg_count' then (ci.meta->>'msg_count')::numeric end desc nulls last,
    ci.occurred_at desc, ci.id desc
  limit greatest(coalesce(p_limit, 40), 0);
end $function$
