-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.country_region_countries(p text)
 RETURNS text[]
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  select case regexp_replace(nullif(trim(lower(coalesce(p,''))), ''), '^the\s+', '')
    when 'north america' then array['united states','canada','mexico','puerto rico','us virgin islands','dominican republic','panama']
    when 'latin america' then array['mexico','brazil','argentina','ecuador','panama','dominican republic','colombia','chile','peru','uruguay','costa rica','guatemala']
    when 'south america' then array['brazil','argentina','ecuador','colombia','chile','peru','uruguay','bolivia','paraguay','venezuela']
    when 'europe' then array['united kingdom','germany','france','spain','italy','portugal','netherlands','belgium','austria','switzerland','ireland','denmark','norway','sweden','finland','iceland','greece','cyprus','malta','poland','czechia','hungary','romania','bulgaria','slovenia','estonia','latvia','lithuania','ukraine','belarus','moldova','russia','turkey','croatia','serbia','slovakia','luxembourg']
    when 'eastern europe' then array['poland','czechia','hungary','romania','bulgaria','slovenia','estonia','latvia','lithuania','ukraine','belarus','moldova','russia','slovakia','serbia','croatia']
    when 'western europe' then array['united kingdom','germany','france','spain','italy','portugal','netherlands','belgium','austria','switzerland','ireland','luxembourg']
    when 'scandinavia' then array['denmark','norway','sweden','finland','iceland']
    when 'nordics' then array['denmark','norway','sweden','finland','iceland']
    when 'africa' then array['south africa','nigeria','kenya','egypt','morocco','ghana','uganda','tanzania','ethiopia','tunisia','algeria','rwanda','senegal','zambia','zimbabwe','mauritius','mauritania','namibia','botswana','ivory coast','cameroon','angola','mozambique','libya','sudan','niger','mali','malawi','madagascar','seychelles']
    when 'north africa' then array['egypt','morocco','tunisia','algeria','libya','sudan']
    when 'sub-saharan africa' then array['south africa','nigeria','kenya','ghana','uganda','tanzania','ethiopia','rwanda','senegal','zambia','zimbabwe','namibia','botswana','ivory coast','cameroon','angola','mozambique','malawi','madagascar']
    when 'west africa' then array['nigeria','ghana','senegal','ivory coast','mali','niger']
    when 'east africa' then array['kenya','uganda','tanzania','ethiopia','rwanda','mauritius','seychelles','madagascar']
    when 'southern africa' then array['south africa','zimbabwe','zambia','namibia','botswana','mozambique','angola','malawi']
    when 'emea' then array['united kingdom','germany','france','spain','italy','portugal','netherlands','belgium','austria','switzerland','ireland','denmark','norway','sweden','finland','iceland','greece','cyprus','malta','poland','czechia','hungary','romania','bulgaria','slovenia','estonia','ukraine','russia','turkey','israel','united arab emirates','saudi arabia','qatar','south africa','nigeria','kenya','egypt','morocco','ghana','zimbabwe','mauritius']
    when 'asia' then array['singapore','thailand','japan','china','hong kong','taiwan','india','indonesia','philippines','vietnam','malaysia','south korea','pakistan','bangladesh','sri lanka','cambodia']
    when 'southeast asia' then array['singapore','thailand','indonesia','philippines','vietnam','malaysia','cambodia']
    when 'middle east' then array['israel','united arab emirates','saudi arabia','qatar','kuwait','bahrain','oman','jordan','lebanon','turkey']
    when 'gulf' then array['united arab emirates','saudi arabia','qatar','kuwait','bahrain','oman']
    when 'oceania' then array['australia','new zealand']
    when 'australia and new zealand' then array['australia','new zealand']
    when 'anz' then array['australia','new zealand']
    else null end
$function$
