-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.country_fold(p text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  select case c
    when 'us' then 'united states' when 'usa' then 'united states'
    when 'united states of america' then 'united states'
    when 'ca' then 'canada' when 'gb' then 'united kingdom' when 'uk' then 'united kingdom'
    when 'sg' then 'singapore' when 'au' then 'australia' when 'fr' then 'france'
    when 'es' then 'spain' when 'de' then 'germany' when 'is' then 'iceland'
    when 'cy' then 'cyprus' when 'mx' then 'mexico' when 'th' then 'thailand'
    when 'ee' then 'estonia' when 'pr' then 'puerto rico' when 'se' then 'sweden'
    when 'pa' then 'panama' when 'jp' then 'japan' when 'br' then 'brazil'
    when 'hk' then 'hong kong' when 'ch' then 'switzerland' when 'il' then 'israel'
    when 'it' then 'italy' when 'gr' then 'greece' when 'pl' then 'poland'
    when 'ar' then 'argentina' when 'ro' then 'romania' when 'hu' then 'hungary'
    when 'si' then 'slovenia' when 'ph' then 'philippines' when 'fi' then 'finland'
    when 'id' then 'indonesia' when 'ru' then 'russia'
    when 'do' then 'dominican republic' when 'pt' then 'portugal'
    when 'in' then 'india' when 'bg' then 'bulgaria' when 'cn' then 'china'
    when 'tr' then 'turkey' when 'cz' then 'czechia' when 'czech republic' then 'czechia'
    when 'vi' then 'us virgin islands' when 'nl' then 'netherlands' when 'nz' then 'new zealand'
    when 'ae' then 'united arab emirates' when 'vn' then 'vietnam' when 'my' then 'malaysia'
    when 'kr' then 'south korea' when 'tw' then 'taiwan' when 'ua' then 'ukraine'
    when 'ie' then 'ireland' when 'be' then 'belgium' when 'at' then 'austria'
    when 'dk' then 'denmark' when 'no' then 'norway' when 'lv' then 'latvia'
    when 'lt' then 'lithuania' when 'sk' then 'slovakia' when 'hr' then 'croatia'
    when 'rs' then 'serbia' when 'lu' then 'luxembourg' when 'mt' then 'malta'
    when 'md' then 'moldova' when 'by' then 'belarus' when 'sa' then 'saudi arabia'
    when 'qa' then 'qatar' when 'kw' then 'kuwait' when 'co' then 'colombia'
    when 'cl' then 'chile' when 'pe' then 'peru' when 'uy' then 'uruguay'
    -- African ISO codes (added 2026-08-04 — ZW was the live miss)
    when 'za' then 'south africa' when 'ng' then 'nigeria' when 'ke' then 'kenya'
    when 'eg' then 'egypt' when 'ma' then 'morocco' when 'gh' then 'ghana'
    when 'ug' then 'uganda' when 'tz' then 'tanzania' when 'et' then 'ethiopia'
    when 'tn' then 'tunisia' when 'dz' then 'algeria' when 'rw' then 'rwanda'
    when 'sn' then 'senegal' when 'zm' then 'zambia' when 'zw' then 'zimbabwe'
    when 'mu' then 'mauritius' when 'mr' then 'mauritania' when 'bw' then 'botswana'
    when 'ci' then 'ivory coast' when 'cm' then 'cameroon' when 'ao' then 'angola'
    when 'mz' then 'mozambique' when 'ly' then 'libya' when 'sd' then 'sudan'
    when 'ml' then 'mali' when 'mw' then 'malawi' when 'mg' then 'madagascar'
    when 'sc' then 'seychelles'
    -- DATA FIX, not ISO: the single 'NE' row is a Haarlem member (Netherlands).
    when 'ne' then 'netherlands'
    else c end
  from (select nullif(trim(lower(coalesce(p,''))), '') c) s
$function$
