-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.derive_knowledge_graph()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare v_rows int;
begin
  delete from digest.member_edges where true;

  -- co-attended (keyed regs, sane-size events)
  insert into digest.member_edges (a_id, b_id, edge_type, weight, evidence, refreshed_at)
  with ev as (
    select er.event_at_id, array_agg(distinct er.member_at_id) as mems,
           count(distinct er.member_at_id) as n
    from digest.event_registrations_live er
    where er.member_at_id is not null
    group by er.event_at_id
    having count(distinct er.member_at_id) between 2 and 150
  ),
  pairs as (
    select least(a.m, b.m) as a_id, greatest(a.m, b.m) as b_id,
           1.0/ln(1 + e.n) as w
    from ev e, unnest(e.mems) a(m), unnest(e.mems) b(m)
    where a.m < b.m
  )
  select p.a_id, p.b_id, 'co_attended', round(sum(p.w)::numeric, 4),
         jsonb_build_object('shared_events', count(*)), now()
  from pairs p group by p.a_id, p.b_id;

  -- same chat (active members, sane-size chats)
  insert into digest.member_edges (a_id, b_id, edge_type, weight, evidence, refreshed_at)
  with mem_chats as (
    select m.at_member_id, c.chat
    from digest.members m, unnest(coalesce(m.channels_present, '{}'::text[])) c(chat)
    where m.at_member_id is not null and digest.is_active_member_status(m.membership_status)
  ),
  sizes as (select chat, count(*) as n from mem_chats group by chat
            having count(*) between 2 and 150),
  pairs as (
    select least(x.at_member_id, y.at_member_id) as a_id,
           greatest(x.at_member_id, y.at_member_id) as b_id,
           1.0/ln(1 + s.n) as w
    from mem_chats x
    join mem_chats y on y.chat = x.chat and x.at_member_id < y.at_member_id
    join sizes s on s.chat = x.chat
  )
  select p.a_id, p.b_id, 'same_chat', round(sum(p.w)::numeric, 4),
         jsonb_build_object('shared_chats', count(*)), now()
  from pairs p group by p.a_id, p.b_id;

  -- same chapter
  insert into digest.member_edges (a_id, b_id, edge_type, weight, evidence, refreshed_at)
  with mem_ch as (
    select ma.at_member_id, ch.c as chapter
    from digest.member_attributes ma, unnest(coalesce(ma.chapter_ids, '{}'::text[])) ch(c)
    where digest.is_active_member_status(ma.membership_status)
  ),
  sizes as (select chapter, count(*) as n from mem_ch group by chapter
            having count(*) between 2 and 150),
  pairs as (
    select least(x.at_member_id, y.at_member_id) as a_id,
           greatest(x.at_member_id, y.at_member_id) as b_id,
           1.0/ln(1 + s.n) as w
    from mem_ch x
    join mem_ch y on y.chapter = x.chapter and x.at_member_id < y.at_member_id
    join sizes s on s.chapter = x.chapter
  )
  select p.a_id, p.b_id, 'same_chapter', round(sum(p.w)::numeric, 4),
         jsonb_build_object('shared_chapters', count(*)), now()
  from pairs p group by p.a_id, p.b_id;

  -- talked-in-thread (fb commenter ↔ post author, both keyed via sender_member)
  insert into digest.member_edges (a_id, b_id, edge_type, weight, evidence, refreshed_at)
  with inter as (
    select mc.at_member_id as commenter, mp.at_member_id as author
    from digest.content_items c
    join digest.content_items p
      on p.source = 'fb_post' and p.source_id = c.meta->>'post_id'
    join digest.members mc on mc.airtable_id = c.meta->>'sender_member'
    join digest.members mp on mp.airtable_id = p.meta->>'sender_member'
    where c.source = 'fb_comment'
      and mc.at_member_id is not null and mp.at_member_id is not null
      and mc.at_member_id <> mp.at_member_id
  )
  select least(i.commenter, i.author), greatest(i.commenter, i.author),
         'thread_interaction', count(*), jsonb_build_object('interactions', count(*)), now()
  from inter i group by 1, 2;

  select count(*) into v_rows from digest.member_edges;
  return jsonb_build_object('edges', v_rows);
end $function$
