-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.derive_member_expertise()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare v_rows int; v_members int;
begin
  delete from digest.member_expertise where true;

  insert into digest.member_expertise
    (at_member_id, topic, score, weakness_score, evidence, refreshed_at, rank_in_topic, pct)
  with actives as (
    select ma.at_member_id, ma.rev_band, ma.main_niche, ma.business_model,
           ma.categories, ma.channel_mix
    from digest.member_attributes ma
    where digest.is_active_member_status(ma.membership_status)
  ),
  term_q as (
    select t.topic, x.term, phraseto_tsquery('english', x.term) as q
    from digest.expertise_topics t, unnest(t.terms) as x(term)
    where numnode(phraseto_tsquery('english', x.term)) > 0
  ),
  content_hits as (
    select m.at_member_id, tq.topic, ci.id,
           bool_or(ci.source in ('fb_post') or ci.kind = 'post') as is_post
    from digest.content_items ci
    join digest.members m on m.airtable_id = coalesce(ci.meta->>'sender_member', ci.meta->>'member')
    join term_q tq on ci.search_tsv @@ tq.q
    where m.at_member_id is not null
    group by m.at_member_id, tq.topic, ci.id
  ),
  content_agg as (
    select ch.at_member_id, ch.topic,
           count(*) filter (where ch.is_post) as posts,
           count(*) filter (where not ch.is_post) as comments
    from content_hits ch group by 1, 2
  ),
  spk_emails as (
    select em, min(at_member_id) as aid, count(distinct at_member_id) as n
    from (
      select lower(at_fields->>'Email') as em, at_member_id from digest.member_profiles
        where coalesce(at_fields->>'Email','') <> ''
      union all
      select lower(at_fields->>'Preferred Email'), at_member_id from digest.member_profiles
        where coalesce(at_fields->>'Preferred Email','') <> ''
    ) x group by em
  ),
  spk as (
    select distinct vs.user_id, e.aid as at_member_id
    from digest.video_speakers vs
    join spk_emails e on coalesce(vs.email,'') <> '' and e.em = lower(vs.email) and e.n = 1
  ),
  video_agg as (
    select s.at_member_id, tq.topic, count(distinct v.video_id) as vids
    from digest.videos_catalog v
    join term_q tq on v.search_tsv @@ tq.q
    join spk s on v.speaker_ids @> array[s.user_id]
    where v.deleted_at is null
    group by 1, 2
  ),
  biz as (
    select a.at_member_id, t.topic
    from actives a
    join digest.expertise_topics t on exists (
      select 1 from unnest(t.terms) term
      where a.main_niche ilike '%'||term||'%'
         or exists (select 1 from unnest(coalesce(a.business_model, '{}'::text[])) bm where bm ilike '%'||term||'%')
         or exists (select 1 from unnest(coalesce(a.categories, '{}'::text[])) c where c ilike '%'||term||'%')
         or exists (select 1 from unnest(coalesce(a.channel_mix, '{}'::text[])) ch where ch ilike '%'||term||'%'))
  ),
  persona_agg as (
    select p.at_member_id, t.topic,
      (select count(*) from unnest(t.terms) term
        where coalesce(p.persona->>'gives','') ilike '%'||term||'%'
           or coalesce(p.persona->>'focus','') ilike '%'||term||'%'
           or coalesce(p.persona->>'business','') ilike '%'||term||'%') as gives,
      (select count(*) from unnest(t.terms) term
        where coalesce(p.persona->>'asks','') ilike '%'||term||'%'
           or coalesce(p.persona->>'challenges_now','') ilike '%'||term||'%') as asks
    from digest.member_personas p
    cross join digest.expertise_topics t
  ),
  scored as (
    select a.at_member_id, t.topic,
      round((( 2.0 * ln(1 + coalesce(c.posts, 0))
             + 0.7 * ln(1 + coalesce(c.comments, 0))
             + 3.0 * least(coalesce(v.vids, 0), 5)
             + 1.5 * (case when b.at_member_id is not null then 1 else 0 end)
             + 1.0 * ln(1 + coalesce(p.gives, 0)))
        * case a.rev_band when '20M+' then 1.5 when '10-20M' then 1.3
                          when '5-10M' then 1.15 else 1.0 end)::numeric, 3) as score,
      round(ln(1 + coalesce(p.asks, 0))::numeric, 3) as weakness,
      jsonb_strip_nulls(jsonb_build_object(
        'posts', nullif(coalesce(c.posts, 0), 0),
        'comments', nullif(coalesce(c.comments, 0), 0),
        'videos_spoken', nullif(coalesce(v.vids, 0), 0),
        'biz_affinity', case when b.at_member_id is not null then true end,
        'persona_gives_hits', nullif(coalesce(p.gives, 0), 0),
        'persona_asks_hits', nullif(coalesce(p.asks, 0), 0),
        'band_multiplier', case a.rev_band when '20M+' then 1.5 when '10-20M' then 1.3
                                           when '5-10M' then 1.15 else 1.0 end)) as evidence
    from actives a
    cross join digest.expertise_topics t
    left join content_agg c on c.at_member_id = a.at_member_id and c.topic = t.topic
    left join video_agg v on v.at_member_id = a.at_member_id and v.topic = t.topic
    left join biz b on b.at_member_id = a.at_member_id and b.topic = t.topic
    left join persona_agg p on p.at_member_id = a.at_member_id and p.topic = t.topic
  )
  select s.at_member_id, s.topic, s.score, s.weakness, s.evidence, now(),
         case when s.score > 0 then rank() over (partition by s.topic order by s.score desc) end,
         case when s.score > 0 then round((1 - percent_rank() over (partition by s.topic order by s.score desc))::numeric, 4) end
  from scored s
  where s.score > 0 or s.weakness > 0;

  get diagnostics v_rows = row_count;
  select count(distinct at_member_id) into v_members from digest.member_expertise;
  return jsonb_build_object('rows', v_rows, 'members', v_members);
end $function$
