-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.derive_expertise_truth()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
 SET statement_timeout TO '120s'
AS $function$
declare v_community int; v_speaker int; v_topics int; v_members int;
begin
  -- Scoped delete: this function owns ONLY the community_mention + speaker rows. Task 2's
  -- 'web' source (added later, by a different loader) is never touched by this rebuild.
  delete from digest.expertise_truth where source in ('community_mention', 'speaker');

  -- ============ SOURCE 1: community mentions ============
  -- Half A: every fb_comment whose text full-name-matches an eligible active member, via the
  -- GIN index on content_items.search_tsv (verified standalone: ~4,954 rows, sub-second).
  drop table if exists _et_name_hits;
  create temp table _et_name_hits on commit drop as
  with active_members as (
    -- member resolution per Addendum C, adapted: FB content's sender_member/member key
    -- resolves via member_attributes.at_member_id (verified: 18,840/18,840 FB content_items
    -- with a key resolve this way; 0/18,840 resolve via digest.members.airtable_id -- see
    -- "Member join path" in task-1-report.md self-review for the full verification).
    --
    -- A single-token name ("Kyle", "Rana", or a data-entry artifact like "Cou") is not
    -- specific enough to credit reliably -- excluded here, not just for authors but as
    -- CANDIDATES to be named (see task-1-report.md).
    select at_member_id, full_name
    from digest.member_attributes
    where digest.is_active_member_status(membership_status)
      and full_name is not null
      and array_length(regexp_split_to_array(trim(full_name), '\s+'), 1) >= 2
      and numnode(phraseto_tsquery('english', full_name)) > 0
  )
  select c.id as comment_ci_id, c.url, c.occurred_at, c.body,
         coalesce(c.meta->>'sender_member', c.meta->>'member') as author_akey,
         c.meta->>'author_name' as author_name,
         c.meta->>'post_id' as post_id,
         am.at_member_id, am.full_name
  from digest.content_items c
  join active_members am on c.search_tsv @@ phraseto_tsquery('english', am.full_name)
  where c.source = 'fb_comment'
    -- this is a table of HUMAN judgment -- Olivia/Millie's own bot replies, relayed by a
    -- member into the thread, are not that (would be circular evidence for Task 3)
    and c.body !~* 'response from (mds.?.?\s*|our new\s*)?(olivia|millie)';
  analyze _et_name_hits;

  -- Half B: every "ask" post and the topic(s) its own text matches (the parent question, not
  -- the reply). Independent of who replies to it.
  drop table if exists _et_ask_topics;
  create temp table _et_ask_topics on commit drop as
  with term_q as materialized (
    select t.topic, x.term, phraseto_tsquery('english', x.term) as q
    from digest.expertise_topics t, unnest(t.terms) as x(term)
    where numnode(phraseto_tsquery('english', x.term)) > 0
  )
  select distinct p.source_id as post_id, p.body as post_body, tq.topic
  from digest.content_items p
  join digest.fb_posts fp on fp.post_id = p.source_id
  join term_q tq on p.search_tsv @@ tq.q
  where p.source = 'fb_post' and fp.post_type = 'ask';
  analyze _et_ask_topics;

  -- Join the two (now correctly-sized) halves, apply Addendum F (self-description) and the
  -- reply-to-address exclusion, then collapse to one row per thread (see url note below).
  insert into digest.expertise_truth (topic, at_member_id, source, weight, url, occurred_at, evidence,
                                       evidence_event_id, evidence_event_topic_count)
  with matched as (
    select at2.topic, nh.at_member_id, nh.url, nh.occurred_at, nh.comment_ci_id,
           nh.post_id, at2.post_body, nh.body, nh.full_name, nh.author_name
    from _et_name_hits nh
    join _et_ask_topics at2 on at2.post_id = nh.post_id
    join digest.member_attributes author_ma on author_ma.at_member_id = nh.author_akey
    where nh.at_member_id <> author_ma.at_member_id  -- Addendum F: someone ELSE must do the naming
      -- Exclude the FB reply-to-a-comment address convention ("<Name>, ..." / "Hey <Name> ...").
      -- A reply OPENING with a name is addressing them, not recommending them -- the same
      -- artifact digest.fb_thread() already special-cases for the post author (#39). Measured:
      -- 4,772 of 5,475 raw full-name hits on ask-threads were exactly this pattern.
      -- Punctuation-normalized so "B.J Kokenos" vs "B.J. Kokenos" still counts as the same opener.
      and position(
            regexp_replace(lower(nh.full_name), '[^a-z0-9 ]', '', 'g')
            in
            regexp_replace(lower(substring(ltrim(nh.body) from 1 for 60)), '[^a-z0-9 ]', '', 'g')
          ) = 0
  ),
  dedup as (
    -- content_items.url is one-per-THREAD for fb_comment rows (every comment on a post shares
    -- the post's url), so two mentions of the same person in the same thread would otherwise
    -- collide on the primary key. Keep the earliest as the representative row.
    select distinct on (topic, at_member_id, url) *
    from matched
    order by topic, at_member_id, url, occurred_at asc, comment_ci_id asc
  )
  select topic, at_member_id, 'community_mention', 1,
         coalesce(url, ''), occurred_at::date,
         jsonb_build_object(
           'kind', 'community_mention',
           'post_id', post_id,
           'post_snippet', left(post_body, 300),
           'comment_snippet', left(body, 300),
           'named_as', full_name,
           'commenter', author_name),
         -- Finding 2: stable event id = this (thread, member) pair, plus how many topic rows
         -- that same pair produced (post-dedup, i.e. the rows actually being inserted).
         'community_mention:' || post_id || ':' || at_member_id,
         count(*) over (partition by post_id, at_member_id)
  from dedup;

  -- ============ SOURCE 2: speaker picks ============
  -- MDS put this person on stage for this subject: videos_catalog.speaker_ids resolved to a
  -- member via the member_profiles Email/Preferred Email union (Addendum E), crossed with the
  -- video's own SUBJECT match (title + category_names + tag_names -- Finding 1; see video_subject
  -- below). Verified before building on it: 202 speaker-member pairs, 421 video-member pairs
  -- (task-1-report.md).
  insert into digest.expertise_truth (topic, at_member_id, source, weight, url, occurred_at, evidence,
                                       evidence_event_id, evidence_event_topic_count)
  with term_q as materialized (
    select t.topic, x.term, phraseto_tsquery('english', x.term) as q
    from digest.expertise_topics t, unnest(t.terms) as x(term)
    where numnode(phraseto_tsquery('english', x.term)) > 0
  ),
  spk_emails as (
    select em, min(at_member_id) as aid, count(distinct at_member_id) as n
    from (
      select lower(at_fields->>'Email') as em, at_member_id from digest.member_profiles
        where coalesce(at_fields->>'Email', '') <> ''
      union all
      select lower(at_fields->>'Preferred Email'), at_member_id from digest.member_profiles
        where coalesce(at_fields->>'Preferred Email', '') <> ''
    ) x group by em
  ),
  spk as (
    select distinct vs.user_id, vs.display_name, e.aid as at_member_id
    from digest.video_speakers vs
    join spk_emails e on coalesce(vs.email, '') <> '' and e.em = lower(vs.email) and e.n = 1
  ),
  active_members as (
    select at_member_id from digest.member_attributes where digest.is_active_member_status(membership_status)
  ),
  video_subject as (
    -- Finding 1: the video's own SUBJECT only -- title, category_names, tag_names. NEVER
    -- search_tsv (also spans speaker_names, call_type, cliff_notes, summary, files_text,
    -- description_text) -- that generated column is why the prior build credited a single
    -- talk's speaker with 25 topics off its summary and attached-file text. Computed once per
    -- video (not once per video-term pair) so the join below stays cheap.
    select v.video_id, v.title, v.speaker_ids, v.app_created_at,
           to_tsvector('english',
             coalesce(v.title, '') || ' ' ||
             digest.immutable_text_array_join(v.category_names) || ' ' ||
             digest.immutable_text_array_join(v.tag_names)
           ) as subject_tsv
    from digest.videos_catalog v
    where v.deleted_at is null
  ),
  video_topic as (
    -- grouped (not a bare distinct) so a member reachable via two speaker rows on the same
    -- video can never produce two rows sharing one primary key
    select vs.video_id, min(vs.title) as title, tq.topic, s.at_member_id,
           min(s.display_name) as speaker_display_name, min(vs.app_created_at) as app_created_at
    from video_subject vs
    join term_q tq on vs.subject_tsv @@ tq.q
    join spk s on vs.speaker_ids @> array[s.user_id]
    group by vs.video_id, tq.topic, s.at_member_id
  )
  select vt.topic, vt.at_member_id, 'speaker', 1,
         coalesce(digest.member_video_url(vt.video_id), ''),
         vt.app_created_at::date,
         jsonb_build_object('kind', 'speaker', 'video_id', vt.video_id,
                             'video_title', vt.title, 'speaker_display_name', vt.speaker_display_name),
         -- Finding 2: stable event id = this (video, member) pair, plus how many topic rows
         -- that same pair produced.
         'speaker:' || vt.video_id || ':' || vt.at_member_id,
         count(*) over (partition by vt.video_id, vt.at_member_id)
  from video_topic vt
  join active_members am on am.at_member_id = vt.at_member_id;

  select count(*) into v_community from digest.expertise_truth where source = 'community_mention';
  select count(*) into v_speaker   from digest.expertise_truth where source = 'speaker';
  select count(distinct topic) into v_topics from digest.expertise_truth;
  select count(distinct at_member_id) into v_members from digest.expertise_truth;
  return jsonb_build_object('community_mention_rows', v_community, 'speaker_rows', v_speaker,
                            'total_rows', v_community + v_speaker,
                            'distinct_topics', v_topics, 'distinct_members', v_members);
end $function$
