-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.en_rank(at_fields jsonb, q tsquery)
 RETURNS real
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'digest', 'public', 'extensions'
AS $function$
  select ts_rank(
    to_tsvector('english',
      coalesce(digest.attr_clean(at_fields->>'Area of Expertise'), '') || ' ' ||
      coalesce(digest.attr_clean(at_fields->>'Main Niche'), '')), q)
$function$
