-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.event_lookup_v2(p_phone text, p_terms text[] DEFAULT NULL::text[], p_city text DEFAULT NULL::text, p_virtual boolean DEFAULT NULL::boolean, p_include_past boolean DEFAULT false, p_limit integer DEFAULT 12, p_embedding text DEFAULT NULL::text, p_at_member_id text DEFAULT NULL::text)
 RETURNS TABLE(event_name text, starts_at timestamp with time zone, start_display text, event_type text, phase text, city text, guests_policy text, chapter text, audience_hint text, is_registered boolean, can_register boolean, reg_link text, guest_reg_link text, spots_left integer, registered_count bigint, event_url text)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare
  v_atid text; v_browse boolean;
begin
  v_browse := p_terms is null and p_city is null and not p_include_past;
  select m.at_member_id into v_atid from digest.members m
   where (case when p_at_member_id is not null then m.at_member_id = p_at_member_id
               else m.phone = p_phone end)
     and digest.is_active_member_status(m.membership_status)
   order by (m.phone is not null) desc, m.airtable_id limit 1;
  if v_atid is null then v_atid := p_at_member_id; end if;

  return query
  with v1 as (
    select t.* from digest.event_lookup(p_phone, p_terms, p_city, p_virtual,
                            p_include_past, p_limit, p_embedding, p_at_member_id)
         with ordinality as t(event_name, starts_at, start_display, event_type, phase, city,
                              guests_policy, chapter, audience_hint, is_registered, can_register,
                              reg_link, guest_reg_link, spots_left, registered_count, event_url, ord)
  ), topics as (
    select * from digest.member_topic_profile(v_atid)
  ), circle as (
    select g.b_id from digest.member_edges g
    where g.a_id = v_atid order by g.weight desc limit 12
  ), scored as (
    select v.*,
      case when not v_browse then 0 else coalesce((
        select sum(tp.sort_score) from topics tp
        where exists (select 1 from unnest(tp.words) w
                      where v.event_name ~* ('\m'||w||'\M')
                         or v.audience_hint ~* ('\m'||w||'\M')
                         or v.chapter ~* ('\m'||w||'\M'))), 0) end as aff,
      case when not v_browse then 0 else coalesce((
        select count(*) from digest.events_catalog c
        join digest.event_registrations_live r on r.event_at_id = c.at_record_id
        where coalesce(c.app_title, c.name) = v.event_name
          and coalesce(c.app_starts_at, c.start_at) = v.starts_at
          and r.member_at_id in (select b_id from circle)), 0) end as circ
    from v1 v
  )
  select s.event_name, s.starts_at, s.start_display, s.event_type, s.phase, s.city,
         s.guests_policy, s.chapter, s.audience_hint, s.is_registered, s.can_register,
         s.reg_link, s.guest_reg_link, s.spots_left, s.registered_count, s.event_url
  from scored s
  order by case when v_browse then s.is_registered else false end asc,
           case when v_browse then s.aff else 0 end desc,
           case when v_browse then s.circ else 0 end desc,
           s.ord;
end $function$
