-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.event_who(p_phone text, p_event text, p_limit integer DEFAULT 10)
 RETURNS TABLE(event_name text, starts_at timestamp with time zone, full_name text, state text, is_me boolean, total_going integer, city text, niche text, channels text[], fit_reason text, shared_topics text[])
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare
  v_n int; v_atid text; v_is_20m boolean := false;
  v_event_id text; v_event_name text; v_banded boolean;
  v_me_city text; v_me_niche text; v_total int; v_asker_registered boolean := false;
begin
  if nullif(trim(coalesce(p_event,'')),'') is null then return; end if;
  select case when digest.resolve_asker(p_phone) is not null then 1 else 0 end into v_n;
  if v_n < 1 then return; end if;
  select digest.resolve_asker(p_phone) into v_atid;
  if v_atid is not null then
    select coalesce(ma.rev_band = '20M+', false), ma.city, ma.main_niche into v_is_20m, v_me_city, v_me_niche
      from digest.member_attributes ma where ma.at_member_id = v_atid;
    v_is_20m := coalesce(v_is_20m, false);
  end if;

  select c.at_record_id, coalesce(c.app_title, c.name),
         (c.name ~* '([0-9]{2,3}M[+]|centurion)')
    into v_event_id, v_event_name, v_banded
  from digest.events_catalog c
  where coalesce(c.phase,'') not in ('Tentative','Awaiting Feedback')
    and (select bool_and(c.name ilike '%'||w||'%'
                          or coalesce(c.app_title,'') ilike '%'||w||'%')
           from regexp_split_to_table(trim(p_event), '[[:space:]]+') w)
  order by
           -- 2026-08-24 (launch, Belen): a RUNNING event outranks everything — during the Summit,
           -- "Singapore summit" must resolve to the Summit itself, never a future side event.
           (coalesce(c.app_starts_at, c.start_at) <= now()
             and now() <= coalesce(c.end_at, coalesce(c.app_starts_at, c.start_at) + interval '3 days')) desc,
           (coalesce(c.app_starts_at, c.start_at) >= now()) desc,
           case c.phase when 'Registration Open' then 0 when 'Confirmed' then 1 else 2 end,
           length(c.name) asc,
           coalesce(c.app_starts_at, c.start_at) asc
  limit 1;
  if v_event_id is null then return; end if;
  if v_banded and not v_is_20m then return; end if;

  select (count(distinct r.member_at_id) filter (where r.member_at_id is not null)
          + count(*) filter (where r.member_at_id is null))::int
    into v_total
  from digest.event_registrations_live r
  where r.event_at_id = v_event_id
    and r.ticket_status = 'Confirmed'
    and r.ticket_for && array['MDS Member','MDS Member''s Business Guest','MDS Team'];

  -- #96: is the ASKER registered for this event? (any live ticket status counts as
  -- "their event" — a member with a pending ticket is planning around it)
  select exists (
    select 1 from digest.event_registrations_live r
    where r.event_at_id = v_event_id and r.member_at_id = v_atid)
    into v_asker_registered;

  if not v_asker_registered then
    -- non-attendee: the aggregate row only — true count, no names
    return query
    select v_event_name,
           (select coalesce(c2.app_starts_at, c2.start_at) from digest.events_catalog c2
             where c2.at_record_id = v_event_id),
           null::text, null::text, false, v_total,
           null::text, null::text, null::text[], null::text, null::text[];
    return;
  end if;

  return query
  with me as (
    select t.topic, t.sort_score, t.is_strength, t.is_working_on
      from digest.member_topic_profile(v_atid) t
  ), conf as (
    select distinct r.member_at_id
    from digest.event_registrations_live r
    where r.event_at_id = v_event_id
      and r.member_at_id is not null
      and r.ticket_status = 'Confirmed'
      and r.ticket_for && array['MDS Member','MDS Member''s Business Guest','MDS Team']
  ), ov as (
    select c.member_at_id as mid,
           max(o.w) as best_w,
           (array_agg(o.topic order by o.w desc))[1:2] as top_topics,
           (array_agg(o.kind  order by o.w desc))[1]   as top_kind
    from conf c
    cross join lateral (
      select t.topic,
             (m.sort_score + t.sort_score)
               * case when m.is_working_on or t.is_working_on then 1.5 else 1.0 end as w,
             case when m.is_working_on and t.is_strength then 'can help you with'
                  when m.is_strength   and t.is_strength then 'you both know'
                  else 'shares your interest in' end as kind
      from digest.member_topic_profile(c.member_at_id) t
      join me m on m.topic = t.topic
    ) o
    group by 1
  ), ranked as (
    select ov.*, percent_rank() over (order by ov.best_w) as pr from ov
  )
  select v_event_name,
         (select coalesce(c2.app_starts_at, c2.start_at) from digest.events_catalog c2
           where c2.at_record_id = v_event_id),
         coalesce(ma.full_name, mp.full_name),
         ma.state,
         (conf.member_at_id = v_atid),
         v_total,
         ma.city,
         coalesce(ma.main_niche, ma.categories[1]),
         (select array_agg(ch) from unnest(coalesce(ma.channel_mix, '{}'::text[])) ch),
         case when rk.pr >= 0.75 and rk.top_kind is not null
              then rk.top_kind || ' ' || array_to_string(rk.top_topics, ' and ') end,
         rk.top_topics
  from conf
  left join digest.member_attributes ma on ma.at_member_id = conf.member_at_id
  left join digest.member_profiles mp on mp.at_member_id = conf.member_at_id
  left join ranked rk on rk.mid = conf.member_at_id
  where coalesce(ma.full_name, mp.full_name) is not null
    -- #106 (Andy 2026-08-22 "make sure I'm not searchable"; Eugene 2026-08-24 "need to filter out
    -- the team"): internal records (Staff / Team User) never appear in an attendee NAME list.
    -- The asker still sees their OWN row, so a Staff asker keeps the is_me "you're on the books"
    -- answer. v_total above is deliberately untouched — it stays the registration census, which
    -- counts MDS Team tickets (#96/#98 ruling: counts are the census, names are gated).
    and (conf.member_at_id = v_atid
         or not digest.is_internal_record(ma.membership_status))
  order by (conf.member_at_id = v_atid) desc,
           coalesce(rk.best_w, 0) desc,
           (lower(coalesce(ma.main_niche,'')) = lower(coalesce(v_me_niche,''))) desc,
           (lower(coalesce(ma.city,'')) = lower(coalesce(v_me_city,''))) desc,
           coalesce(ma.full_name, mp.full_name)
  -- Eugene's cap (#96): never more than 10 names in one answer — display cap only
  limit least(greatest(coalesce(p_limit, 10), 1), 10);
end $function$
