-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.event_history_v2(p_phone text)
 RETURNS TABLE(kind text, label text, detail text)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare v_atid text;
begin
  return query select * from digest.event_history(p_phone);

  select m.at_member_id into v_atid from digest.members m
   where m.phone = p_phone and digest.is_active_member_status(m.membership_status);
  if v_atid is null then return; end if;

  return query
  select 'interest'::text, tp.topic,
         case when tp.is_strength then 'their space' else 'building up' end
  from digest.member_topic_profile(v_atid) tp
  order by tp.is_strength desc, tp.sort_score desc limit 6;
end $function$
