-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.events_embed_invalidate()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  if (new.name, new.app_title, new.event_type, new.style, new.chapter_area, new.chapter_hint,
      new.location, new.city_state, new.app_city, new.start_at, new.app_starts_at)
     is distinct from
     (old.name, old.app_title, old.event_type, old.style, old.chapter_area, old.chapter_hint,
      old.location, old.city_state, old.app_city, old.start_at, old.app_starts_at) then
    new.embedding := null;
  end if;
  return new;
end $function$
