-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.event_lookup_v3(p_phone text, p_terms text[] DEFAULT NULL::text[], p_city text DEFAULT NULL::text, p_virtual boolean DEFAULT NULL::boolean, p_include_past boolean DEFAULT false, p_limit integer DEFAULT 12, p_embedding text DEFAULT NULL::text, p_at_member_id text DEFAULT NULL::text)
 RETURNS TABLE(event_name text, starts_at timestamp with time zone, start_display text, event_type text, phase text, city text, guests_policy text, chapter text, audience_hint text, is_registered boolean, can_register boolean, reg_link text, guest_reg_link text, spots_left integer, registered_count bigint, event_url text, fit_reason text, strength_note text)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare v_atid text;
begin
  select m.at_member_id into v_atid from digest.members m
   where (case when p_at_member_id is not null then m.at_member_id = p_at_member_id
               else m.phone = p_phone end)
     and digest.is_active_member_status(m.membership_status)
   order by (m.phone is not null) desc, m.airtable_id limit 1;
  if v_atid is null then v_atid := p_at_member_id; end if;

  return query
  with v2 as (
    select t.* from digest.event_lookup_v2(p_phone, p_terms, p_city, p_virtual,
                          p_include_past, p_limit, p_embedding, p_at_member_id)
      with ordinality as t(event_name, starts_at, start_display, event_type, phase, city,
                           guests_policy, chapter, audience_hint, is_registered, can_register,
                           reg_link, guest_reg_link, spots_left, registered_count, event_url, ord)
  ), me as (
    select tp.topic, tp.is_working_on from digest.member_topic_profile(v_atid) tp
  ), dos as (
    -- #59: ONE dossier per row, keyed on the event record; joined back by ord, never by name.
    select v.ord, ed.strength_note snote, f.topics
    from v2 v
    left join lateral (
      select d.*
      from digest.entity_dossier d
      join digest.events_catalog c on c.at_record_id = d.entity_id
      where d.kind = 'event'
        and coalesce(c.app_title, c.name) = v.event_name
        and coalesce(c.app_starts_at, c.start_at) is not distinct from v.starts_at
      order by d.refreshed_at desc nulls last
      limit 1
    ) ed on true
    left join lateral (
      select array_agg(m.topic order by m.is_working_on desc,
                       (ed.topic_profile->>m.topic)::numeric desc) topics
      from me m
      where ed.topic_profile ? m.topic and (ed.topic_profile->>m.topic)::numeric >= 0.3
    ) f on true
  )
  select v.event_name, v.starts_at, v.start_display, v.event_type, v.phase, v.city,
         v.guests_policy, v.chapter, v.audience_hint, v.is_registered, v.can_register,
         v.reg_link, v.guest_reg_link, v.spots_left, v.registered_count, v.event_url,
         case when d.topics is not null and array_length(d.topics,1) > 0
              then 'the room skews toward what you work on: ' || array_to_string(d.topics[1:2], ', ') end,
         d.snote
  from v2 v left join dos d on d.ord = v.ord
  order by v.ord;
end
$function$
