-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.event_lookup(p_phone text, p_terms text[] DEFAULT NULL::text[], p_city text DEFAULT NULL::text, p_virtual boolean DEFAULT NULL::boolean, p_include_past boolean DEFAULT false, p_limit integer DEFAULT 12, p_embedding text DEFAULT NULL::text, p_at_member_id text DEFAULT NULL::text)
 RETURNS TABLE(event_name text, starts_at timestamp with time zone, start_display text, event_type text, phase text, city text, guests_policy text, chapter text, audience_hint text, is_registered boolean, can_register boolean, reg_link text, guest_reg_link text, spots_left integer, registered_count bigint, event_url text)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare
  v_n int; v_atid text; v_email text; v_email_ok boolean := false; v_is_20m boolean := false;
  v_browse boolean; v_member_chapters text[]; v_vec extensions.vector(1024);
begin
  if p_at_member_id is not null then
    select count(*) into v_n from digest.member_attributes mz where mz.at_member_id = p_at_member_id and digest.is_active_member_status(mz.membership_status);
  else
    select count(*) into v_n from digest.member_identity mz where mz.at_member_id = digest.resolve_asker(p_phone) and digest.is_active_member_status(mz.membership_status);
  end if;
  if v_n < 1 then return; end if;
  select m.at_member_id, lower(nullif(trim(m.email), ''))
    into v_atid, v_email
  from digest.member_identity m where (case when p_at_member_id is not null then m.at_member_id = p_at_member_id else m.at_member_id = digest.resolve_asker(p_phone) end) and digest.is_active_member_status(m.membership_status) order by (m.phone is not null) desc, m.airtable_id limit 1;
  if p_at_member_id is not null and v_atid is null then v_atid := p_at_member_id; end if;
  if v_atid is not null then
    select coalesce(ma.rev_band = '20M+', false), ma.chapter_ids
      into v_is_20m, v_member_chapters
      from digest.member_attributes ma where ma.at_member_id = v_atid;
    v_is_20m := coalesce(v_is_20m, false);
    v_email_ok := v_email is not null and not exists (
      select 1 from digest.members m2
      where lower(m2.email) = v_email and m2.at_member_id is distinct from v_atid);
  end if;
  v_browse := p_terms is null and p_city is null;
  if p_embedding is not null then
    begin
      v_vec := p_embedding::extensions.vector(1024);
    exception when others then
      v_vec := null;
    end;
  end if;

  return query
  with regs as (
    select r.event_at_id,
           count(*) as reg_count,
           bool_or(r.member_at_id = v_atid
                   or (v_email_ok and lower(r.email) = v_email
                       and (r.member_at_id is null
                            or not exists (select 1 from digest.members mo
                                           where mo.at_member_id = r.member_at_id
                                             and mo.phone is not null
                                             and mo.phone <> p_phone)))) as me_registered
    from digest.event_registrations_live r
    group by r.event_at_id
  ), base as (
    select c.*,
      digest.member_event_url(c.member_reg_link, c.app_url) as safe_reg_link,
      digest.member_event_url(c.guest_reg_link, null) as safe_guest_link
    from digest.events_catalog_live c
  ), sel as (
  select
    coalesce(c.app_title, c.name) as o_event_name,
    coalesce(c.app_starts_at, c.start_at) as o_starts_at,
    case when c.event_type = 'Virtual' or c.app_starts_at is null then
      to_char(c.start_at at time zone 'UTC', 'Dy Mon DD, YYYY') || ' (time as listed: ' ||
      to_char(c.start_at at time zone 'UTC', 'HH24:MI') || ' UTC)'
    else
      to_char(c.app_starts_at at time zone coalesce(c.app_timezone,'UTC'), 'Dy Mon DD, YYYY, HH12:MI AM') || ' local time'
    end || case when coalesce(c.app_starts_at, c.start_at) < now()
                 then ' - THIS EVENT HAS ALREADY HAPPENED (past - speak about it in the past tense)'
                 else ' - upcoming' end as o_start_display,
    c.event_type as o_event_type,
    c.phase as o_phase,
    coalesce(c.app_city, nullif(c.city_state,''), nullif(c.location,'')) as o_city,
    c.guests_policy as o_guests_policy,
    c.chapter_hint as o_chapter,
    nullif(concat_ws(' · ',
      case when c.name ~* '[0-9]{2,3}M[+]' then substring(c.name from '([0-9]{2,3}M[+])') || ' tier event' end,
      case when c.name ~* 'centurion' then 'Centurion tier event' end,
      case when c.name ~* $w$women'?s$w$ then 'women''s event' end,
      case when c.name ~* 'recommended event' then 'external industry event (MDS-recommended)' end
    ), '') as o_audience_hint,
    coalesce(g.me_registered, false) as o_is_registered,
    (c.phase = 'Registration Open'
       and c.safe_reg_link is not null
       and coalesce(c.app_starts_at, c.start_at) >= now()) as o_can_register,
    case when c.phase = 'Registration Open'
          and coalesce(c.app_starts_at, c.start_at) >= now()
         then c.safe_reg_link end as o_reg_link,
    case when c.guests_policy in ('Open to Guests','Public Event')
         then c.safe_guest_link end as o_guest_reg_link,
    case when c.venue_capacity is not null
         then greatest(c.venue_capacity - coalesce(g.reg_count, 0)::int, 0) end as o_spots_left,
    coalesce(g.reg_count, 0) as o_registered_count,
    coalesce(c.app_url, c.public_page_url) as o_event_url,
    (select count(*) from unnest(coalesce(p_terms, '{}'::text[])) t
      where c.name ilike '%'||t||'%' or c.app_title ilike '%'||t||'%'
         or c.location ilike '%'||t||'%' or c.city_state ilike '%'||t||'%') as o_term_hits,
    case when v_vec is not null and c.embedding is not null
         then (c.embedding operator(extensions.<=>) v_vec) end as o_vec_dist,
    (case when v_browse then (coalesce(c.app_starts_at, c.start_at) >= now()) else null end) as o_upc,
    (coalesce(c.app_starts_at, c.start_at) >= now()) as o_future,
    abs(extract(epoch from (coalesce(c.app_starts_at, c.start_at) - now()))) as o_prox
  from base c
  left join regs g on g.event_at_id = c.at_record_id
  where coalesce(c.phase,'') not in ('Tentative','Awaiting Feedback')
    and not (c.phase is null and c.event_type = 'Virtual'
             and coalesce(c.app_starts_at, c.start_at) >= now())
    and (p_include_past or not v_browse or coalesce(c.phase,'') not in ('Postponed','Canceled','Cancelled'))
    and (p_include_past or not v_browse
         or c.phase = 'Registration Open'
         )
    and nullif(trim(c.name),'') is not null
    and (p_include_past or not v_browse or coalesce(c.app_starts_at, c.start_at) >= now() - interval '36 hours')
    and (p_virtual is null
         or (p_virtual and c.event_type = 'Virtual')
         or (not p_virtual and c.event_type = 'In Person'))
    and (p_city is null or
         c.city_state ilike '%'||p_city||'%' or c.location ilike '%'||p_city||'%'
         or c.app_city ilike '%'||p_city||'%' or c.chapter_hint ilike '%'||p_city||'%'
         or c.name ilike '%'||p_city||'%')
    and (not v_browse or v_is_20m
         or not (c.name ~* '([0-9]{2,3}M[+]|centurion)'))
    and (
      c.guests_policy = 'Public Event'
      or (
        coalesce(c.style,'') <> 'Chapter'
        and c.name !~* 'chapter'
        and (c.chapter_ids is null or cardinality(c.chapter_ids) = 0)
      )
      or (
        v_member_chapters is not null
        and c.chapter_ids is not null and cardinality(c.chapter_ids) > 0
        and c.chapter_ids && v_member_chapters
      )
    )
  ), ranked as (
    select s.*, case when s.o_vec_dist is not null
                     then rank() over (partition by s.o_future order by s.o_vec_dist asc nulls last) end as o_vec_rank
    from sel s
  )
  select r.o_event_name, r.o_starts_at, r.o_start_display, r.o_event_type, r.o_phase, r.o_city,
         r.o_guests_policy, r.o_chapter, r.o_audience_hint, r.o_is_registered, r.o_can_register,
         r.o_reg_link, r.o_guest_reg_link, r.o_spots_left, r.o_registered_count, r.o_event_url
  from ranked r
  where p_terms is null or r.o_term_hits > 0 or coalesce(r.o_vec_rank, 999) <= 12
  order by
    (case when p_include_past then null else r.o_future end) desc nulls last,
    (1.0/(60 + rank() over (order by r.o_term_hits desc))
     + coalesce(case when r.o_vec_dist is not null
                     then 1.0/(60 + rank() over (order by r.o_vec_dist asc nulls last)) end, 0)) desc,
    r.o_upc desc nulls last,
    r.o_prox asc
  limit least(greatest(coalesce(p_limit, 12), 1), 30);
end $function$
