-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.event_who(p_phone text, p_event text, p_limit integer DEFAULT 60)
 RETURNS TABLE(event_name text, starts_at timestamp with time zone, full_name text, state text, is_me boolean, total_going integer)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare
  v_n int; v_atid text; v_is_20m boolean := false;
  v_event_id text; v_event_name text; v_banded boolean;
  v_me_city text; v_total int;
begin
  if nullif(trim(coalesce(p_event,'')),'') is null then return; end if;
  select case when digest.resolve_asker(p_phone) is not null then 1 else 0 end into v_n;
  if v_n <> 1 then return; end if;
  select digest.resolve_asker(p_phone) into v_atid;
  if v_atid is not null then
    select coalesce(ma.rev_band = '20M+', false), ma.city into v_is_20m, v_me_city
      from digest.member_attributes ma where ma.at_member_id = v_atid;
    v_is_20m := coalesce(v_is_20m, false);
  end if;

  select c.at_record_id, coalesce(c.app_title, c.name),
         (c.name ~* '([0-9]{2,3}M[+]|centurion)')
    into v_event_id, v_event_name, v_banded
  from digest.events_catalog c
  where coalesce(c.phase,'') not in ('Tentative','Awaiting Feedback')
    and (select bool_and(c.name ilike '%'||w||'%'
                          or coalesce(c.app_title,'') ilike '%'||w||'%')
           from regexp_split_to_table(trim(p_event), '[[:space:]]+') w)
  order by (coalesce(c.app_starts_at, c.start_at) >= now()) desc,
           case c.phase when 'Registration Open' then 0 when 'Confirmed' then 1 else 2 end,
           length(c.name) asc,
           coalesce(c.app_starts_at, c.start_at) asc
  limit 1;
  if v_event_id is null then return; end if;
  if v_banded and not v_is_20m then return; end if;

  select (count(distinct r.member_at_id) filter (where r.member_at_id is not null)
          + count(*) filter (where r.member_at_id is null))::int
    into v_total
  from digest.event_registrations_live r
  where r.event_at_id = v_event_id
    and r.ticket_status = 'Confirmed'
    and r.ticket_for && array['MDS Member','MDS Member''s Business Guest','MDS Team'];

  return query
  with conf as (
    select distinct r.member_at_id
    from digest.event_registrations_live r
    where r.event_at_id = v_event_id
      and r.member_at_id is not null
      and r.ticket_status = 'Confirmed'
      and r.ticket_for && array['MDS Member','MDS Member''s Business Guest','MDS Team']
  )
  select v_event_name,
         (select coalesce(c2.app_starts_at, c2.start_at) from digest.events_catalog c2
           where c2.at_record_id = v_event_id),
         coalesce(ma.full_name, mp.full_name),
         ma.state,
         (conf.member_at_id = v_atid),
         v_total
  from conf
  left join digest.member_attributes ma on ma.at_member_id = conf.member_at_id
  left join digest.member_profiles mp on mp.at_member_id = conf.member_at_id
  where coalesce(ma.full_name, mp.full_name) is not null
  order by (conf.member_at_id = v_atid) desc,
           (lower(coalesce(ma.city,'')) = lower(coalesce(v_me_city,''))) desc,
           coalesce(ma.full_name, mp.full_name)
  limit least(greatest(coalesce(p_limit, 60), 1), 60);
end $function$
