-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.event_history(p_phone text)
 RETURNS TABLE(kind text, label text, detail text)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare
  v_n int; v_atid text; v_email text; v_email_ok boolean := false;
begin
  select case when digest.resolve_asker(p_phone) is not null then 1 else 0 end into v_n;
  if v_n < 1 then return; end if;
  select m.at_member_id, lower(nullif(trim(m.email), ''))
    into v_atid, v_email
  from digest.member_identity m where m.at_member_id = digest.resolve_asker(p_phone) and digest.is_active_member_status(m.membership_status);
  if v_atid is null then return; end if;
  v_email_ok := v_email is not null and not exists (
    select 1 from digest.members m2
    where lower(m2.email) = v_email and m2.at_member_id is distinct from v_atid);

  return query
  select 'me'::text,
         nullif(concat_ws(', ', ma.city, ma.state), ''),
         null::text
  from digest.member_attributes ma
  where ma.at_member_id = v_atid and (ma.city is not null or ma.state is not null);

  return query
  select distinct on (c.at_record_id)
         'upcoming'::text,
         coalesce(c.app_title, c.name),
         to_char(coalesce(c.app_starts_at, c.start_at) at time zone 'UTC', 'YYYY-MM-DD')
  from digest.event_registrations_live r
  join digest.events_catalog_live c on c.at_record_id = r.event_at_id
  where (r.member_at_id = v_atid
         or (v_email_ok and lower(r.email) = v_email
             and (r.member_at_id is null
                  or not exists (select 1 from digest.members mo
                                 where mo.at_member_id = r.member_at_id
                                   and mo.phone is not null
                                   and mo.phone <> p_phone))))
    and coalesce(c.app_starts_at, c.start_at) >= now()
  order by c.at_record_id, coalesce(c.app_starts_at, c.start_at);

  return query
  with past as (
    select distinct on (c.at_record_id)
           coalesce(c.app_title, c.name) as nm,
           coalesce(c.app_starts_at, c.start_at) as st
    from digest.event_registrations_live r
    join digest.events_catalog_live c on c.at_record_id = r.event_at_id
    where (r.member_at_id = v_atid
           or (v_email_ok and lower(r.email) = v_email
               and (r.member_at_id is null
                    or not exists (select 1 from digest.members mo
                                   where mo.at_member_id = r.member_at_id
                                     and mo.phone is not null
                                     and mo.phone <> p_phone))))
      and coalesce(c.app_starts_at, c.start_at) < now()
    order by c.at_record_id
  )
  select 'past'::text, p.nm, to_char(p.st at time zone 'UTC', 'YYYY-MM-DD')
  from past p order by p.st desc limit 15;

  return query
  select 'past_total'::text,
         count(distinct c.at_record_id)::text,
         null::text
  from digest.event_registrations_live r
  join digest.events_catalog_live c on c.at_record_id = r.event_at_id
  where (r.member_at_id = v_atid
         or (v_email_ok and lower(r.email) = v_email
             and (r.member_at_id is null
                  or not exists (select 1 from digest.members mo
                                 where mo.at_member_id = r.member_at_id
                                   and mo.phone is not null
                                   and mo.phone <> p_phone))))
    and coalesce(c.app_starts_at, c.start_at) < now()
  having count(distinct c.at_record_id) > 0;
end $function$
