-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.expertise_query(p_query text)
 RETURNS tsquery
 LANGUAGE plpgsql
 IMMUTABLE
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare
  q text := lower(coalesce(p_query, ''));
  parts text[] := '{}';
  syn record;
  result tsquery := null;
  p text;
  tq tsquery;
begin
  parts := array(select t from regexp_split_to_table(regexp_replace(q, '[^a-z0-9 ]', ' ', 'g'), '[[:space:]]+') t
                 where length(t) >= 2);
  for syn in
    select s.syns from (values
      ('ppc',        array['ppc','advertising','ads','sponsored','acos','tacos','paid media','google ads','amazon advertising']),
      ('ads',        array['ppc','advertising','ads','sponsored']),
      ('advertis',   array['ppc','advertising','ads','sponsored']),
      ('marketing',  array['marketing','advertising','ads','growth','acquisition']),
      ('seo',        array['seo','listing','optimization','keyword','ranking','copywriting']),
      ('listing',    array['listing','seo','optimization','copywriting']),
      ('sourc',      array['sourcing','supplier','supply','manufacturer','factory','china','import','alibaba']),
      ('supplier',   array['sourcing','supplier','supply','manufacturer']),
      ('logistic',   array['logistics','3pl','fulfillment','fba','freight','shipping','warehouse','inventory']),
      ('inventory',  array['inventory','logistics','supply','forecasting','fba']),
      ('brand',      array['brand','branding','design','creative','packaging']),
      ('dtc',        array['dtc','shopify','ecommerce','website','funnel','klaviyo']),
      ('shopify',    array['dtc','shopify','ecommerce','website']),
      ('tiktok',     array['tiktok','social','ugc','influencer','creator','shop']),
      ('wholesale',  array['wholesale','distribution','retail','b2b']),
      ('supplement', array['supplement','supplements','health','nutrition','fda','cpg']),
      ('finance',    array['finance','accounting','cashflow','bookkeeping','tax','cfo']),
      ('hir',        array['hiring','recruiting','team','sop','operations','management']),
      ('operation',  array['operations','sop','systems','processes','team','management']),
      ('exit',       array['exit','acquisition','m&a','valuation','aggregator','sell business']),
      ('ai',         array['ai','automation','chatgpt','claude','agents','workflow']),
      ('automation', array['automation','ai','systems','zapier','make','n8n']),
      ('reimburs',   array['reimbursement','reimbursements','refund','recovery','fba errors','discrepancies']),
      ('refund',     array['reimbursement','refund','recovery']),
      ('insur',      array['insurance','liability','coverage','policy']),
      ('fund',       array['funding','financing','capital','loan','credit','cash flow','working capital']),
      ('financ',     array['funding','financing','capital','loan','credit','cash flow']),
      ('capital',    array['funding','financing','capital','loan','credit']),
      ('trademark',  array['trademark','patent','ip','intellectual property','brand registry','counterfeit','infringement']),
      ('patent',     array['trademark','patent','ip','intellectual property']),
      ('walmart',    array['walmart','marketplace','omnichannel']),
      ('suspen',     array['suspension','suspended','reinstatement','appeal','account health','deactivat']),
      ('reinstat',   array['suspension','reinstatement','appeal','account health']),
      ('profit',     array['profit','profitability','margin','analytics','pnl']),
      ('bookkeep',   array['bookkeeping','accounting','tax','cfo']),
      ('photo',      array['photography','photo','images','creative','video','content']),
      ('translat',   array['translation','localization','international'])
    ) as s(key, syns)
    where q like '%' || s.key || '%'
  loop
    parts := parts || syn.syns;
  end loop;

  if array_length(parts, 1) is null then return null; end if;

  foreach p in array (select array_agg(distinct x) from unnest(parts) x) loop
    tq := plainto_tsquery('english', p);
    if tq is not null and tq::text <> '' then
      result := case when result is null then tq else result || tq end;  -- || = OR
    end if;
  end loop;
  return result;
end $function$
