-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.expertise_search(p_phone text, p_query text, p_limit integer DEFAULT 12, p_embedding text DEFAULT NULL::text)
 RETURNS TABLE(full_name text, city text, state text, expertise text, niche text, matched_text text, matched_rank real)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare
  v_n int; v_atid text; v_q tsquery; v_vec extensions.vector(1024); v_audit boolean;
begin
  if nullif(trim(coalesce(p_query,'')),'') is null then return; end if;
  select case when digest.resolve_asker(p_phone) is not null then 1 else 0 end into v_n;
  if v_n <> 1 then return; end if;
  select digest.resolve_asker(p_phone) into v_atid;
  if v_atid is null then return; end if;

  v_audit := coalesce((current_setting('request.headers', true))::json->>'x-olivia-audit','') <> '';

  v_q := digest.expertise_query(p_query);
  begin
    if p_embedding is not null and left(trim(p_embedding),1) = '[' then
      v_vec := p_embedding::extensions.vector(1024);
    end if;
  exception when others then v_vec := null;
  end;
  if v_q is null and v_vec is null then return; end if;

  drop table if exists _es_out;
  create temp table _es_out on commit drop as
  with pool as (
    select ma.at_member_id, ma.full_name, ma.city, ma.state, ma.categories,
           mp.at_fields, mp.engagement_score
    from digest.member_attributes ma
    join digest.member_profiles mp on mp.at_member_id = ma.at_member_id
    where ma.at_member_id <> v_atid
      and ma.full_name is not null
      and ma.membership_status in ('Current Member','New Member','Pending Group Entrance','Current Member- Not Renewing')
  ),
  kw as (
    select p.at_member_id,
           row_number() over (order by
             digest.term_cover(p.at_fields, p_query) desc,
             (digest.en_rank(p.at_fields, v_q) > 0) desc,
             coalesce(p.engagement_score, 0) desc,
             digest.profile_rank(p.at_fields, v_q) desc,
             p.full_name) as rk
    from pool p
    where v_q is not null
      and to_tsvector('english',
            coalesce(digest.attr_clean(p.at_fields->>'Area of Expertise'),'') || ' ' ||
            coalesce(p.at_fields->>'About Me','') || ' ' ||
            coalesce(digest.attr_clean(p.at_fields->>'Main Niche'),'') || ' ' ||
            coalesce(digest.attr_clean(p.at_fields->>'Interesting / Fun fact'),'')) @@ v_q
    limit 40
  ),
  vec as (
    select e.at_member_id,
           row_number() over (order by e.embedding operator(extensions.<=>) v_vec) as rk
    from digest.member_profile_embeddings e
    join pool p on p.at_member_id = e.at_member_id
    where v_vec is not null and e.embedding is not null
    order by e.embedding operator(extensions.<=>) v_vec
    limit 40
  ),
  merged as (
    select coalesce(k.at_member_id, v.at_member_id) as id,
           coalesce(1.0/(60+k.rk), 0) + coalesce(1.0/(60+v.rk), 0) as rrf
    from kw k full outer join vec v on v.at_member_id = k.at_member_id
  ),
  recent as (
    select r.recommended_at_id,
           bool_or(r.asker_at_id = v_atid and r.created_at >= now() - interval '30 days') as asker_repeat,
           max(r.created_at) filter (where r.asker_at_id = v_atid) as last_rec_at,
           count(*) filter (where r.created_at >= now() - interval '7 days') as global_7d
    from digest.olivia_recommendations r
    where r.created_at >= now() - interval '30 days'
    group by 1
  )
  select p.at_member_id, p.full_name, p.city, p.state,
         digest.attr_clean(p.at_fields->>'Area of Expertise') as expertise,
         digest.attr_clean(p.at_fields->>'Main Niche') as niche,
         left(concat_ws(' | ',
           case when digest.attr_clean(p.at_fields->>'About Me') is not null
                then 'about: ' || digest.attr_clean(p.at_fields->>'About Me') end,
           case when digest.attr_clean(p.at_fields->>'Interesting / Fun fact') is not null
                then 'fun fact: ' || digest.attr_clean(p.at_fields->>'Interesting / Fun fact') end), 500) as matched_text,
         (case when v_q is not null then
           ts_rank(
             to_tsvector('english',
               coalesce(digest.attr_clean(p.at_fields->>'Area of Expertise'),'') || ' ' ||
               coalesce(p.at_fields->>'About Me','') || ' ' ||
               coalesce(digest.attr_clean(p.at_fields->>'Main Niche'),'') || ' ' ||
               coalesce(digest.attr_clean(p.at_fields->>'Interesting / Fun fact'),'')),
             v_q)
         else 0::real end) as matched_rank,
         row_number() over (order by
           (m.rrf * case when coalesce(rc.asker_repeat, false) then 0.6 else 1.0 end) desc,
           (coalesce(p.engagement_score, 0) - 15 * ln(1 + coalesce(rc.global_7d, 0))) desc,
           rc.last_rec_at asc nulls first,
           p.full_name) as ord
  from merged m
  join pool p on p.at_member_id = m.id
  left join recent rc on rc.recommended_at_id = p.at_member_id
  order by ord
  limit least(greatest(coalesce(p_limit, 12), 1), 30);

  if not v_audit then
    insert into digest.olivia_recommendations (asker_at_id, recommended_at_id, lane)
    select v_atid, o.at_member_id, 'expertise_search' from _es_out o;
  end if;

  return query
  select o.full_name, o.city, o.state, o.expertise, o.niche, o.matched_text, o.matched_rank
  from _es_out o order by o.ord;
end $function$
