-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.expertise_search(p_phone text, p_query text, p_limit integer DEFAULT 12, p_embedding text DEFAULT NULL::text)
 RETURNS TABLE(full_name text, city text, state text, expertise text, niche text, matched_text text, matched_rank real)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare
  v_n int; v_atid text; v_q tsquery; v_vec extensions.vector(1024);
begin
  if nullif(trim(coalesce(p_query,'')),'') is null then return; end if;
  select case when digest.resolve_asker(p_phone) is not null then 1 else 0 end into v_n;
  if v_n <> 1 then return; end if;
  select digest.resolve_asker(p_phone) into v_atid;
  if v_atid is null then return; end if;

  v_q := digest.expertise_query(p_query);
  begin
    if p_embedding is not null and left(trim(p_embedding),1) = '[' then
      v_vec := p_embedding::extensions.vector(1024);
    end if;
  exception when others then v_vec := null;  -- malformed vector degrades to keyword
  end;
  if v_q is null and v_vec is null then return; end if;

  return query
  with pool as (
    select ma.at_member_id, ma.full_name, ma.city, ma.state, ma.categories,
           mp.at_fields, mp.engagement_score
    from digest.member_attributes ma
    join digest.member_profiles mp on mp.at_member_id = ma.at_member_id
    where ma.at_member_id <> v_atid
      and ma.full_name is not null
      and ma.membership_status in ('Current Member','New Member','Pending Group Entrance','Current Member- Not Renewing')
  ),
  kw as (
    select p.at_member_id,
           row_number() over (order by
             digest.term_cover(p.at_fields, p_query) desc,
             (digest.en_rank(p.at_fields, v_q) > 0) desc,
             coalesce(p.engagement_score, 0) desc,
             digest.profile_rank(p.at_fields, v_q) desc,
             p.full_name) as rk
    from pool p
    where v_q is not null
      and to_tsvector('english',
            coalesce(digest.attr_clean(p.at_fields->>'Area of Expertise'),'') || ' ' ||
            coalesce(p.at_fields->>'About Me','') || ' ' ||
            coalesce(digest.attr_clean(p.at_fields->>'Main Niche'),'') || ' ' ||
            coalesce(digest.attr_clean(p.at_fields->>'Interesting / Fun fact'),'')) @@ v_q
    limit 40
  ),
  vec as (
    select e.at_member_id,
           row_number() over (order by e.embedding operator(extensions.<=>) v_vec) as rk
    from digest.member_profile_embeddings e
    join pool p on p.at_member_id = e.at_member_id
    where v_vec is not null and e.embedding is not null
    order by e.embedding operator(extensions.<=>) v_vec
    limit 40
  ),
  merged as (
    select coalesce(k.at_member_id, v.at_member_id) as id,
           coalesce(1.0/(60+k.rk), 0) + coalesce(1.0/(60+v.rk), 0) as rrf
    from kw k full outer join vec v on v.at_member_id = k.at_member_id
  )
  select p.full_name, p.city, p.state,
         digest.attr_clean(p.at_fields->>'Area of Expertise'),
         digest.attr_clean(p.at_fields->>'Main Niche'),
         left(concat_ws(' | ',
           case when digest.attr_clean(p.at_fields->>'About Me') is not null
                then 'about: ' || digest.attr_clean(p.at_fields->>'About Me') end,
           case when digest.attr_clean(p.at_fields->>'Interesting / Fun fact') is not null
                then 'fun fact: ' || digest.attr_clean(p.at_fields->>'Interesting / Fun fact') end), 500),
         case when v_q is not null then
           ts_rank(
             to_tsvector('english',
               coalesce(digest.attr_clean(p.at_fields->>'Area of Expertise'),'') || ' ' ||
               coalesce(p.at_fields->>'About Me','') || ' ' ||
               coalesce(digest.attr_clean(p.at_fields->>'Main Niche'),'') || ' ' ||
               coalesce(digest.attr_clean(p.at_fields->>'Interesting / Fun fact'),'')),
             v_q)
         else 0::real end as matched_rank
  from merged m
  join pool p on p.at_member_id = m.id
  order by m.rrf desc, coalesce(p.engagement_score, 0) desc, p.full_name
  limit least(greatest(coalesce(p_limit, 12), 1), 30);
end $function$
