-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.fb_link_content()
 RETURNS TABLE(posts_linked bigint, comments_linked bigint, images_enriched bigint)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare p bigint; c bigint; ie bigint;
begin
  with ins as (
    insert into digest.content_items (source,kind,source_id,body,occurred_at,url,access_rule,sensitivity,meta)
    select 'fb_post','post',post_id,text,created_time,
      'https://www.facebook.com/groups/699138040189700/posts/'||post_id||'/',
      '{"type":"public"}'::jsonb,'normal',jsonb_build_object('author_name',author_name)
    from digest.fb_posts on conflict (source,source_id) do nothing returning 1)
  select count(*) into p from ins;
  with ins as (
    insert into digest.content_items (source,kind,source_id,body,occurred_at,url,access_rule,sensitivity,meta)
    select 'fb_comment','comment',fc.comment_id,fc.text,fc.created_time,
      'https://www.facebook.com/groups/699138040189700/posts/'||fc.post_id||'/',
      '{"type":"public"}'::jsonb,'normal',
      jsonb_build_object('post_id',fc.post_id,'author_name',fc.author_name,'sender_member',m.at_member_id)
    from digest.fb_comments fc left join digest.fb_member_map m on m.fb_uid=fc.author_uid
    on conflict (source,source_id) do nothing returning 1)
  select count(*) into c from ins;
  update digest.fb_post_images set storage_path = 'fb-images/' || regexp_replace(local_path, '^.*/', '')
   where storage_path is null and local_path is not null;
  -- search_extra is REBUILT here, never appended to, so every contributing source must be in this
  -- union: image vision text (ord 1) then link-preview cards (ord 2). Cards are DISTINCT-ed because
  -- one shared link is captured at several thumbnail sizes = several rows, one card. display_name
  -- sits next to the domain because to_tsvector treats "theguardian.com" as one unsplittable token.
  with parts as (
    select post_id, 1 as ord, string_agg(nullif(trim(coalesce(description,'') ||
        case when nullif(ocr_text,'') is not null then ' [text in image: '||ocr_text||']' else '' end),''),' | '
        order by idx) as t
    from digest.fb_post_images where description is not null or nullif(ocr_text,'') is not null group by post_id
    union all
    select post_id, 2 as ord, string_agg(card,' | ' order by card) as t
    from (select distinct post_id,
            '[shared link: '||coalesce(nullif(display_name,'')||' ','')||domain
              ||coalesce(' '||target_url,'')||']' as card
          from digest.fb_post_links where domain is not null) l
    group by post_id),
  agg as (
    select post_id, string_agg(t,' | ' order by ord) as t from parts where t is not null group by post_id),
  upd as (
    update digest.content_items ci set search_extra = agg.t, embedding = null
    from agg where ci.source='fb_post' and ci.source_id = agg.post_id
      and agg.t is not null and ci.search_extra is distinct from agg.t returning 1)
  select count(*) into ie from upd;
  return query select p, c, ie;
end $function$
