-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.fill_member_display_name()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare v_disp text;
begin
  if new.at_member_id is not null then
    v_disp := digest.member_display_name(new.at_member_id);
    if v_disp is not null then
      new.full_name := v_disp;
    end if;
  end if;
  return new;
end $function$
