-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.fill_member_chapter()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare a jsonb;
begin
  select at_fields into a from digest.member_profiles where at_member_id = NEW.at_member_id;
  if a is not null then
    NEW.chapter_affiliation := case when jsonb_typeof(a->'Chapter Affiliation') = 'array'
      then array(select jsonb_array_elements_text(a->'Chapter Affiliation')) end;
    NEW.chapter_ids := case when jsonb_typeof(a->'Link to Chapters') = 'array'
      then array(select jsonb_array_elements_text(a->'Link to Chapters')) else '{}'::text[] end;
  end if;
  return NEW;
end $function$
