-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.form_field_history(p_phone text, p_field text DEFAULT NULL::text)
 RETURNS TABLE(canonical_key text, answer text, form_name text, submitted_at timestamp with time zone)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare v_n int; v_atid text;
begin
  select count(*) into v_n from digest.members m
   where m.phone = p_phone and digest.is_active_member_status(m.membership_status);
  if v_n <> 1 then return; end if;
  select m.at_member_id into v_atid from digest.members m
   where m.phone = p_phone and digest.is_active_member_status(m.membership_status);

  return query
  select coalesce(m.canonical_key, a.key),
         case when jsonb_typeof(a.value->'v') in ('array','object')
              then (select string_agg(x.e, ', ') from (
                      select jsonb_array_elements_text(a.value->'v') e) x)
              else a.value->>'v' end,
         fr.form_name, fr.submitted_at
  from digest.form_responses fr
  join digest.form_scope sc on sc.form_id = fr.form_id and sc.scope = 'profile'
  cross join lateral jsonb_each(fr.answers) a
  left join digest.form_field_map m on m.form_id = fr.form_id and m.ref = a.key
  where fr.member_at_id = v_atid
    and a.key not in ('email','phone','full_name')
    and (p_field is null or coalesce(m.canonical_key, a.key) = p_field
         or (a.value->>'q') ilike '%'||p_field||'%')
  order by 1, submitted_at asc
  limit 200;
end $function$
