-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.form_stats(p_phone text, p_question text DEFAULT NULL::text, p_form_id text DEFAULT NULL::text, p_group_by text DEFAULT NULL::text, p_since date DEFAULT NULL::date, p_until date DEFAULT NULL::date)
 RETURNS TABLE(label text, value numeric, detail text)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare
  v_n int;
  v_tokens text[];
begin
  select count(*) into v_n from digest.member_identity m
   where m.at_member_id = digest.resolve_asker(p_phone) and digest.is_active_member_status(m.membership_status);
  if v_n <> 1 then return; end if;

  if nullif(trim(coalesce(p_question,'')),'') is null then
    return query
    with w as materialized (
      select * from digest.form_windowed(p_form_id, p_since, p_until)
    ), k as (
      select w.canonical_key ck, min(w.question) q, count(distinct w.member_at_id) nn,
             avg(case when jsonb_typeof(w.value) = 'number'
                        or (jsonb_typeof(w.value) = 'string' and (w.value #>> '{}') ~ '^[0-9][0-9,.]*$')
                      then 1.0 else 0.0 end) num_share,
             bool_or(w.answer_type in ('choice','choices','boolean')) has_choice,
             bool_or(w.canonical_key <> w.ref) curated
      from w group by w.canonical_key
      having count(distinct w.member_at_id) >= 3
    )
    select k.ck, k.nn::numeric, k.q from k
    where k.num_share >= 0.8 or k.has_choice or k.curated
    order by k.nn desc limit 100;
    return;
  end if;

  select array_agg(distinct t) into v_tokens
  from (
    select tok t from regexp_split_to_table(lower(p_question), '[^a-z0-9_]+') tok where length(tok) >= 4
    union
    select regexp_replace(tok, 's$', '') from regexp_split_to_table(lower(p_question), '[^a-z0-9_]+') tok
     where length(tok) >= 5 and tok like '%s'
  ) x
  where t not in ('what','your','yours','which','where','when','does','have','many','much','from','with',
                  'that','this','they','them','will','been','members','member','typically','typical',
                  'average','avg','median','share','percent','percentage','rate','about','their','there','email','emails','address','addresses','phone','phones','name','names');

  return query
  with w as materialized (
    select * from digest.form_windowed(p_form_id, p_since, p_until)
  ),
  keys as (
    select w.canonical_key ck, min(w.question) q,
           count(distinct w.member_at_id) nn,
           avg(case when jsonb_typeof(w.value) = 'number'
                      or (jsonb_typeof(w.value) = 'string' and (w.value #>> '{}') ~ '^[0-9][0-9,.]*$')
                    then 1.0 else 0.0 end) >= 0.8 as is_num,
           bool_or(w.answer_type in ('choice','choices','boolean')) has_choice,
           bool_or(w.canonical_key <> w.ref) curated
    from w
    group by w.canonical_key
    having count(distinct w.member_at_id) >= 3
       and (w.canonical_key = p_question
            or min(w.question) ilike '%'||p_question||'%'
            or exists (select 1 from unnest(coalesce(v_tokens,'{}'::text[])) t
                       where lower(min(w.question)) like '%'||t||'%'
                          or lower(w.canonical_key) like '%'||t||'%'))
    order by (min(w.canonical_key) = p_question) desc,
             (select count(*) from unnest(coalesce(v_tokens,'{}'::text[])) t
               where lower(min(w.question)) like '%'||t||'%' or lower(w.canonical_key) like '%'||t||'%') desc,
             count(distinct w.member_at_id) desc
    limit 4
  ),
  nums as (
    select k.q, grpd.grp, avg(grpd.v) mean, count(*) n,
           (percentile_cont(0.5) within group (order by grpd.v))::numeric med,
           (percentile_cont(0.1) within group (order by grpd.v))::numeric p10,
           (percentile_cont(0.9) within group (order by grpd.v))::numeric p90,
           avg(case when grpd.v > 0 then 1.0 else 0.0 end) share_pos
    from keys k
    join lateral (
      select case when jsonb_typeof(w2.value) = 'number' then (w2.value)::text::numeric
                  else replace((w2.value #>> '{}'), ',', '')::numeric end v,
             g.grp
      from w w2
      left join digest.member_attributes ma on ma.at_member_id = w2.member_at_id
      left join digest.member_profiles mpg on mpg.at_member_id = w2.member_at_id
      cross join lateral (
        select case p_group_by when 'country' then ma.country when 'state' then ma.state
                               when 'niche' then ma.main_niche when 'rev_band' then ma.rev_band
                               when 'gender' then case when lower(coalesce(nullif(trim(mpg.at_fields->>'Gender'),''),'unspecified')) in ('male','female') then lower(trim(mpg.at_fields->>'Gender')) else 'unspecified' end
                               else 'all' end grp
        where coalesce(p_group_by,'') <> 'chapter'
        union all
        select ch from unnest(coalesce(ma.chapter_affiliation, '{}'::text[])) ch
        where p_group_by = 'chapter'
      ) g
      where w2.canonical_key = k.ck
        and (jsonb_typeof(w2.value) = 'number'
             or (jsonb_typeof(w2.value) = 'string' and (w2.value #>> '{}') ~ '^[0-9][0-9,.]*$'))
    ) grpd on true
    where k.is_num and grpd.grp is not null
    group by k.q, grpd.grp
    having count(*) >= 3
  ),
  chos as (
    select k.q, o.opt, count(distinct o.member_at_id) n, k.nn base
    from keys k
    join lateral (
      select w3.member_at_id,
             case when w3.answer_type in ('choice','choices','boolean') then oo.raw_opt
                  else initcap(lower(trim(oo.raw_opt))) end opt
      from w w3
      cross join lateral (
        select jsonb_array_elements_text(w3.value) as raw_opt
        where jsonb_typeof(w3.value) = 'array'
        union all
        select w3.value #>> '{}' where jsonb_typeof(w3.value) <> 'array'
      ) oo
      where w3.canonical_key = k.ck
    ) o on true
    where not k.is_num and (k.has_choice or k.curated)
      and nullif(trim(o.opt),'') is not null
    group by k.q, o.opt, k.nn
    having count(distinct o.member_at_id) >= 3
  )
  select * from (
    select n1.q || case when n1.grp <> 'all' then ' ['||n1.grp||']' else '' end,
           round(n1.med, 0),
           'EXACT reported numbers - median (lead with this) · avg=' || round(n1.mean::numeric,0)
             || ' · typical range (10th-90th pct)=' || round(n1.p10,0) || '..' || round(n1.p90,0)
             || ' · share>0=' || round(100*n1.share_pos::numeric,0) || '%'
             || ' · n=' || n1.n || ' (n INTERNAL - never say how many answered; never quote a single member''s extreme)'
    from nums n1
    union all
    select c.q || ' — ' || c.opt,
           round(100.0 * c.n / c.base, 1),
           'PERCENT of members who answered this question (no-answers excluded from the base) - speak %, never counts'
    from chos c
  ) u
  order by 2 desc
  limit 40;
end $function$
