-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.form_windowed(p_form_id text, p_since date, p_until date)
 RETURNS TABLE(member_at_id text, canonical_key text, ref text, question text, answer_type text, value jsonb, submitted_at timestamp with time zone)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  select distinct on (e.member_at_id, e.canonical_key)
         e.member_at_id, e.canonical_key, e.ref, e.question, e.answer_type, e.value, e.submitted_at
  from digest.form_answers_exploded e
  join digest.form_scope s on s.form_id = e.form_id and s.scope = 'profile'
  where (p_form_id is null or e.form_id = p_form_id)
    and (p_since is null or e.submitted_at >= p_since)
    and (p_until is null or e.submitted_at < p_until)
  order by e.member_at_id, e.canonical_key, e.submitted_at desc
$function$
