-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.geo_country_unmatched(p text)
 RETURNS boolean
 LANGUAGE sql
 STABLE
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  select case
    when digest.geo_country_set(p) is null then false
    else not exists (
      select 1 from digest.member_attributes ma
      where digest.is_active_member_status(ma.membership_status)
        and digest.country_fold(ma.country) = any(digest.geo_country_set(p)))
  end
$function$
