-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.geo_country_set(p text)
 RETURNS text[]
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  select nullif(array(
    select distinct c from (
      select unnest(coalesce(digest.country_region_countries(tok),
                             case when digest.country_fold(tok) is not null
                                  then array[digest.country_fold(tok)] end)) c
      from unnest(string_to_array(coalesce(p,''), ',')) tok
      where nullif(trim(tok),'') is not null
    ) s where c is not null
  ), '{}')
$function$
