-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.health_report_secret()
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'vault', 'pg_temp'
AS $function$
declare v_secret text;
begin
  select decrypted_secret into v_secret
    from vault.decrypted_secrets where name = 'HEALTH_REPORT_SECRET' limit 1;
  return jsonb_build_object('secret', coalesce(v_secret, ''));
end;
$function$
