-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.is_active_member_status(p_status text)
 RETURNS boolean
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  select p_status in ('Current Member', 'New Member', 'Current Member- Not Renewing',
                      'Staff', 'Pending Group Entrance')
$function$
