-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.is_internal_record(p_status text)
 RETURNS boolean
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  -- #106 (Andy 2026-08-22 "make sure I'm not searchable"; Eugene 2026-08-24 "need to filter out
  -- the team"). This is the SUBJECT-side predicate: may this record be SHOWN to a member?
  -- It is deliberately NOT digest.is_active_member_status(), which is the ACCESS predicate
  -- (may this person USE Millie?) and correctly includes 'Staff' so the team can ask.
  -- btrim guards the trailing-space statuses that exist live ('Declined Applicant ').
  select btrim(coalesce(p_status, '')) in ('Staff', 'Team User')
$function$
