-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.mark_stale_members(p_stale_after interval DEFAULT '24:00:00'::interval, p_min_healthy_share numeric DEFAULT 0.80)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare
  v_total   bigint;
  v_fresh   bigint;
  v_share   numeric;
  v_marked  bigint;
  v_cleared bigint;
begin
  select count(*), count(*) filter (where synced_at > now() - p_stale_after)
    into v_total, v_fresh from digest.members;

  if v_total = 0 then
    return jsonb_build_object('ok', true, 'skipped', 'no members', 'marked', 0, 'cleared', 0);
  end if;

  -- A row that came back is not stale, whatever it was before. Always safe, so it runs even
  -- when the wave is unhealthy: clearing a mark can never hide a live member.
  update digest.members set stale_since = null
   where stale_since is not null and synced_at > now() - p_stale_after;
  get diagnostics v_cleared = row_count;

  v_share := v_fresh::numeric / v_total;
  if v_share < p_min_healthy_share then
    return jsonb_build_object('ok', false, 'skipped', 'sync wave looks unhealthy',
                              'fresh_share', round(v_share, 3), 'required', p_min_healthy_share,
                              'marked', 0, 'cleared', v_cleared);
  end if;

  update digest.members
     set stale_since = now()
   where stale_since is null and synced_at <= now() - p_stale_after;
  get diagnostics v_marked = row_count;

  return jsonb_build_object('ok', true, 'fresh_share', round(v_share, 3),
                            'marked', v_marked, 'cleared', v_cleared,
                            'stale_total', (select count(*) from digest.members where stale_since is not null));
end;
$function$
