-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.member_card_v3(p_phone text, p_member text)
 RETURNS TABLE(full_name text, city text, state text, country text, revenue_tier text, niche text, expertise text, about_me text, hobbies text, fun_fact text, facebook_link text, chapter text, channels text[], business_model text[], categories text[], shared_chats text[], membership_state text, joined date, left_date date, brands text[])
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  select c.*,
         (select array_agg(distinct b order by b)
            from digest.member_profiles mp
            join digest.member_attributes ma on ma.at_member_id = mp.at_member_id,
                 lateral (select trim(regexp_replace(x, '(https?://|www\.)[^ ]*', ' ', 'g')) as b
                            from regexp_split_to_table(
                                   concat_ws(', ',
                                     digest.attr_clean(mp.at_fields->>'Brand Name'),
                                     mp.at_fields->>'Brand(s) URL / Name(s)',
                                     digest.attr_clean(mp.at_fields->>'Storefront - Census')),
                                   '\s*,\s*') x) t
           where digest.name_fold(coalesce(nullif(trim(mp.at_fields->>'Full Name'), ''),
                                           nullif(trim(mp.full_name), ''),
                                           ma.full_name)) = digest.name_fold(c.full_name)
             and length(t.b) >= 3) as brands
    from digest.member_card_v2(p_phone, p_member) c
$function$
