-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.member_dossier(p_phone text)
 RETURNS TABLE(kind text, label text, detail text)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare
  v_n int; v_atid text; v_warow text;
begin
  select case when digest.resolve_asker(p_phone) is not null then 1 else 0 end into v_n;
  if v_n < 1 then return; end if;
  select m.at_member_id, m.airtable_id into v_atid, v_warow
    from digest.member_identity m where m.at_member_id = digest.resolve_asker(p_phone) and digest.is_active_member_status(m.membership_status);

  -- the living persona card (#28), the asker's own only
  if v_atid is not null then
    return query
    select 'persona'::text, p.key,
           left(regexp_replace(p.value::text, '[[:space:]]+', ' ', 'g'), 400)
    from digest.member_personas mp,
         lateral jsonb_each(mp.persona) p(key, value)
    where mp.at_member_id = v_atid
    limit 10;
  end if;

  -- where they are engaged (their own message counts, 30d)
  return query
  select 'active_chat'::text, w.chat_name, count(*)::text
  from digest.wa_messages w
  where w.sender_member = v_warow and w.sent_at >= now() - interval '30 days'
    and nullif(trim(coalesce(w.text,'')),'') is not null
  group by w.chat_name order by count(*) desc limit 5;

  -- what they have been saying (their OWN words, newest first)
  return query
  select 'recent_said'::text,
         w.chat_name || ' · ' || to_char(w.sent_at, 'Mon DD'),
         left(regexp_replace(w.text, '[[:space:]]+', ' ', 'g'), 180)
  from digest.wa_messages w
  where w.sender_member = v_warow
    and length(coalesce(w.text,'')) >= 30
  order by w.sent_at desc limit 8;

  -- their events (upcoming + recent past), own data
  if v_atid is not null then
    return query
    select case when coalesce(c.app_starts_at, c.start_at) >= now()
                then 'upcoming_event' else 'past_event' end,
           coalesce(c.app_title, c.name),
           to_char(coalesce(c.app_starts_at, c.start_at), 'YYYY-MM-DD')
    from (select distinct r.event_at_id from digest.event_registrations_live r
           where r.member_at_id = v_atid) x
    join digest.events_catalog c on c.at_record_id = x.event_at_id
    order by 1 desc, 3 desc limit 10;
  end if;
end $function$
