-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.member_personas_archive()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  insert into digest.member_personas_history
    (at_member_id, version, persona, signals_hash, model, built_at)
  values (old.at_member_id, old.version, old.persona, old.signals_hash, old.model, old.built_at)
  on conflict (at_member_id, version) do nothing;
  new.version := old.version + 1;
  return new;
end $function$
