-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.member_match_v2(p_phone text, p_dims text[] DEFAULT ARRAY['state'::text, 'category'::text, 'band'::text], p_limit integer DEFAULT 10, p_city text DEFAULT NULL::text, p_state text DEFAULT NULL::text, p_channel text DEFAULT NULL::text, p_category text DEFAULT NULL::text, p_country text DEFAULT NULL::text)
 RETURNS TABLE(full_name text, city text, state text, reasons text[], matched_total bigint)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare
  v_n int; v_atid text; me digest.member_attributes;
  use_city boolean; use_state boolean; use_cat boolean; use_band boolean;
  use_model boolean; use_channel boolean;
  tgt_city text; tgt_channel text; tgt_category text;
  tgt_states text[]; tgt_state_label text;
  tgt_countries text[]; tgt_country_label text;
  target_mode boolean; trait_mode boolean; v_audit boolean;
begin
  select case when digest.resolve_asker(p_phone) is not null then 1 else 0 end into v_n;
  if v_n < 1 then return; end if;
  select digest.resolve_asker(p_phone) into v_atid;
  if v_atid is null then return; end if;
  select * into me from digest.member_attributes ma where ma.at_member_id = v_atid;
  if me is null then return; end if;

  v_audit := coalesce((current_setting('request.headers', true))::json->>'x-olivia-audit','') <> '';

  tgt_city := digest.place_city(p_city);
  tgt_states := digest.geo_state_set(p_state);
  tgt_state_label := case when tgt_states is not null and cardinality(tgt_states) > 1
                          then initcap(trim(p_state)) end;
  tgt_channel := nullif(trim(coalesce(p_channel, '')), '');
  tgt_category := nullif(trim(coalesce(p_category, '')), '');
  tgt_countries := digest.geo_country_set(p_country);
  tgt_country_label := case when tgt_countries is not null then initcap(trim(p_country)) end;
  target_mode := tgt_city is not null or tgt_states is not null or tgt_countries is not null;
  trait_mode := tgt_channel is not null or tgt_category is not null;

  use_city    := not target_mode and 'city'  = any(p_dims) and me.city is not null;
  use_state   := not target_mode and 'state' = any(p_dims) and me.state is not null;
  use_cat     := not target_mode and tgt_category is null and 'category' = any(p_dims) and cardinality(me.categories) > 0;
  use_band    := not target_mode and 'band'     = any(p_dims) and me.rev_band is not null;
  use_model   := not target_mode and 'model'    = any(p_dims) and cardinality(me.business_model) > 0;
  use_channel := not target_mode and tgt_channel is null and 'channel' = any(p_dims) and cardinality(me.channel_mix) > 0;
  if not (target_mode or trait_mode or use_city or use_state or use_cat or use_band or use_model or use_channel) then return; end if;

  drop table if exists _mm_out;
  create temp table _mm_out on commit drop as
  with my_gaps as (
    select tp.topic, tp.sort_score from digest.member_topic_profile(v_atid) tp
    where tp.is_working_on
  ), comp as (
    select e.at_member_id, e.topic, e.score
    from digest.member_expertise e
    join my_gaps g on g.topic = e.topic
    where coalesce(e.weakness_score, 0) = 0 and e.score > 0
  ), recent as (
    select r.recommended_at_id,
           bool_or(r.asker_at_id = v_atid and r.created_at >= now() - interval '30 days') as asker_repeat,
           max(r.created_at) filter (where r.asker_at_id = v_atid) as last_rec_at,
           count(*) filter (where r.created_at >= now() - interval '7 days') as global_7d
    from digest.olivia_recommendations r
    where r.created_at >= now() - interval '30 days'
    group by 1
  )
  select ma.at_member_id, ma.full_name, ma.city, ma.state,
    array_remove(array[
      case when target_mode and tgt_city is not null and ma.city ilike tgt_city
           then 'in ' || ma.city end,
      case when target_mode and tgt_state_label is not null
                and ma.state = any(tgt_states)
           then 'in ' || coalesce(ma.city || ', ', '') || ma.state
                || ' (' || tgt_state_label || ')' end,
      case when target_mode and tgt_countries is not null
                and digest.country_fold(ma.country) = any(tgt_countries)
           then 'in ' || coalesce(ma.city || ', ', '')
                || initcap(digest.country_fold(ma.country))
                || case when cardinality(tgt_countries) > 1
                        then ' (' || tgt_country_label || ')' else '' end end,
      case when target_mode and not (tgt_city is not null and ma.city ilike tgt_city)
                and not (tgt_state_label is not null and ma.state = any(tgt_states))
                and not (tgt_countries is not null and digest.country_fold(ma.country) = any(tgt_countries))
           then 'in ' || coalesce(ma.city || ' (' || ma.state || ')', ma.state) end,
      case when tgt_channel is not null and tgt_channel ilike '%tiktok%' and ma.tiktok_seller
           then 'sells on TikTok' end,
      case when tgt_channel is not null and not tgt_channel ilike '%tiktok%'
           then 'sells on ' || (select ch from unnest(ma.channel_mix) ch
                                where ch ilike '%' || tgt_channel || '%' limit 1) end,
      case when tgt_category is not null
           then 'category: ' || (select c from unnest(ma.categories) c
                                 where c ilike '%' || tgt_category || '%' limit 1) end,
      case when target_mode and ma.categories && me.categories then 'shared category: ' ||
        (select c from unnest(ma.categories) c where c = any(me.categories) limit 1) end,
      case when target_mode and ma.rev_band is not null and ma.rev_band = me.rev_band
           then 'similar revenue level' end,
      case when use_city  then 'same city' end,
      case when use_state then 'same state' end,
      case when use_cat and ma.categories && me.categories then 'shared category: ' ||
        (select c from unnest(ma.categories) c where c = any(me.categories) limit 1) end,
      case when use_band  then 'similar revenue level' end,
      case when use_model then 'similar business model' end,
      case when use_channel then 'also sells on ' ||
        (select ch from unnest(ma.channel_mix) ch where ch = any(me.channel_mix) limit 1) end,
      (select 'knows ' || c.topic from comp c
        where c.at_member_id = ma.at_member_id
        order by c.score desc limit 1)
    ], null) as reasons,
    row_number() over (order by
      (target_mode and tgt_city is not null and ma.city ilike tgt_city) desc,
      (target_mode and tgt_states is not null and ma.state = any(tgt_states)) desc,
      (target_mode and tgt_countries is not null and digest.country_fold(ma.country) = any(tgt_countries)) desc,
      (target_mode and (ma.categories && me.categories)) desc,
      (target_mode and ma.rev_band is not null and ma.rev_band = me.rev_band) desc,
      (lower(coalesce(ma.city, '')) = lower(coalesce(me.city, ''))) desc,
      coalesce(rc.asker_repeat, false) asc,
      -- LRU CYCLING (#95 catch 2): among repeats, the LONGEST-unseen name leads —
      -- an exhausted pool rotates instead of freezing
      rc.last_rec_at asc nulls first,
      (coalesce((select max(c.score) from comp c where c.at_member_id = ma.at_member_id), 0)
         - 0.5 * ln(1 + coalesce(rc.global_7d, 0))) desc,
      ma.full_name) as ord,
         count(*) over () as matched_total
  from digest.member_attributes ma
  left join recent rc on rc.recommended_at_id = ma.at_member_id
  where ma.at_member_id <> v_atid
    and ma.full_name is not null
    and ma.membership_status in ('Current Member','New Member','Pending Group Entrance','Current Member- Not Renewing')
    and (not target_mode or (
          (tgt_city is not null and ma.city ilike tgt_city)
          or (tgt_states is not null and ma.state = any(tgt_states))
          or (tgt_countries is not null and digest.country_fold(ma.country) = any(tgt_countries))))
    and (tgt_channel is null or (
          case when tgt_channel ilike '%tiktok%' then ma.tiktok_seller
               else exists (select 1 from unnest(ma.channel_mix) ch
                            where ch ilike '%' || tgt_channel || '%') end))
    and (tgt_category is null or exists (
          select 1 from unnest(ma.categories) c where c ilike '%' || tgt_category || '%'))
    and (not use_city    or lower(ma.city) = lower(me.city))
    and (not use_state   or lower(ma.state) = lower(me.state))
    and (not use_cat     or ma.categories && me.categories)
    and (not use_band    or ma.rev_band = me.rev_band)
    and (not use_model   or ma.business_model && me.business_model)
    and (not use_channel or ma.channel_mix && me.channel_mix)
  order by ord
  limit greatest(coalesce(p_limit, 10), 0);

  if not v_audit then
    -- log EVERY shown name's exposure moment; a repeat refreshes last_rec_at so
    -- the LRU cycle advances (the 24h dedupe would freeze the cycle - dropped
    -- here; gate/audits no longer write at all, so dedupe lost its job)
    insert into digest.olivia_recommendations (asker_at_id, recommended_at_id, lane)
    select v_atid, o.at_member_id, 'member_match' from _mm_out o;
  end if;

  return query
  select o.full_name, o.city, o.state, o.reasons, o.matched_total from _mm_out o order by o.ord;
end $function$
