-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.member_count(p_phone text, p_niche text DEFAULT NULL::text, p_city text DEFAULT NULL::text, p_state text DEFAULT NULL::text, p_chapter text DEFAULT NULL::text, p_band text DEFAULT NULL::text, p_main_only boolean DEFAULT false, p_group_by text DEFAULT NULL::text, p_at_member_id text DEFAULT NULL::text)
 RETURNS TABLE(total bigint, breakdown jsonb, breakdown_sum bigint, population bigint, note text)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare v_n int;
begin
  if p_at_member_id is not null then
    select count(*) into v_n from digest.member_attributes mz
      where mz.at_member_id = p_at_member_id and digest.is_active_member_status(mz.membership_status);
  else
    select count(*) into v_n from digest.members mz
      where mz.phone = p_phone and digest.is_active_member_status(mz.membership_status);
  end if;
  if v_n <> 1 then return; end if;

  return query
  with pop as (
    select ma.at_member_id, ma.city, ma.state, ma.rev_band,
           mp.at_fields->>'Chapter Affiliation' as chapter_raw
    from digest.member_attributes ma
    left join digest.member_profiles mp on mp.at_member_id = ma.at_member_id
    where ma.membership_status in
      ('Current Member','New Member','Pending Group Entrance','Current Member- Not Renewing')
  ),
  chap as (
    select p.at_member_id, trim(ch.one) as chapter
    from pop p cross join lateral regexp_split_to_table(
      coalesce(digest.attr_clean(p.chapter_raw), ''), ',[[:space:]]*') ch(one)
    where trim(ch.one) not in ('', 'No Chapter Affiliation', 'Chapter Leads')
  ),
  filt as (
    select p.at_member_id, p.city, p.state, p.rev_band
    from pop p
    where (p_city  is null or p.city  ilike digest.place_city(p_city))
      and (p_state is null or p.state ilike p_state)
      and (p_band  is null or p.rev_band ilike ('%' || p_band || '%'))
      and (p_chapter is null or exists (select 1 from chap c where c.at_member_id = p.at_member_id
             and c.chapter ilike ('%' || p_chapter || '%')))
      and (p_niche is null or exists (select 1 from digest.member_niches n
             where n.at_member_id = p.at_member_id and n.niche ilike ('%' || p_niche || '%')
               and (not p_main_only or n.is_main_niche)))
  ),
  bd as (
    select case lower(coalesce(p_group_by,''))
      when 'niche' then (select coalesce(jsonb_object_agg(t.k, t.n order by t.n desc), '{}'::jsonb)
        from (select n.niche as k, count(distinct n.at_member_id) as n from digest.member_niches n
              join filt f on f.at_member_id = n.at_member_id
              where (not p_main_only or n.is_main_niche) group by 1) t)
      when 'state' then (select coalesce(jsonb_object_agg(t.k, t.n order by t.n desc), '{}'::jsonb)
        from (select coalesce(nullif(trim(f.state),''),'(none on file)') as k, count(*) as n from filt f group by 1) t)
      when 'city' then (select coalesce(jsonb_object_agg(t.k, t.n order by t.n desc), '{}'::jsonb)
        from (select coalesce(nullif(trim(f.city),''),'(none on file)') as k, count(*) as n from filt f group by 1) t)
      when 'chapter' then (select coalesce(jsonb_object_agg(t.k, t.n order by t.n desc), '{}'::jsonb)
        from (select c.chapter as k, count(distinct c.at_member_id) as n from chap c
              join filt f on f.at_member_id = c.at_member_id group by 1) t)
      when 'band' then (select coalesce(jsonb_object_agg(t.k, t.n order by t.n desc), '{}'::jsonb)
        from (select coalesce(nullif(trim(f.rev_band),''),'(none on file)') as k, count(*) as n from filt f group by 1) t)
      when 'business_model' then (select coalesce(jsonb_object_agg(t.k, t.n order by t.n desc), '{}'::jsonb)
        from (select trim(bm.one) as k, count(distinct f.at_member_id) as n
              from filt f join digest.member_attributes ma2 on ma2.at_member_id = f.at_member_id
              cross join lateral unnest(coalesce(ma2.business_model, '{}'::text[])) bm(one)
              where trim(bm.one) <> '' group by 1) t)
      else '{}'::jsonb end as j
  )
  select
    (select count(*) from filt),
    (select j from bd),
    (select coalesce(sum(v.n::bigint),0)::bigint from bd, jsonb_each_text(bd.j) v(k,n) where v.n ~ '^\d+$'),
    (select count(*) from pop),
    'counts only — never names. total = DISTINCT members matching; breakdown_sum = the breakdown values added (can exceed total: members hold several chapters/niches). Use breakdown_sum when asked to total the list.'::text;
end $function$
