-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.member_topic_profile(p_atid text)
 RETURNS TABLE(topic text, words text[], is_strength boolean, is_working_on boolean, sort_score numeric)
 LANGUAGE sql
 STABLE
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  select e.topic,
         (select array_agg(w) from (
            select w from unnest(string_to_array(lower(regexp_replace(e.topic, '[^a-zA-Z0-9]+', ' ', 'g')), ' ')) w
            where length(w) >= 3 or w = 'ai') s) as words,
         e.score > 0 and e.score >= 2 * coalesce(e.weakness_score, 0) as is_strength,
         coalesce(e.weakness_score, 0) > 0 as is_working_on,
         greatest(coalesce(e.score, 0), coalesce(e.weakness_score, 0)) as sort_score
  from digest.member_expertise e
  where e.at_member_id = p_atid and (e.score > 0 or coalesce(e.weakness_score, 0) > 0)
$function$
