-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.member_card(p_phone text, p_member text)
 RETURNS TABLE(full_name text, city text, state text, country text, revenue_tier text, niche text, expertise text, about_me text, hobbies text, fun_fact text, facebook_link text, chapter text, channels text[], business_model text[], categories text[], shared_chats text[], membership_state text, joined date, left_date date)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare v_n int; v_my_chats text[];
begin
  if nullif(trim(coalesce(p_member,'')),'') is null then return; end if;
  select case when digest.resolve_asker(p_phone) is not null then 1 else 0 end into v_n;
  if v_n <> 1 then return; end if;
  select coalesce(m.channels_present, '{}') into v_my_chats
    from digest.member_identity m where m.at_member_id = digest.resolve_asker(p_phone) and digest.is_active_member_status(m.membership_status);

  return query
  with cand as (
    select ma.*, mp.at_fields, mp.join_date, mp.full_name as mp_name, tm.channels_present as t_chats,
           concat_ws(' ', ma.full_name, mp.full_name,
                     mp.at_fields->>'Full Name', mp.at_fields->>'Profile Name',
                     mp.at_fields->>'Profile Name Cleaned',
                     mp.at_fields->>'First Name', mp.at_fields->>'Last Name') as all_names,
           coalesce(nullif(trim(mp.at_fields->>'Full Name'), ''),
                    nullif(trim(mp.full_name), ''), ma.full_name) as best_name,
           case when ma.membership_status in ('Current Member','New Member','Pending Group Entrance',
                                             'Current Member- Not Renewing','Current Member- Paused',
                                             'Current Member- Soft Removed','Staff')
                then 'current' else 'past' end as m_state
      from digest.member_attributes ma
      join digest.member_profiles mp on mp.at_member_id = ma.at_member_id
      left join lateral (select m2.channels_present from digest.members m2
                          where m2.at_member_id = ma.at_member_id limit 1) tm on true
     where ma.membership_status in (
             'Current Member','New Member','Pending Group Entrance','Current Member- Not Renewing',
             'Current Member- Paused','Current Member- Soft Removed','Staff',
             'Removed - Canceled Membership','Removed - For Cause','Removed - Replaced with other Member')
  )
  select c.best_name, c.city, c.state,
         nullif(trim(c.country), ''),
         c.rev_band,
         digest.attr_clean(c.at_fields->>'Main Niche'),
         digest.attr_clean(c.at_fields->>'Area of Expertise'),
         digest.attr_clean(c.at_fields->>'About Me'),
         digest.attr_clean(c.at_fields->>'Hobbies'),
         digest.attr_clean(c.at_fields->>'Interesting / Fun fact'),
         case when c.at_fields->>'Facebook Profile Link' ilike '%facebook.com%'
              then c.at_fields->>'Facebook Profile Link' end,
         nullif(digest.attr_clean(c.at_fields->>'Chapter Affiliation'), 'No Chapter Affiliation'),
         (coalesce(c.channel_mix, '{}'::text[])
            || case when c.tiktok_seller then array['TikTok Shop'] else '{}'::text[] end),
         coalesce(c.business_model, '{}'::text[]),
         coalesce(c.categories, '{}'::text[]),
         (select coalesce(array_agg(x order by x), '{}')
            from (select unnest(v_my_chats) intersect
                  select unnest(coalesce(c.t_chats, '{}'))) s(x)),
         c.m_state,
         c.join_date,
         case when c.m_state = 'past'
                   and c.at_fields->>'Member Removed Date' ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
              then substring(c.at_fields->>'Member Removed Date' from 1 for 10)::date end
    from cand c
   where c.best_name is not null
     and (select bool_and(digest.name_fold(c.all_names) like '%'||digest.name_fold(w)||'%')
            from regexp_split_to_table(trim(p_member), '[[:space:]]+') w)
   order by (digest.name_fold(c.best_name) = digest.name_fold(trim(p_member))) desc,
            (c.m_state = 'current') desc,
            length(c.best_name) asc
   limit 3;

  if not found then
    return query
    with cand as (
      select ma.*, mp.at_fields, mp.join_date, tm.channels_present as t_chats,
             digest.name_fold(concat_ws(' ', ma.full_name, mp.full_name,
                       mp.at_fields->>'Full Name', mp.at_fields->>'Profile Name',
                       mp.at_fields->>'Profile Name Cleaned',
                       mp.at_fields->>'First Name', mp.at_fields->>'Last Name')) as folded_names,
             coalesce(nullif(trim(mp.at_fields->>'Full Name'), ''),
                      nullif(trim(mp.full_name), ''), ma.full_name) as best_name,
             case when ma.membership_status in ('Current Member','New Member','Pending Group Entrance',
                                               'Current Member- Not Renewing','Current Member- Paused',
                                               'Current Member- Soft Removed','Staff')
                  then 'current' else 'past' end as m_state
        from digest.member_attributes ma
        join digest.member_profiles mp on mp.at_member_id = ma.at_member_id
        left join lateral (select m2.channels_present from digest.members m2
                            where m2.at_member_id = ma.at_member_id limit 1) tm on true
       where ma.membership_status in (
               'Current Member','New Member','Pending Group Entrance','Current Member- Not Renewing',
               'Current Member- Paused','Current Member- Soft Removed','Staff',
               'Removed - Canceled Membership','Removed - For Cause','Removed - Replaced with other Member')
    )
    select c.best_name, c.city, c.state,
           nullif(trim(c.country), ''),
           c.rev_band,
           digest.attr_clean(c.at_fields->>'Main Niche'),
           digest.attr_clean(c.at_fields->>'Area of Expertise'),
           digest.attr_clean(c.at_fields->>'About Me'),
           digest.attr_clean(c.at_fields->>'Hobbies'),
           digest.attr_clean(c.at_fields->>'Interesting / Fun fact'),
           case when c.at_fields->>'Facebook Profile Link' ilike '%facebook.com%'
                then c.at_fields->>'Facebook Profile Link' end,
           nullif(digest.attr_clean(c.at_fields->>'Chapter Affiliation'), 'No Chapter Affiliation'),
           (coalesce(c.channel_mix, '{}'::text[])
              || case when c.tiktok_seller then array['TikTok Shop'] else '{}'::text[] end),
           coalesce(c.business_model, '{}'::text[]),
           coalesce(c.categories, '{}'::text[]),
           (select coalesce(array_agg(x order by x), '{}')
              from (select unnest(v_my_chats) intersect
                    select unnest(coalesce(c.t_chats, '{}'))) s(x)),
           c.m_state,
           c.join_date,
           case when c.m_state = 'past'
                     and c.at_fields->>'Member Removed Date' ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
                then substring(c.at_fields->>'Member Removed Date' from 1 for 10)::date end
      from cand c
     where c.best_name is not null
       and extensions.word_similarity(digest.name_fold(trim(p_member)), c.folded_names) > 0.62
     order by extensions.word_similarity(digest.name_fold(trim(p_member)), c.folded_names) desc,
              (c.m_state = 'current') desc,
              length(c.best_name) asc
     limit 3;
  end if;
end $function$
