-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.member_link(p_at_member_id text)
 RETURNS text
 LANGUAGE sql
 STABLE
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  with raw as (
    select coalesce(
      (select case when mp.at_fields->>'Facebook Profile Link' ilike '%facebook.com%'
                   then trim(mp.at_fields->>'Facebook Profile Link') end
         from digest.member_profiles mp where mp.at_member_id = p_at_member_id limit 1),
      (select case when nullif(trim(f.vanity_url),'') is not null then trim(f.vanity_url)
                   when nullif(trim(f.fb_uid),'') is not null then 'https://www.facebook.com/profile.php?id=' || trim(f.fb_uid) end
         from digest.fb_member_map f
        where f.at_member_id = p_at_member_id
        order by f.is_primary desc nulls last, f.synced_at desc nulls last
        limit 1)
    ) as v
  )
  select case
    when v is null then null
    when v ~* '^(https?://)?(www\.|m\.|web\.|mobile\.)?facebook\.com/'
      then 'https://www.facebook.com/' || regexp_replace(v, '^(https?://)?(www\.|m\.|web\.|mobile\.)?facebook\.com/', '', 'i')
    else null   -- anything that is not a Facebook profile is not a member link
  end
  from raw
$function$
