-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.member_alias_ids(p_member text)
 RETURNS text[]
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  with me as (select nullif(btrim(p_member), '') as at_member_id),
  my_emails as (
    select distinct lower(btrim(a.email)) as email
      from digest.member_email_alias a, me
     where a.at_member_id = me.at_member_id
       and nullif(btrim(a.email), '') is not null
  )
  select array(
    select at_member_id from me where at_member_id is not null
    union
    select distinct a.at_member_id
      from digest.member_email_alias a
     where lower(btrim(a.email)) in (select email from my_emails)
  )
$function$
