-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.member_card_v2(p_phone text, p_member text)
 RETURNS TABLE(full_name text, city text, state text, country text, revenue_tier text, niche text, expertise text, about_me text, hobbies text, fun_fact text, facebook_link text, chapter text, channels text[], business_model text[], categories text[], shared_chats text[], membership_state text, joined date, left_date date)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare v_n int;
begin
  -- same doors as v1: no name, or an unresolvable/inactive asker → nothing at all
  if nullif(trim(coalesce(p_member,'')),'') is null then return; end if;
  select count(*) into v_n from digest.member_identity m
   where m.at_member_id = digest.resolve_asker(p_phone) and digest.is_active_member_status(m.membership_status);
  if v_n <> 1 then return; end if;

  return query select * from digest.member_card(p_phone, p_member);

  if not found then
    return query
    select trim(p_member), null::text, null::text, null::text, null::text,
           null::text, null::text, null::text, null::text, null::text,
           null::text, null::text, null::text[], null::text[],
           null::text[], null::text[], 'not_found'::text,
           null::date, null::date;
  end if;
end $function$
