-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.member_event_url(p_link text, p_fallback text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  select case
    when p_link is null or trim(p_link) = '' then p_fallback
    when p_link !~* '/admin/' then p_link
    when p_link ~* 'id=[0-9a-f]{24}' then
      'https://app.mds.co/events/u/' || substring(p_link from 'id=([0-9a-f]{24})')
    else p_fallback
  end
$function$
