-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.member_display_name(p_at_member_id text)
 RETURNS text
 LANGUAGE sql
 STABLE
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  select coalesce(
           nullif(trim(p.at_fields->>'Profile Name Cleaned'), ''),
           nullif(trim(p.full_name), ''))
  from digest.member_profiles p
  where p.at_member_id = p_at_member_id
$function$
