-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.member_video_url(p_video_id text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  select case
    when p_video_id ~ '^[0-9a-f]{24}$'
      then 'https://app.mds.co/videos/' || p_video_id
    else null
  end
$function$
