-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.meta_webhook_config()
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'vault', 'public', 'pg_temp'
AS $function$
declare
  v_secret text;
  v_relay text;
  v_enforce text;
begin
  select decrypted_secret into v_secret
    from vault.decrypted_secrets where name = 'META_APP_SECRET' limit 1;
  select decrypted_secret into v_relay
    from vault.decrypted_secrets where name = 'OLIVIA_RELAY_SECRET' limit 1;
  select v into v_enforce
    from digest.olivia_alarm_config where k = 'meta_webhook_enforce';

  return jsonb_build_object(
    'secret', coalesce(v_secret, ''),
    'relay_secret', coalesce(v_relay, ''),
    'enforce', coalesce(lower(btrim(v_enforce)) in ('1', 'true', 'yes'), false)
  );
end;
$function$
