-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.meta_signature_ok(p_raw text, p_signature text)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'vault', 'public', 'pg_temp'
AS $function$
declare
  v_secret text;
  v_sent   text;
  v_expect text;
  v_nonce  text;
begin
  -- Fail closed on a missing secret. A check that disables itself when it is
  -- misconfigured is not a check.
  select decrypted_secret into v_secret
    from vault.decrypted_secrets where name = 'META_APP_SECRET' limit 1;
  if v_secret is null or btrim(v_secret) = '' then
    return jsonb_build_object('ok', false, 'reason', 'missing_secret');
  end if;

  if p_raw is null then
    return jsonb_build_object('ok', false, 'reason', 'missing_body');
  end if;

  if p_signature is null or p_signature = '' then
    return jsonb_build_object('ok', false, 'reason', 'missing_signature');
  end if;

  if left(p_signature, 7) <> 'sha256=' then
    return jsonb_build_object('ok', false, 'reason', 'bad_format');
  end if;

  v_sent := lower(substr(p_signature, 8));
  if v_sent !~ '^[0-9a-f]{64}$' then
    return jsonb_build_object('ok', false, 'reason', 'bad_format');
  end if;

  v_expect := encode(extensions.hmac(p_raw, v_secret, 'sha256'), 'hex');

  -- Double-HMAC compare. Plain text equality in Postgres short-circuits on the first
  -- differing byte, which leaks how much of a guess was right. Hashing both sides
  -- under a fresh random key first makes the comparison carry no usable timing.
  v_nonce := encode(extensions.gen_random_bytes(32), 'hex');
  if extensions.hmac(v_expect, v_nonce, 'sha256') = extensions.hmac(v_sent, v_nonce, 'sha256') then
    return jsonb_build_object('ok', true);
  end if;

  return jsonb_build_object('ok', false, 'reason', 'mismatch');
end;
$function$
