-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.meta_webhook_record(p_reason text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
begin
  insert into digest.meta_webhook_verdicts (day, reason, n)
  values (current_date, coalesce(nullif(btrim(p_reason), ''), 'unknown'), 1)
  on conflict (day, reason) do update
    set n = digest.meta_webhook_verdicts.n + 1,
        last_at = now();
end;
$function$
