-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.multi_source(p_phone text, p_query text DEFAULT NULL::text, p_terms text[] DEFAULT '{}'::text[], p_city text DEFAULT NULL::text, p_want text[] DEFAULT ARRAY['partners'::text, 'members'::text, 'events'::text, 'chats'::text, 'fb'::text, 'videos'::text])
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare v_n int; v_atid text; result jsonb := '{}'::jsonb; v_q text;
begin
  select case when digest.resolve_asker(p_phone) is not null then 1 else 0 end into v_n;
  if v_n <> 1 then return '{}'::jsonb; end if;                 -- fail closed
  select digest.resolve_asker(p_phone) into v_atid;
  if v_atid is null then return '{}'::jsonb; end if;
  v_q := nullif(trim(coalesce(p_query, array_to_string(p_terms, ' '))), '');

  if 'partners' = any(p_want) and v_q is not null then
    result := result || jsonb_build_object('partners', coalesce((
      select jsonb_agg(to_jsonb(t)) from (
        select name, offer_value, description_snippet, rating_avg, review_count, partner_url
        from digest.partner_lookup(p_phone, v_q, 4)) t), '[]'::jsonb));
  end if;

  -- MEMBERS. Two modes, both write the 'members' section:
  --  'members_nearby' = a NETWORKING / meet-people ask -> people NEAR the asker
  --    (member_match is asker-relative: it resolves the asker's own state internally).
  --    The match reason is surfaced under the 'expertise' key ON PURPOSE so the existing
  --    Build Prompt multi 'members' renderer shows it with zero workflow changes.
  --  'members' = a TOPIC ask -> people who KNOW the topic (expertise_search).
  if 'members_nearby' = any(p_want) then
    result := result || jsonb_build_object('members', coalesce((
      select jsonb_agg(to_jsonb(t)) from (
        select full_name, city, state,
               coalesce(nullif(array_to_string(reasons, ', '), ''), 'near you') as expertise
        from digest.member_match(p_phone, ARRAY['state'], 6)) t), '[]'::jsonb));
  elsif 'members' = any(p_want) and v_q is not null then
    result := result || jsonb_build_object('members', coalesce((
      select jsonb_agg(to_jsonb(t)) from (
        select full_name, city, state, expertise, niche
        from digest.expertise_search(p_phone, v_q, 6)) t), '[]'::jsonb));
  end if;

  if 'events' = any(p_want) then
    result := result || jsonb_build_object('events', coalesce((
      select jsonb_agg(to_jsonb(t)) from (
        select event_name, start_display, event_type, city, phase, can_register, reg_link
        from digest.event_lookup(p_phone, null, p_city, null, false, 6)) t), '[]'::jsonb));
  end if;

  if 'chats' = any(p_want) and array_length(p_terms, 1) >= 1 then
    result := result || jsonb_build_object('chats', coalesce((
      select jsonb_agg(jsonb_build_object(
               'chat', cs.meta->>'chat_name', 'who', cs.meta->>'sender_name',
               'tldr', cs.tl_dr, 'text', left(cs.body, 240), 'at', cs.occurred_at))
      from digest.content_search_v2(p_phone, p_terms, array['wa_digest','wa_message'],
                                 null, null, null, 20, false) cs), '[]'::jsonb));
  end if;

  -- #8: FACEBOOK joins the fan-out (posts + comments, same gated content_search)
  if 'fb' = any(p_want) and array_length(p_terms, 1) >= 1 then
    result := result || jsonb_build_object('fb', coalesce((
      select jsonb_agg(jsonb_build_object(
               'who', cs.meta->>'author_name', 'kind', cs.kind,
               'tldr', cs.tl_dr, 'text', left(cs.body, 240), 'at', cs.occurred_at,
               'url', cs.url))
      from digest.content_search_v2(p_phone, p_terms, array['fb_post','fb_comment'],
                                 null, null, null, 12, false) cs), '[]'::jsonb));
  end if;

  -- #8: VIDEOS join the fan-out (restriction markers travel in description_snippet)
  if 'videos' = any(p_want) and v_q is not null then
    result := result || jsonb_build_object('videos', coalesce((
      select jsonb_agg(to_jsonb(t)) from (
        select vs.title, vs.call_type, vs.description_snippet, vs.published_at,
               vs.video_url, vs.is_restricted
        from digest.video_search(p_phone => p_phone, p_query => v_q, p_limit => 4) vs) t), '[]'::jsonb));
  end if;

  return result;
end $function$
