-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.my_form_answers(p_phone text, p_form_id text DEFAULT NULL::text)
 RETURNS TABLE(form_name text, submitted_at timestamp with time zone, ref text, question text, answer text)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare v_n int; v_atid text;
begin
  select count(*) into v_n from digest.member_identity m
   where m.at_member_id = digest.resolve_asker(p_phone) and digest.is_active_member_status(m.membership_status);
  if v_n <> 1 then return; end if;
  select digest.resolve_asker(p_phone) into v_atid;
  if v_atid is null then return; end if;

  return query
  select fr.form_name, fr.submitted_at, a.key,
         a.value->>'q',
         case when jsonb_typeof(a.value->'v') in ('array','object')
              then (select string_agg(x.e, ', ') from (
                      select jsonb_array_elements_text(a.value->'v') e) x)
              else a.value->>'v' end
  from digest.form_responses fr
  join digest.form_scope sc on sc.form_id = fr.form_id and sc.scope = 'profile'
  cross join lateral jsonb_each(fr.answers) a
  where fr.member_at_id = v_atid
    and (p_form_id is null or fr.form_id = p_form_id)
    and a.key not in ('email','phone','full_name')
  order by fr.submitted_at desc, a.key
  limit 200;
end $function$
