-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.name_fold(t text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  select lower(translate(coalesce(t,''),
    'ÁÀÂÄÃÅáàâäãåÉÈÊËéèêëÍÌÎÏíìîïÓÒÔÖÕóòôöõÚÙÛÜúùûüÑñÇçŠšŽžŸÿ',
    'AAAAAAaaaaaaEEEEeeeeIIIIiiiiOOOOOoooooUUUUuuuuNnCcSsZzYy'))
$function$
