-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.olivia_alarm_fire(p_kind text, p_firing boolean, p_detail text, p_token text, p_channel text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'digest', 'net', 'extensions', 'pg_temp'
AS $function$
declare
  st digest.olivia_alarm_state;
  v_msg text;
  v_age interval;
  v_gap interval;
  v_since text;
begin
  select * into st from digest.olivia_alarm_state where kind = p_kind;
  if st.kind is null then
    insert into digest.olivia_alarm_state(kind) values (p_kind)
    on conflict (kind) do nothing;
    select * into st from digest.olivia_alarm_state where kind = p_kind;
  end if;

  if p_firing then
    v_age := now() - coalesce(st.last_ok_at, now());
    v_gap := case
               when v_age < interval '2 hours'  then interval '30 minutes'
               when v_age < interval '12 hours' then interval '2 hours'
               when v_age < interval '48 hours' then interval '6 hours'
               else interval '24 hours'
             end;
    if (not coalesce(st.is_firing, false))
       or st.last_alert_at is null or st.last_alert_at < now() - v_gap then
      -- Say how long it has been down and when the next repeat is due, so the message carries
      -- the information the repetition used to imply.
      v_since := case
                   when st.last_ok_at is null then 'unknown'
                   else to_char(v_age, 'DD"d" HH24"h" MI"m"')
                 end;
      v_msg := '🚨 *Olivia alarm — ' || p_kind || '* ' || coalesce(p_detail,'') ||
               case when coalesce(st.is_firing,false)
                    then ' (still down for ' || v_since || ' — next check-in in ' || v_gap || ')'
                    else '' end;
      perform net.http_post(
        url := 'https://slack.com/api/chat.postMessage',
        headers := jsonb_build_object('Authorization', 'Bearer ' || p_token,
                                      'Content-Type', 'application/json'),
        body := jsonb_build_object('channel', p_channel, 'text', v_msg));
      update digest.olivia_alarm_state
        set is_firing = true, last_alert_at = now(), detail = p_detail where kind = p_kind;
    else
      update digest.olivia_alarm_state set detail = p_detail where kind = p_kind;
    end if;
  else
    if coalesce(st.is_firing, false) then
      perform net.http_post(
        url := 'https://slack.com/api/chat.postMessage',
        headers := jsonb_build_object('Authorization', 'Bearer ' || p_token,
                                      'Content-Type', 'application/json'),
        body := jsonb_build_object('channel', p_channel,
                                   'text', '✅ *Olivia recovered — ' || p_kind || '*'));
    end if;
    update digest.olivia_alarm_state
      set is_firing = false, last_ok_at = now() where kind = p_kind;
  end if;
end $function$
