-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.olivia_broadcast_audience()
 RETURNS TABLE(phone text, full_name text, turns bigint, last_use date)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  select u.phone, mm.full_name, u.turns, u.last_use
  from (
    select m.phone, count(*) turns, max(m.created_at)::date last_use
    from digest.olivia_messages m
    where m.role = 'member' and m.route not in ('stop','muted')
    group by m.phone
  ) u
  join digest.members mm on mm.phone = u.phone
  where mm.olivia_optout_at is null
    and digest.is_active_member_status(mm.membership_status)
    and u.phone <> '17866578153'          -- the probe number: its thread is test traffic
  order by u.turns desc, mm.full_name
$function$
