-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.olivia_front_door_v2(p_phone text, p_user_id text DEFAULT NULL::text)
 RETURNS TABLE(phone text, full_name text, name text, membership_status text, at_member_id text, airtable_id text, channels_present text[], olivia_welcomed_at timestamp with time zone, olivia_optout_at timestamp with time zone)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  -- 1. the normal path: a real phone number arrived.
  select * from digest.olivia_front_door(p_phone)
   where p_phone is not null and p_phone <> ''
  union all
  -- 2. no phone (or a phone nobody owns): fall back to the WhatsApp opaque id.
  select f.* from digest.olivia_front_door(
    (select w.phone from digest.member_wa_ids w where w.wa_user_id = p_user_id)
  ) f
  where p_user_id is not null
    and not exists (select 1 from digest.olivia_front_door(p_phone)
                     where p_phone is not null and p_phone <> '')
$function$
