-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.olivia_health_check()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'digest', 'net', 'extensions', 'pg_temp'
AS $function$
declare
  v_token text; v_channel text; v_n int;
  v_prev bigint; v_status int; v_timed boolean; v_req bigint; v_stale text;
  v_dups text;
begin
  select v into v_token from digest.olivia_alarm_config where k = 'slack_token';
  select v into v_channel from digest.olivia_alarm_config where k = 'slack_channel';
  if v_token is null or v_channel is null then return; end if;

  insert into digest.olivia_alarm_config(k, v) values ('last_tick_at', now()::text)
  on conflict (k) do update set v = now()::text;

  begin
    select count(*) into v_n from digest.olivia_messages
    where role = 'olivia' and created_at > now() - interval '10 minutes'
      and text like 'Sorry%could not generate%'
      and phone <> '17866578153' and coalesce(wamid,'') not like '%SELFTEST%'
      and coalesce(wamid,'') not like '%ALARMPROBE%';
    perform digest.olivia_alarm_fire('members-getting-failure-text', v_n > 0,
      v_n || ' failure reply(ies) reached members in the last 10 min', v_token, v_channel);
  exception when others then null; end;

  begin
    select count(*) into v_n from digest.olivia_sends
    where conversation_origin = 'relay_maintenance'
      and greatest(coalesce(first_seen_at,'epoch'), coalesce(status_at,'epoch'), coalesce(updated_at,'epoch'))
          > now() - interval '10 minutes';
    perform digest.olivia_alarm_fire('n8n-workflow-down', v_n > 0,
      v_n || ' relay maintenance marker(s) in the last 10 min (Meta callbacks arriving, n8n not answering)',
      v_token, v_channel);
  exception when others then null; end;

  begin
    select ping_request_id into v_prev from digest.olivia_alarm_state where kind = 'webhook-ping';
    if v_prev is not null then
      select status_code, timed_out into v_status, v_timed
      from net._http_response where id = v_prev;
      perform digest.olivia_alarm_fire('webhook-ping',
        (v_status is distinct from 200) or coalesce(v_timed, false),
        'prod webhook probe: status=' || coalesce(v_status::text, 'no-response') ||
        case when coalesce(v_timed,false) then ' (timed out)' else '' end,
        v_token, v_channel);
    end if;
    v_req := net.http_post(
      url := 'https://mdsco.app.n8n.cloud/webhook/olivia-wa-live',
      headers := '{"Content-Type":"application/json"}'::jsonb,
      body := '{"object":"whatsapp_business_account","entry":[{"id":"healthping","changes":[{"value":{"messaging_product":"whatsapp","statuses":[{"id":"wamid.HEALTHPING","status":"delivered","recipient_id":"10000000000"}]},"field":"messages"}]}]}'::jsonb,
      timeout_milliseconds := 15000);
    insert into digest.olivia_alarm_state(kind, ping_request_id) values ('webhook-ping', v_req)
    on conflict (kind) do update set ping_request_id = v_req;
  exception when others then null; end;

  -- signal 4 (#15): any expected nightly job stale beyond its max_age
  begin
    select string_agg(job || ' (' ||
             coalesce('last ok ' || to_char(last_success_at, 'Mon DD HH24:MI'), 'NEVER') || ')', ', ')
      into v_stale
    from digest.olivia_job_heartbeats
    where last_success_at is null or last_success_at < now() - make_interval(hours => max_age_hours);
    perform digest.olivia_alarm_fire('nightly-job-stale', v_stale is not null,
      'stale derivation job(s): ' || coalesce(v_stale, ''), v_token, v_channel);
  exception when others then null; end;

  -- signal 5 (#60): duplicate FUTURE display identities in the events catalog
  begin
    select string_agg(nm || ' @ ' || to_char(st, 'Mon DD') || ' ×' || c, ', ')
      into v_dups
    from (
      select coalesce(c.app_title, c.name) nm, coalesce(c.app_starts_at, c.start_at) st, count(*) c
      from digest.events_catalog c
      where coalesce(c.app_starts_at, c.start_at) >= now()
      group by 1, 2 having count(*) > 1
    ) d;
    perform digest.olivia_alarm_fire('catalog-duplicate-event', v_dups is not null,
      'two catalog rows share one display name+start (app-event mis-link?): ' || coalesce(v_dups, ''),
      v_token, v_channel);
  exception when others then null; end;

  -- signal 6 (#77): the identity phone index is refreshed by pg_cron every 15 min; if that
  -- stops, active members silently lose access instead of anything visibly breaking.
  begin
    select to_char(max(refreshed_at), 'Mon DD HH24:MI') into v_stale
      from digest.member_phone_index;
    perform digest.olivia_alarm_fire('phone-index-stale',
      not exists (select 1 from digest.member_phone_index
                   where refreshed_at > now() - interval '60 minutes'),
      'member_phone_index has not refreshed since ' || coalesce(v_stale, 'NEVER') ||
      ' — active members not in a WA chat cannot be identified', v_token, v_channel);
  exception when others then null; end;

  -- signal 7 (#75): a reaction reached the raw store but never became a feedback row —
  -- the parse path dropped it. 15-min grace covers in-flight events; 24h lookback keeps
  -- the jsonb extraction on a handful of rows.
  begin
    select count(*) into v_n
    from digest.olivia_webhook_events e
    where e.msg_type = 'reaction'
      and e.received_at between now() - interval '24 hours' and now() - interval '15 minutes'
      and not exists (
        select 1 from digest.olivia_feedback f
        where f.wamid = e.payload->'entry'->0->'changes'->0->'value'->'messages'->0->'reaction'->>'message_id'
          and f.phone = e.from_phone);
    perform digest.olivia_alarm_fire('reaction-parse-gap', v_n > 0,
      v_n || ' reaction(s) hit the raw store in the last 24h with no olivia_feedback row — the parse path is dropping them',
      v_token, v_channel);
  exception when others then null; end;

  -- signal 8 (#75): no member reaction has ARRIVED in 14 days. 👍/👎 is the only free teaching
  -- signal; before the raw store, six silent weeks were invisible. Quiet until the store has
  -- 14 days of history, so a fresh deploy cannot page.
  begin
    perform digest.olivia_alarm_fire('reaction-silence-14d',
      exists (select 1 from digest.olivia_webhook_events
               where received_at < now() - interval '14 days')
      and not exists (
        select 1 from digest.olivia_webhook_events
        where msg_type = 'reaction'
          and coalesce(wamid,'') not like '%SELFTEST%'
          and payload::text not like '%SELFTEST%'
          and received_at > now() - interval '14 days'),
      'no member reaction has arrived in 14+ days — check the Meta webhook subscription and the reaction path',
      v_token, v_channel);
  exception when others then null; end;
end $function$
