-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.olivia_front_door(p_phone text)
 RETURNS TABLE(phone text, full_name text, name text, membership_status text, at_member_id text, airtable_id text, channels_present text[], olivia_welcomed_at timestamp with time zone, olivia_optout_at timestamp with time zone)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  select m.phone, m.full_name, m.name, m.membership_status, m.at_member_id, m.airtable_id,
         m.channels_present, m.olivia_welcomed_at, m.olivia_optout_at
  from digest.members m
  where m.phone = p_phone
  union all
  select i.phone, i.full_name, i.name, i.membership_status, i.at_member_id, i.airtable_id,
         i.channels_present, mw.olivia_welcomed_at, mw.olivia_optout_at
  from digest.member_identity i
  left join digest.members mw on mw.at_member_id = i.at_member_id
  where not exists (select 1 from digest.members m2 where m2.phone = p_phone)
    and digest.resolve_asker(p_phone) is not null
    and i.at_member_id = digest.resolve_asker(p_phone)
$function$
