-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.olivia_touch(p_phone text)
 RETURNS void
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
  update digest.members
     set olivia_interactions = coalesce(olivia_interactions, 0) + 1,
         olivia_last_used_at = now()
   where phone = p_phone;
$function$
