-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.partner_lookup(p_phone text, p_query text DEFAULT NULL::text, p_limit integer DEFAULT 8, p_embedding text DEFAULT NULL::text, p_at_member_id text DEFAULT NULL::text, p_order text DEFAULT NULL::text)
 RETURNS TABLE(name text, offer_value text, description_snippet text, categories text[], rating_avg numeric, review_count integer, claim_count integer, featured boolean, fresh_deal boolean, partner_url text, reviews_sample jsonb, matched_rank real)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare
  v_n int; v_atid text; v_q tsquery; v_strict tsquery; v_vec extensions.vector(1024);
  v_order text;
begin
  if p_at_member_id is not null then
    select count(*) into v_n from digest.member_attributes mz where mz.at_member_id = p_at_member_id and digest.is_active_member_status(mz.membership_status);
  else
    select count(*) into v_n from digest.member_identity mz where mz.at_member_id = digest.resolve_asker(p_phone) and digest.is_active_member_status(mz.membership_status);
  end if;
  if v_n < 1 then return; end if;
  select case when p_at_member_id is not null
              then (select a.at_member_id from digest.member_attributes a
                     where a.at_member_id = p_at_member_id
                       and digest.is_active_member_status(a.membership_status))
              else digest.resolve_asker(p_phone) end into v_atid;
  if p_at_member_id is not null and v_atid is null then v_atid := p_at_member_id; end if;
  if v_atid is null then return; end if;

  -- #56: ranking mode — the metric orders the WHOLE directory; search is bypassed.
  v_order := lower(nullif(trim(coalesce(p_order,'')), ''));
  if v_order is not null and v_order not in ('reviews','rating','claims') then v_order := null; end if;
  if v_order is not null then
    return query
    with pool as (
      select distinct on (pc.name)
             pc.partner_id, pc.name as pname, pc.offer_value as poffer, pc.description_text,
             pc.category_names, pc.rating_avg as prating, pc.review_count as prevs,
             pc.claim_count as pclaims, pc.featured as pfeat, pc.fresh_deal as pfresh
      from digest.partners_catalog pc
      where pc.status = 'published' and pc.access_restriction = 'public'
      order by pc.name, pc.claim_count desc, pc.app_created_at desc
    )
    select h.pname, h.poffer, left(h.description_text, 700), h.category_names,
           h.prating, h.prevs, h.pclaims, h.pfeat, h.pfresh,
           digest.member_partner_url(h.partner_id),
           rv.sample, null::real
    from pool h
    left join lateral (
      select jsonb_agg(jsonb_build_object('rating', r.rating, 'text', r.review_text)
                       order by r.reviewed_at desc) as sample
      from (select pr.rating, pr.review_text, pr.reviewed_at
            from digest.partner_reviews pr
            where pr.partner_id = h.partner_id and pr.review_text is not null
            order by pr.reviewed_at desc limit 3) r
    ) rv on true
    order by
      case v_order when 'reviews' then coalesce(h.prevs, 0)
                   when 'claims' then coalesce(h.pclaims, 0)
                   else 0 end desc,
      -- rating mode: average first, but ties/thin data break on volume so one 5.0★ review
      -- never outranks 4.8★ × 48
      case when v_order = 'rating' then coalesce(h.prating, 0) else 0 end desc,
      coalesce(h.prevs, 0) desc, h.pname
    limit least(greatest(coalesce(p_limit, 8), 1), 20);
    return;
  end if;

  if nullif(trim(coalesce(p_query, '')), '') is not null then
    v_q := digest.expertise_query(p_query);
    v_strict := plainto_tsquery('english', p_query);
    if v_strict::text = '' then v_strict := null; end if;
  end if;
  if p_embedding is not null then
    begin
      v_vec := p_embedding::extensions.vector(1024);
    exception when others then
      v_vec := null;
    end;
  end if;

  return query
  with pool as (
    select distinct on (pc.name)
           pc.partner_id, pc.name as pname, pc.offer_value as poffer, pc.description_text,
           pc.category_names, pc.rating_avg as prating, pc.review_count as prevs,
           pc.claim_count as pclaims, pc.featured as pfeat, pc.fresh_deal as pfresh,
           pc.search_tsv as ptsv, pc.embedding as pemb
    from digest.partners_catalog pc
    where pc.status = 'published'
      and pc.access_restriction = 'public'
    order by pc.name, pc.claim_count desc, pc.app_created_at desc
  ), kw as (
    select p.partner_id,
           (ts_rank(p.ptsv, v_q)
            + case when v_strict is not null and p.ptsv @@ v_strict
                   then 3.0::real * ts_rank(p.ptsv, v_strict) else 0.0::real end) as rnk,
           row_number() over (order by
             (ts_rank(p.ptsv, v_q)
              + case when v_strict is not null and p.ptsv @@ v_strict
                     then 3.0::real * ts_rank(p.ptsv, v_strict) else 0.0::real end) desc,
             p.pfeat desc, p.pfresh desc, p.pclaims desc, p.pname) as r
    from pool p
    where v_q is not null and p.ptsv @@ v_q
  ), vec as (
    select p.partner_id,
           row_number() over (order by p.pemb operator(extensions.<=>) v_vec, p.pname) as r
    from pool p
    where v_vec is not null and p.pemb is not null
    order by p.pemb operator(extensions.<=>) v_vec
    limit 25
  ), sel as (
    select p.*, coalesce(k.rnk, 0.0::real) as kw_rnk,
           (coalesce(1.0/(60+k.r), 0) + coalesce(1.0/(60+x.r), 0))::real as rrf
    from pool p
    left join kw k on k.partner_id = p.partner_id
    left join vec x on x.partner_id = p.partner_id
    where (v_q is null and v_vec is null)
       or k.partner_id is not null
       or x.partner_id is not null
  )
  select h.pname,
         h.poffer,
         left(h.description_text, 700) as description_snippet,
         h.category_names as categories,
         h.prating,
         h.prevs,
         h.pclaims,
         h.pfeat,
         h.pfresh,
         digest.member_partner_url(h.partner_id) as partner_url,
         rv.sample as reviews_sample,
         case when v_vec is null then h.kw_rnk else h.rrf end as matched_rank
  from sel h
  left join lateral (
    select jsonb_agg(jsonb_build_object('rating', r.rating, 'text', r.review_text)
                     order by r.reviewed_at desc) as sample
    from (
      select pr.rating, pr.review_text, pr.reviewed_at
      from digest.partner_reviews pr
      where pr.partner_id = h.partner_id
        and pr.review_text is not null
      order by pr.reviewed_at desc
      limit 3
    ) r
  ) rv on true
  order by h.rrf desc, h.kw_rnk desc, h.pfeat desc, h.pfresh desc, h.pclaims desc, h.pname
  limit least(greatest(coalesce(p_limit, 8), 1), 20);
end $function$
