-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.partners_embed_invalidate()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  if (new.name, new.description_text, new.offer_value, new.category_names)
     is distinct from (old.name, old.description_text, old.offer_value, old.category_names) then
    new.embedding := null;
  end if;
  return new;
end $function$
