-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.partner_lookup_v2(p_phone text, p_query text DEFAULT NULL::text, p_limit integer DEFAULT 8, p_embedding text DEFAULT NULL::text, p_at_member_id text DEFAULT NULL::text, p_order text DEFAULT NULL::text)
 RETURNS TABLE(name text, offer_value text, description_snippet text, categories text[], rating_avg numeric, review_count integer, claim_count integer, featured boolean, fresh_deal boolean, partner_url text, reviews_sample jsonb, matched_rank real, fit_reason text, strength_note text)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare v_atid text;
begin
  select case when p_at_member_id is not null
              then (select a.at_member_id from digest.member_attributes a
                     where a.at_member_id = p_at_member_id
                       and digest.is_active_member_status(a.membership_status))
              else digest.resolve_asker(p_phone) end into v_atid;
  if v_atid is null then v_atid := p_at_member_id; end if;

  return query
  with v1 as (
    select t.* from digest.partner_lookup(p_phone, p_query, p_limit, p_embedding, p_at_member_id, p_order)
      with ordinality as t(name, offer_value, description_snippet, categories, rating_avg,
                           review_count, claim_count, featured, fresh_deal, partner_url,
                           reviews_sample, matched_rank, ord)
  ), me as (
    select tp.topic, tp.is_working_on, tp.sort_score from digest.member_topic_profile(v_atid) tp
  ), dos as (
    -- #59: ONE dossier per row, joined back by ord, never by name (12 partner names repeat).
    select v.ord, ed.strength_note snote, coalesce(ed.weak_signal, 0) wsig, f.fit, f.topics
    from v1 v
    left join lateral (
      select d.* from digest.entity_dossier d
      where d.kind = 'partner' and d.name = v.name
      order by d.refreshed_at desc nulls last
      limit 1
    ) ed on true
    left join lateral (
      select sum((ed.topic_profile->>m.topic)::numeric * case when m.is_working_on then 1.5 else 1.0 end) fit,
             array_agg(m.topic order by m.is_working_on desc,
                       (ed.topic_profile->>m.topic)::numeric desc) topics
      from me m
      where ed.topic_profile ? m.topic and (ed.topic_profile->>m.topic)::numeric >= 0.2
    ) f on true
  )
  select v.name, v.offer_value, v.description_snippet, v.categories, v.rating_avg, v.review_count,
         v.claim_count, v.featured, v.fresh_deal, v.partner_url, v.reviews_sample, v.matched_rank,
         case when d.topics is not null and array_length(d.topics,1) > 0
              then 'fits what you work on: ' || array_to_string(d.topics[1:2], ', ') end,
         d.snote
  from v1 v left join dos d on d.ord = v.ord
  -- ranking mode keeps ITS order exactly; browse/search gets the fit nudge, weak demoted in ties
  order by case when p_order is not null then v.ord else 0 end,
           case when p_order is null then coalesce(d.fit, 0) else 0 end desc,
           case when p_order is null then d.wsig else 0 end asc,
           v.ord;
end
$function$
