-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.personas_sheet(p_id text)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  select jsonb_build_object(
    'member', (select to_jsonb(l) || jsonb_build_object(
                 'niche', ma.main_niche, 'channels', coalesce(to_jsonb(ma.channel_mix),'[]'::jsonb), 'since', ma.started_year, 'title', ma.title,
                 'summary', mp.persona->>'summary', 'blurb', mp.persona->>'blurb',
                 'focus', coalesce((select jsonb_agg(f->>'item' order by (f->>'weight')::numeric desc nulls last) from jsonb_array_elements(coalesce(mp.persona->'focus','[]'::jsonb)) f), '[]'::jsonb),
                 'gives_text', coalesce((select jsonb_agg(g->>'item') from jsonb_array_elements(coalesce(mp.persona->'gives','[]'::jsonb)) g), '[]'::jsonb),
                 'asks_text', coalesce((select jsonb_agg(g->>'item') from jsonb_array_elements(coalesce(mp.persona->'asks','[]'::jsonb)) g), '[]'::jsonb),
                 'pattern', mp.persona->'engagement'->>'pattern')
               from digest.personas_library() l
               left join digest.member_attributes ma on ma.at_member_id = l.id
               left join digest.member_personas mp on mp.at_member_id = l.id
               where l.id = p_id),
    'stats', coalesce((select jsonb_agg(to_jsonb(s) - 'at_member_id' order by s.parent nulls first, s.value desc) from digest.personas_stats s where s.at_member_id = p_id), '[]'::jsonb),
    'asks',  coalesce((select jsonb_agg(distinct s.topic) from digest.personas_stats s where s.at_member_id = p_id and (s.evidence ? 'persona_asks_hits' or coalesce(s.weakness,0) > 0)), '[]'::jsonb),
    'gives', coalesce((select jsonb_agg(distinct s.topic) from digest.personas_stats s where s.at_member_id = p_id and s.evidence ? 'persona_gives_hits'), '[]'::jsonb)
  );
$function$
