-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.personas_fading()
 RETURNS TABLE(id text, fading_count integer)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  select s.at_member_id, count(*)::int
  from digest.personas_stats s
  join digest.member_profiles p on p.at_member_id = s.at_member_id
  where s.parent is null and s.badge = 'fading' and s.value > 0
    and p.status in ('Current Member','New Member','Current Member- Not Renewing','Current Member- Paused','Staff')
  group by s.at_member_id;
$function$
