-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.persona_signal_fingerprints()
 RETURNS TABLE(member_at_id text, member_phone text, member_name text, fingerprint text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  with actives as (
    select ma.at_member_id as atid, ma.full_name as nm
    from digest.member_attributes ma
    where ma.membership_status in ('Current Member', 'New Member', 'Current Member- Not Renewing', 'Staff')
  ), ph as (
    select m.at_member_id as atid, min(m.phone) as phone
    from digest.members m where m.phone is not null and m.at_member_id is not null
    group by m.at_member_id
  ), q as (
    select om.phone as phx, count(*) as n, max(om.created_at) as mx
    from digest.olivia_messages om
    where om.role = 'member' and coalesce(om.wamid, '') not like '%SELFTEST%'
      and om.created_at > now() - interval '180 days'
    group by om.phone
  ), att as (
    select r.member_at_id as atid, count(*) as n, max(coalesce(ec.app_starts_at, ec.start_at)) as mx
    from digest.event_registrations_live r
    join digest.events_catalog ec on ec.at_record_id = r.event_at_id
    where r.ticket_status = 'Confirmed' and r.member_at_id is not null
    group by r.member_at_id
  ), fb as (
    select p.author_name as nm, count(*) as n, max(p.created_time) as mx
    from digest.fb_posts p
    where p.created_time > now() - interval '180 days'
    group by p.author_name
  ), fm as (
    -- profile-scope form answers: a new submission, a re-mapped field or a corrected answer
    -- all move this term, which is what makes the member due for a rebuild
    select e.member_at_id as atid, count(*) as n, max(e.submitted_at) as mx
    from digest.form_answers_exploded e
    join digest.form_scope s on s.form_id = e.form_id and s.scope = 'profile'
    where e.member_at_id is not null
    group by e.member_at_id
  )
  select a.atid, ph.phone, a.nm,
         md5(coalesce(ma.refreshed_at::text, '') || '|'
             || coalesce(q.n, 0)::text || '@' || coalesce(q.mx::text, '') || '|'
             || coalesce(att.n, 0)::text || '@' || coalesce(att.mx::text, '') || '|'
             || coalesce(fb.n, 0)::text || '@' || coalesce(fb.mx::text, '') || '|'
             || coalesce(fm.n, 0)::text || '@' || coalesce(fm.mx::text, ''))
  from actives a
  join digest.member_attributes ma on ma.at_member_id = a.atid
  left join ph on ph.atid = a.atid
  left join q on q.phx = ph.phone
  left join att on att.atid = a.atid
  left join fb on fb.nm = a.nm
  left join fm on fm.atid = a.atid
$function$
