-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.personas_strong()
 RETURNS TABLE(id text, strong jsonb)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  select s.at_member_id, jsonb_object_agg(s.topic, s.value)
  from digest.personas_stats s
  join digest.member_profiles p on p.at_member_id = s.at_member_id
  where s.parent is null and s.value >= 60
    and p.status in ('Current Member','New Member','Current Member- Not Renewing','Current Member- Paused','Staff')
  group by s.at_member_id;
$function$
