-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.personas_related(p_id text)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  with me as (select topic, value from digest.personas_stats where at_member_id = p_id and parent is null),
  asks as (select topic from digest.personas_stats where at_member_id = p_id and (evidence ? 'persona_asks_hits' or coalesce(weakness,0) > 0)),
  others as (select s.at_member_id, s.topic, s.value from digest.personas_stats s
             join digest.member_profiles p on p.at_member_id = s.at_member_id
             where s.parent is null and s.at_member_id <> p_id
               and p.status in ('Current Member','New Member','Current Member- Not Renewing','Current Member- Paused','Staff')),
  cos as (select o.at_member_id,
                 sum(o.value * me.value) / nullif(sqrt(sum(o.value*o.value)) * sqrt((select sum(value*value) from me)), 0) as sim,
                 array_agg(o.topic order by o.value desc) filter (where o.value >= 70 and me.value >= 70) as shared
          from others o join me on me.topic = o.topic group by o.at_member_id),
  sim as (select c.*, l.name, l.city, l.level, l.photo_url from cos c join digest.personas_library() l on l.id = c.at_member_id
          where c.sim is not null order by c.sim desc limit 5),
  comp as (select o.at_member_id, array_agg(o.topic order by o.value desc) as cover, sum(o.value) as score
           from others o join asks a on a.topic = o.topic where o.value >= 75 group by o.at_member_id),
  compx as (select c.*, l.name, l.city, l.level, l.photo_url,
                   (select array_agg(o2.topic order by o2.value desc) from others o2 join me on me.topic = o2.topic where o2.at_member_id = c.at_member_id and o2.value >= 70 and me.value >= 70) as shared
            from comp c join digest.personas_library() l on l.id = c.at_member_id order by c.score desc limit 5)
  select jsonb_build_object(
    'similar', coalesce((select jsonb_agg(jsonb_build_object('id', at_member_id, 'name', name, 'city', city, 'level', level, 'photo_url', photo_url,
                          'pct', round(sim*100)::int, 'shared', coalesce(to_jsonb(shared[1:2]),'[]'::jsonb)) order by sim desc) from sim), '[]'::jsonb),
    'companions', coalesce((select jsonb_agg(jsonb_build_object('id', at_member_id, 'name', name, 'city', city, 'level', level, 'photo_url', photo_url,
                          'cover', to_jsonb(cover[1:2]), 'shared', coalesce(to_jsonb(shared[1:2]),'[]'::jsonb)) order by score desc) from compx), '[]'::jsonb));
$function$
