-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.persona_signals(p_at_member_id text)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare
  v_phone text; v_name text; v_n int;
begin
  select count(*) into v_n from digest.member_attributes ma where ma.at_member_id = p_at_member_id;
  if v_n <> 1 then return '{}'::jsonb; end if;
  select ma.full_name into v_name from digest.member_attributes ma where ma.at_member_id = p_at_member_id;
  select min(m.phone) into v_phone from digest.members m
  where m.at_member_id = p_at_member_id and m.phone is not null;

  return jsonb_build_object(
    'name', v_name,
    'attributes', (select to_jsonb(ma) - 'rev_band' - 'provenance' - 'at_member_id'
                   from digest.member_attributes ma where ma.at_member_id = p_at_member_id),
    'self_reported', (select coalesce(jsonb_agg(
                        case when length(f.question) > 88 then left(f.question, 50) || '…' || right(f.question, 36) else f.question end || ' = ' || left(f.ans, 80)
                          || ' (' || f.submitted_at::date || ')'
                        order by f.canonical_key), '[]'::jsonb)
                      from (
                        select distinct on (e.canonical_key)
                               e.canonical_key, e.question, e.submitted_at,
                               case when jsonb_typeof(e.value) = 'array'
                                    then (select string_agg(x, ' / ')
                                          from jsonb_array_elements_text(e.value) x)
                                    else e.value #>> '{}' end as ans
                        from digest.form_answers_exploded e
                        join digest.form_scope s on s.form_id = e.form_id and s.scope = 'profile'
                        where e.member_at_id = p_at_member_id
                          and e.answer_type <> 'text'
                          and e.canonical_key <> all (array['ttm_revenue','projected_revenue','prior_year_revenue'])
                          and nullif(trim(coalesce(e.question, '')), '') is not null
                        order by e.canonical_key, e.submitted_at desc
                      ) f
                      where nullif(trim(coalesce(f.ans, '')), '') is not null),
    'wa_chats_member_of', (select to_jsonb(m.channels_present) from digest.members m
                           where m.at_member_id = p_at_member_id and m.phone = v_phone limit 1),
    'questions_180d', case when v_phone is null then '[]'::jsonb else
                      (select coalesce(jsonb_agg(jsonb_build_object(
                        'd', om.created_at::date, 'q', left(om.text, 200)) order by om.created_at desc), '[]'::jsonb)
                      from (select * from digest.olivia_messages om
                            where om.phone = v_phone and om.role = 'member'
                              and coalesce(om.wamid, '') not like '%SELFTEST%'
                              and om.created_at > now() - interval '180 days'
                            order by om.created_at desc limit 60) om) end,
    'events_attended', (select coalesce(jsonb_agg(jsonb_build_object(
                          'name', coalesce(ec.app_title, ec.name),
                          'when', coalesce(ec.app_starts_at, ec.start_at)::date) order by coalesce(ec.app_starts_at, ec.start_at) desc), '[]'::jsonb)
                        from (select * from digest.event_registrations_live r
                              join digest.events_catalog ec on ec.at_record_id = r.event_at_id
                              where r.member_at_id = p_at_member_id and r.ticket_status = 'Confirmed'
                              order by coalesce(ec.app_starts_at, ec.start_at) desc limit 15) ec),
    'authored_recent', case when v_phone is not null then
                        (select coalesce(jsonb_agg(jsonb_build_object(
                          'src', c.source, 'd', c.occurred_at::date,
                          't', left(coalesce(nullif(c.title, ''), c.body), 220))), '[]'::jsonb)
                        from digest.content_search_v2(p_phone => v_phone, p_terms => '{}'::text[],
                          p_author => v_name, p_sources => array['fb_post', 'fb_comment', 'wa_message'],
                          p_limit => 30) c)
                      else
                        (select coalesce(jsonb_agg(jsonb_build_object(
                          'src', x.src, 'd', x.d, 't', x.t)), '[]'::jsonb)
                         from (
                           select 'fb_post' as src, p.created_time::date as d, left(p.text, 220) as t
                           from digest.fb_posts p where p.author_name = v_name and p.text is not null
                           union all
                           select 'fb_comment', c.created_time::date, left(c.text, 220)
                           from digest.fb_comments c where c.author_name = v_name and c.text is not null
                           order by d desc nulls last
                           limit 30) x)
                      end
  );
end $function$
