-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.personas_topic_peaks()
 RETURNS TABLE(topic text, strong_count integer, peak_count integer)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  select s.topic,
         count(*) filter (where s.value >= 60)::int as strong_count,
         count(*) filter (where s.value >= 60 and s.badge = 'peak')::int as peak_count
  from digest.personas_stats s
  join digest.member_profiles p on p.at_member_id = s.at_member_id
  where s.parent is null
    and p.status in ('Current Member','New Member','Current Member- Not Renewing','Current Member- Paused','Staff')
  group by s.topic;
$function$
