-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.personas_library()
 RETURNS TABLE(id text, name text, status text, city text, joined date, level integer, top jsonb, photo_url text, msgs30 integer, at_peak_count integer)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  with act as (
    select p.at_member_id, p.full_name, p.status, p.join_date
    from digest.member_profiles p
    where p.status in ('Current Member','New Member','Current Member- Not Renewing','Current Member- Paused','Staff')
  ), cat as (
    select s.at_member_id, s.topic, s.value, s.badge from digest.personas_stats s where s.parent is null
  ), lvl as (
    select at_member_id,
           round(avg(value) filter (where rn <= 3))::int as level,
           count(*) filter (where badge = 'peak' and value >= 50)::int as at_peak_count
    from (select c.*, row_number() over (partition by at_member_id order by value desc) rn from cat c) x
    group by at_member_id
  ), top2 as (
    select at_member_id, jsonb_agg(jsonb_build_object('name', topic, 'value', value) order by value desc) as top
    from (select c.*, row_number() over (partition by at_member_id order by value desc) rn from cat c) x
    where rn <= 2 group by at_member_id
  ), chats as (
    select m.at_member_id, max(coalesce(m.msgs_30d,0))::int as msgs30 from digest.members m group by m.at_member_id
  )
  select a.at_member_id, a.full_name, a.status,
         concat_ws(', ', ma.city, case when coalesce(ma.country,'') in ('United States','US','USA','') then ma.state else ma.country end),
         a.join_date, coalesce(l.level,0), coalesce(t.top,'[]'::jsonb), ph.public_url, coalesce(ch.msgs30,0), coalesce(l.at_peak_count,0)
  from act a
  left join digest.member_attributes ma on ma.at_member_id = a.at_member_id
  left join lvl l on l.at_member_id = a.at_member_id
  left join top2 t on t.at_member_id = a.at_member_id
  left join chats ch on ch.at_member_id = a.at_member_id
  left join digest.member_photos ph on ph.at_member_id = a.at_member_id
  order by a.full_name;
$function$
