-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.personas_cohort(p_stat text)
 RETURNS TABLE(id text, name text, status text, city text, level integer, value integer, top jsonb, photo_url text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  select l.id, l.name, l.status, l.city, l.level, s.value, l.top, l.photo_url
  from digest.personas_stats s
  join digest.personas_library() l on l.id = s.at_member_id
  where s.topic = p_stat and s.value >= 60
  order by s.value desc, l.name;
$function$
