-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.place_city(p text)
 RETURNS text
 LANGUAGE sql
 STABLE
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  with x as (
    -- strip a terminal ", NY" / ", New Jersey" style suffix, fold case for matching
    select lower(trim(regexp_replace(trim(p), '\s*,\s*[A-Za-z. ]+$', ''))) as folded,
           trim(regexp_replace(trim(p), '\s*,\s*[A-Za-z. ]+$', '')) as stripped
  )
  select case
    when p is null or trim(p) = '' then null
    when (select canonical from digest.city_aliases a, x where a.alias = x.folded) is not null
      then (select canonical from digest.city_aliases a, x where a.alias = x.folded)
    -- all-lowercase input gets title case ("new york" -> "New York"); mixed case is preserved
    when (select stripped = lower(stripped) from x) then (select initcap(stripped) from x)
    else (select stripped from x)
  end
$function$
