-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.profile_texts_for_embedding()
 RETURNS TABLE(at_member_id text, profile_text text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  select ma.at_member_id,
         left(concat_ws(' | ',
           'expertise: ' || digest.attr_clean(mp.at_fields->>'Area of Expertise'),
           'about: '     || digest.attr_clean(mp.at_fields->>'About Me'),
           'main niche: '|| digest.attr_clean(mp.at_fields->>'Main Niche'),
           'fun fact: '  || digest.attr_clean(mp.at_fields->>'Interesting / Fun fact'),
           'niches: '    || (select string_agg(n.niche, ', ') from digest.member_niches n
                              where n.at_member_id = ma.at_member_id),
           'categories: '|| array_to_string(ma.categories, ', ')
         ), 4000) as profile_text
  from digest.member_attributes ma
  join digest.member_profiles mp on mp.at_member_id = ma.at_member_id
  where ma.membership_status in ('Current Member','New Member','Pending Group Entrance','Current Member- Not Renewing')
    and ma.full_name is not null
$function$
