-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.propagate_display_name()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'digest', 'pg_temp'
AS $function$
begin
  update digest.members m set full_name = m.full_name
    where m.at_member_id = new.at_member_id;      -- no-op update fires the BEFORE trigger
  update digest.member_attributes ma set full_name = ma.full_name
    where ma.at_member_id = new.at_member_id;
  return new;
end $function$
