-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
-- #176 (2026-09-08): this mirror is written AHEAD of the apply — it is the body of
-- scripts/sql/20260908_public_gate_classify_member_audience_176.sql, which Andy applies by hand.
-- Until that migration runs, the live function still carries the #169 fix-round-3 body.
CREATE OR REPLACE FUNCTION digest.public_gate_classify(p_urls text[], p_source_ids text[])
 RETURNS TABLE(key text, klass text, source text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  -- content rows, by url then by source_id. OPEN is the MDS Facebook group — posts and comments a
  -- member can scroll to in the group this answer gets posted into. CLOSED is every other source:
  -- wa_message / wa_digest (a closed WhatsApp channel), call_transcript (a private call or meeting),
  -- application (a member's own submission, never anyone else's to read), and anything new that
  -- lands in this table without being added to the allowlist above — unknown stays closed.
  -- access_rule / sensitivity ride along as secondary guards so a group post an admin later marks
  -- restricted or never_surface drops out of the open bucket without this function being touched.
  select c.url as key,
         case when c.source in ('fb_post', 'fb_comment')
                   and c.access_rule->>'type' = 'public'
                   and coalesce(c.sensitivity, 'normal') = 'normal'
              then 'public' else 'closed' end,
         'content:' || c.source
  from digest.content_items c where c.url = any(coalesce(p_urls, '{}'))
  union all
  select c.source_id,
         case when c.source in ('fb_post', 'fb_comment')
                   and c.access_rule->>'type' = 'public'
                   and coalesce(c.sensitivity, 'normal') = 'normal'
              then 'public' else 'closed' end,
         'content:' || c.source
  from digest.content_items c where c.source_id = any(coalesce(p_source_ids, '{}'))
  union all
  -- partners: a published listing and its page are open to every member.
  -- #169 (verified 2026-09-07): partners_catalog has no partner_url column (only logo_url, an image).
  -- partner_lookup_v2 / partner_lookup both derive their `partner_url` output via
  -- digest.member_partner_url(partner_id), so we build the same key here rather than inventing a column.
  select digest.member_partner_url(p.partner_id), 'public', 'partner' from digest.partners_catalog p
  where p.status = 'published' and digest.member_partner_url(p.partner_id) = any(coalesce(p_urls, '{}'))
  union all
  -- events, by public page url.
  select e.public_page_url, 'public', 'event'
  from digest.events_catalog e
  where e.public_page_url = any(coalesce(p_urls, '{}'))
  union all
  -- events, by app url: the SAME event keyed by the other column — this is the branch event_lookup*
  -- output actually lands on (#169 fix round 2, kept). Now equally open: an event's page in the
  -- members' app is a page a member can already open.
  select e.app_url, 'public', 'event'
  from digest.events_catalog e
  where e.app_url = any(coalesce(p_urls, '{}'))
  union all
  -- videos, by id: the app's own library. Open when access_restriction says every member can watch
  -- it; a 'restricted' recording (mastermind / chapter / coaching cohort) is a closed room and
  -- stays closed.
  select v.video_id::text,
         case when v.access_restriction = 'public' then 'public' else 'closed' end, 'video'
  from digest.videos_catalog v where v.video_id::text = any(coalesce(p_source_ids, '{}'))
  union all
  -- videos, by app link: the SAME library entry keyed by the url an answer would actually print, so
  -- an open library link survives the module's link pass instead of being stripped as unclassified.
  -- The id is pulled out of the url with the same shape public_gate.js's VIDEO_LINK_RE matches, so
  -- a trailing slash or a query string cannot hide it.
  --
  -- DELIBERATE COLLISION, and it fails closed: a call_transcript content row's OWN url is this same
  -- `app.mds.co/videos/<id>` link (verified live — 13,507 transcript rows, all of them). When a turn
  -- cites a transcript chunk, the content branch above emits `closed` for that url and this branch
  -- emits `public`; `Public Redact` collapses duplicate keys most-restrictively, so the key lands
  -- `closed` — the transcript row cannot back a name and the link is stripped. Cite the library
  -- entry WITHOUT a transcript chunk and only this row exists, so the link survives. A private call
  -- never rides in on its own recording's page.
  select u.url,
         case when v.access_restriction = 'public' then 'public' else 'closed' end, 'video'
  from (select t.url, substring(t.url from 'app\.mds\.co/videos/([0-9a-f]{24})') as vid
        from unnest(coalesce(p_urls, '{}')) as t(url)) u
  join digest.videos_catalog v on v.video_id::text = u.vid
  where u.vid is not null;
$function$
