-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.public_gate_name_index()
 RETURNS TABLE(name text, kind text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  select distinct trim(n) as name, k as kind from (
    select full_name as n, 'member' as k from digest.members            where full_name is not null
    union all
    select full_name,       'member'      from digest.member_attributes where full_name is not null
    union all
    select display_name,    'speaker'     from digest.speakers          where display_name is not null and kind = 'member'
  ) x
  where length(trim(n)) >= 5 and position(' ' in trim(n)) > 0;   -- two-word names only; single words over-match
$function$
