-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.public_gate_classify(p_urls text[], p_source_ids text[])
 RETURNS TABLE(key text, klass text, source text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  -- content rows: by url, then by source_id
  select c.url as key,
         case when c.access_rule->>'type' = 'public' and coalesce(c.sensitivity,'normal') = 'normal' then 'public' else 'closed' end,
         'content:' || c.source
  from digest.content_items c where c.url = any(coalesce(p_urls, '{}'))
  union all
  select c.source_id, case when c.access_rule->>'type' = 'public' and coalesce(c.sensitivity,'normal') = 'normal' then 'public' else 'closed' end, 'content:' || c.source
  from digest.content_items c where c.source_id = any(coalesce(p_source_ids, '{}'))
  union all
  -- partners: the directory is public
  -- #169 (verified 2026-09-07): partners_catalog has no partner_url column (only logo_url, an image).
  -- partner_lookup_v2 / partner_lookup both derive their `partner_url` output via
  -- digest.member_partner_url(partner_id), so we build the same key here rather than inventing a column.
  select digest.member_partner_url(p.partner_id), 'public', 'partner' from digest.partners_catalog p
  where p.status = 'published' and digest.member_partner_url(p.partner_id) = any(coalesce(p_urls, '{}'))
  union all
  -- events: public only with a public page (or the app flag)
  select coalesce(e.public_page_url, e.app_url), case when e.public_page_url is not null or e.app_is_public then 'public' else 'closed' end, 'event'
  from digest.events_catalog e
  where coalesce(e.public_page_url, e.app_url) = any(coalesce(p_urls, '{}'))
  union all
  -- videos: by video id passed as a source id
  select v.video_id::text, case when v.access_restriction = 'public' then 'public' else 'closed' end, 'video'
  from digest.videos_catalog v where v.video_id::text = any(coalesce(p_source_ids, '{}'));
$function$
