-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.public_gate_name_index()
 RETURNS TABLE(name text, kind text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  select distinct trim(n) as name, k as kind from (
    select full_name as n, 'member' as k from digest.members            where full_name is not null
    union all
    select full_name,       'member'      from digest.member_attributes where full_name is not null
    union all
    select display_name,    'speaker'     from digest.speakers          where display_name is not null and kind = 'member'
  ) x
  where length(trim(n)) >= 5 and position(' ' in trim(n)) > 0   -- two-word names only; single words over-match
    and trim(n) not ilike 'MDS %'    -- org rows: MDS Community / Partners / Programs / Member / Chapters / Test
    and trim(n) not ilike '% MDS'    -- org rows: Systems MDS / Andy MDS
    -- #176, three properties that disqualify a row from being a person's name (see header):
    and trim(n) !~ '[0-9]'           -- a phone number, address, record id or duplicate suffix, not a name
    and trim(n) not like '%@%'       -- an email glued to (or instead of) a name
    and lower(trim(n)) !~ '(^|[^[:alpha:]])test(ing)?([^[:alpha:]]|$)'  -- placeholder/test accounts
    and lower(split_part(trim(n), ' ', 1)) <> all (array[               -- function-word first token
      'a','an','the','this','that','these','those','my','your','his','her','its','our','their',
      'they','them','we','you','and','but','because','from','with','without','into','onto','about',
      'over','under','for','of','to','in','on','at','as','not','none','null','unknown','undefined',
      'test','testing','first','last','next','other','another','some','any','all','both','each',
      'every','more','most','much','many','very','just','only','also','here','there','when','where',
      'what','which','who','whom','whose','how','why','same','such','etc']);
$function$
