-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.refresh_all_member_attributes()
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare n int := 0; r record;
begin
  for r in select at_member_id from digest.member_profiles loop
    perform digest.derive_member_attributes(r.at_member_id);
    n := n + 1;
  end loop;
  return n;
end $function$
