-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.refresh_member_phone_index()
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'digest', 'public'
AS $function$
declare n integer;
begin
  with active_owner as (
    select p.phone10, p.at_member_id, min(p.source) source
      from digest.member_phones p
      join digest.member_attributes ma on ma.at_member_id = p.at_member_id
     where digest.is_active_member_status(ma.membership_status)
     group by p.phone10, p.at_member_id
  ),
  unambiguous as (
    -- exactly one ACTIVE member owns this number
    select phone10, min(at_member_id) at_member_id, min(source) source
      from active_owner
     group by phone10
    having count(distinct at_member_id) = 1
  ),
  upserted as (
    insert into digest.member_phone_index (phone10, at_member_id, source, refreshed_at)
    select phone10, at_member_id, source, now() from unambiguous
    on conflict (phone10) do update
      set at_member_id = excluded.at_member_id,
          source       = excluded.source,
          refreshed_at = now()
    returning 1
  )
  select count(*) into n from upserted;

  -- drop numbers that no longer belong to exactly one active member (member cancelled, phone
  -- changed, or a second active member appeared on the same number)
  delete from digest.member_phone_index i
   where not exists (
     select 1 from digest.member_phones p
       join digest.member_attributes ma on ma.at_member_id = p.at_member_id
      where p.phone10 = i.phone10
        and p.at_member_id = i.at_member_id
        and digest.is_active_member_status(ma.membership_status));
  return n;
end $function$
