-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.refresh_form_answers()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare n bigint;
begin
  refresh materialized view concurrently digest.form_answers_exploded;
  select count(*) into n from digest.form_answers_exploded;
  return jsonb_build_object('rows', n);
end $function$
