-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.refresh_entity_dossiers()
 RETURNS TABLE(o_kind text, o_rows integer)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare v_n int;
begin
  with vids as (
    select v.video_id, v.title, v.search_tsv,
           coalesce(v.view_count,0) vc, coalesce(v.like_count,0) lc, coalesce(v.comment_count,0) cc
    from digest.videos_catalog v
    where v.status = 'published' and v.deleted_at is null
  ), catalog_hits as (
    select vd.video_id, t.topic,
           ts_rank(vd.search_tsv, digest.expertise_query(array_to_string(t.terms,' '))) rnk
    from vids vd cross join digest.expertise_topics t
    where vd.search_tsv @@ digest.expertise_query(array_to_string(t.terms,' '))
  ), transcript_hits as (
    select ci.meta->>'video_id' as video_id, t.topic,
           2.0 * sum(ts_rank(ci.search_tsv, digest.expertise_query(array_to_string(t.terms,' ')))) rnk
    from digest.content_items ci
    join digest.videos_catalog v on v.video_id = ci.meta->>'video_id'
                                and v.status = 'published' and v.deleted_at is null
    cross join digest.expertise_topics t
    where ci.source = 'call_transcript'
      and ci.search_tsv @@ digest.expertise_query(array_to_string(t.terms,' '))
    group by 1, 2
  ), hits as (
    select video_id, topic, sum(rnk) as rnk
    from (select * from catalog_hits union all select * from transcript_hits) u
    group by video_id, topic
  ), prof as (
    select h.video_id,
           jsonb_object_agg(h.topic, round(least(1.0, h.rnk*10)::numeric, 3)
                            order by h.rnk desc) filter (where h.rnk > 0.01) tp
    from hits h group by h.video_id
  ), pct as (
    select vd.video_id,
           percent_rank() over (order by vd.vc) pvc,
           percent_rank() over (order by vd.lc + vd.cc) peng
    from vids vd
  )
  insert into digest.entity_dossier as ed (kind, entity_id, name, topic_profile, reception, strength_note, weak_signal, refreshed_at)
  select 'video', vd.video_id, vd.title,
         coalesce(p.tp, '{}'::jsonb),
         jsonb_build_object('views', vd.vc, 'likes', vd.lc, 'comments', vd.cc,
                            'view_pct', round(x.pvc::numeric,2), 'engagement_pct', round(x.peng::numeric,2)),
         case when x.peng >= 0.9 then 'one of the most-watched and reacted-to sessions in the library'
              when x.peng >= 0.7 then 'a session members clearly engaged with'
              end,
         case when x.peng < 0.2 and vd.vc > 0 then round((0.2 - x.peng)::numeric, 2) end,
         now()
  from vids vd left join prof p on p.video_id = vd.video_id join pct x on x.video_id = vd.video_id
  on conflict (kind, entity_id) do update
    set name = excluded.name, topic_profile = excluded.topic_profile,
        reception = excluded.reception, strength_note = excluded.strength_note,
        weak_signal = excluded.weak_signal, refreshed_at = excluded.refreshed_at
    where ed.topic_profile is distinct from excluded.topic_profile
       or ed.reception is distinct from excluded.reception
       or ed.strength_note is distinct from excluded.strength_note
       or ed.weak_signal is distinct from excluded.weak_signal;
  get diagnostics v_n = row_count;
  o_kind := 'video'; o_rows := v_n; return next;

  with parts as (
    select pc.partner_id::text pid, pc.name pname, pc.search_tsv,
           pc.rating_avg ra, coalesce(pc.review_count,0) rc, coalesce(pc.claim_count,0) cl
    from digest.partners_catalog pc
    where pc.status = 'published' and pc.access_restriction = 'public'
  ), hits as (
    select pt.pid, t.topic,
           ts_rank(pt.search_tsv, digest.expertise_query(array_to_string(t.terms,' '))) rnk
    from parts pt cross join digest.expertise_topics t
    where pt.search_tsv @@ digest.expertise_query(array_to_string(t.terms,' '))
  ), prof as (
    select h.pid, jsonb_object_agg(h.topic, round(least(1.0, h.rnk*10)::numeric,3)
                                   order by h.rnk desc) filter (where h.rnk > 0.01) tp
    from hits h group by h.pid
  )
  insert into digest.entity_dossier as ed (kind, entity_id, name, topic_profile, reception, strength_note, weak_signal, refreshed_at)
  select 'partner', pt.pid, pt.pname,
         coalesce(p.tp, '{}'::jsonb),
         jsonb_build_object('rating_avg', pt.ra, 'review_count', pt.rc, 'claim_count', pt.cl),
         case when pt.rc >= 20 and pt.ra >= 4.5 then 'heavily reviewed by members and strongly rated'
              when pt.rc >= 5 and pt.ra >= 4.5 then 'consistently well rated by members'
              when pt.cl >= 100 then 'one of the most-claimed deals in the directory'
              end,
         case when pt.rc >= 3 and pt.ra is not null and pt.ra < 3.5 then round((3.5 - pt.ra)::numeric, 2) end,
         now()
  from parts pt left join prof p on p.pid = pt.pid
  on conflict (kind, entity_id) do update
    set name = excluded.name, topic_profile = excluded.topic_profile,
        reception = excluded.reception, strength_note = excluded.strength_note,
        weak_signal = excluded.weak_signal, refreshed_at = excluded.refreshed_at
    where ed.topic_profile is distinct from excluded.topic_profile
       or ed.reception is distinct from excluded.reception
       or ed.strength_note is distinct from excluded.strength_note
       or ed.weak_signal is distinct from excluded.weak_signal;
  get diagnostics v_n = row_count;
  o_kind := 'partner'; o_rows := v_n; return next;

  with ev as (
    select c.at_record_id eid, coalesce(c.app_title, c.name) ename,
           to_tsvector('english', coalesce(c.app_title, c.name, '') || ' ' || coalesce(c.event_type,'') || ' ' || coalesce(c.style,'')) tsv
    from digest.events_catalog c
  ), reg as (
    select distinct er.event_at_id eid, er.member_at_id mid
    from digest.event_registrations_live er where er.member_at_id is not null
  ), draw as (
    select r.eid, count(*) regs from reg r group by r.eid
  ), comm as (
    select e.topic, avg(e.score) base from digest.member_expertise e
    where coalesce(e.weakness_score,0) = 0 and e.score > 0 group by e.topic
  ), att as (
    select r.eid, e.topic, avg(e.score) ascore, count(*) n
    from reg r join digest.member_expertise e on e.at_member_id = r.mid
    where coalesce(e.weakness_score,0) = 0 and e.score > 0
    group by r.eid, e.topic
  ), lifted as (
    select a.eid, a.topic, round(least(1.0, (a.ascore/c.base)/3.0)::numeric, 3) w,
           (a.ascore/c.base) lift
    from att a join comm c on c.topic = a.topic join draw d on d.eid = a.eid
    where d.regs between 5 and 150 and a.n >= 5 and (a.ascore/c.base) >= 1.3
  ), attprof as (
    select l.eid, jsonb_object_agg(l.topic, l.w order by l.lift desc) tp
    from (select *, row_number() over (partition by eid order by lift desc) rn from lifted) l
    where l.rn <= 5 group by l.eid
  ), flagship as (
    select r.eid,
           jsonb_build_object(
             'topics', coalesce((
                select jsonb_agg(jsonb_build_object('topic', x.topic, 'members', x.n)
                                 order by x.n desc)
                from (select e.topic, count(distinct r2.mid) n
                        from reg r2 join digest.member_expertise e on e.at_member_id = r2.mid
                       where r2.eid = r.eid and coalesce(e.weakness_score,0) = 0 and e.score > 0
                       group by e.topic having count(distinct r2.mid) >= 3
                       order by count(distinct r2.mid) desc limit 8) x), '[]'::jsonb),
             'niches', coalesce((
                select jsonb_agg(jsonb_build_object('niche', y.label, 'members', y.n)
                                 order by y.n desc)
                from (select (array_agg(cc.label order by length(cc.label)))[1] label,
                             count(distinct cc.mid) n
                        from (select r3.mid,
                                     regexp_replace(lower(trim(cat)), '[^a-z0-9]|and', '', 'g') key,
                                     trim(cat) label
                                from reg r3
                                join digest.member_attributes ma on ma.at_member_id = r3.mid
                                cross join lateral unnest(coalesce(ma.categories,'{}'::text[])) cat
                               where r3.eid = r.eid and nullif(trim(cat),'') is not null) cc
                       group by cc.key having count(distinct cc.mid) >= 3
                       order by count(distinct cc.mid) desc limit 6) y), '[]'::jsonb),
             'rev_bands', coalesce((
                select jsonb_object_agg(z.band, z.n)
                from (select ma.rev_band band, count(*) n
                        from reg r4 join digest.member_attributes ma on ma.at_member_id = r4.mid
                       where r4.eid = r.eid and ma.rev_band is not null
                       group by 1 having count(*) >= 3) z), '{}'::jsonb),
             'countries', coalesce((
                select jsonb_agg(jsonb_build_object('country', q.country, 'members', q.n)
                                 order by q.n desc)
                from (select initcap(digest.country_fold(ma.country)) country, count(*) n
                        from reg r5 join digest.member_attributes ma on ma.at_member_id = r5.mid
                       where r5.eid = r.eid and ma.country is not null
                         and digest.country_fold(ma.country) is not null
                       group by 1 having count(*) >= 3
                       order by count(*) desc limit 6) q), '[]'::jsonb)
           ) room
    from (select distinct eid from reg) r
    join digest.events_catalog c2 on c2.at_record_id = r.eid
    join digest.event_series_profile sp
      on coalesce(c2.app_title, c2.name) ~* sp.match_pattern
     and coalesce(c2.app_title, c2.name) !~* coalesce(sp.exclude_pattern, '$^')
  ), namehits as (
    select e2.eid, t.topic, ts_rank(e2.tsv, digest.expertise_query(array_to_string(t.terms,' '))) rnk
    from ev e2 cross join digest.expertise_topics t
    where e2.tsv @@ digest.expertise_query(array_to_string(t.terms,' '))
  ), nameprof as (
    select nh.eid, jsonb_object_agg(nh.topic, round(least(1.0, nh.rnk*10)::numeric,3)) tp
    from namehits nh where nh.rnk > 0.01 group by nh.eid
  )
  insert into digest.entity_dossier as ed (kind, entity_id, name, topic_profile, reception, strength_note, weak_signal, refreshed_at)
  select 'event', e3.eid, e3.ename,
         coalesce(np.tp, '{}'::jsonb) || coalesce(ap.tp, '{}'::jsonb),
         jsonb_build_object('member_registrations', coalesce(d.regs,0),
                            'audience', case when fl.room is not null then 'flagship - a room, not a topic: describe who is in it, never what it is about'
                                             when coalesce(d.regs,0) > 150 then 'flagship - draws the whole community, no topic skew'
                                             when ap.tp is not null then 'selective room - topics are lift over the community baseline'
                                             end)
           || case when fl.room is not null then jsonb_build_object('room', fl.room) else '{}'::jsonb end,
         case when coalesce(d.regs,0) > 150 then 'a flagship - genuinely for everyone'
              when coalesce(d.regs,0) >= 40 then 'draws a strong member crowd'
              end,
         null,
         now()
  from ev e3 left join attprof ap on ap.eid = e3.eid
  left join flagship fl on fl.eid = e3.eid
  left join nameprof np on np.eid = e3.eid
  left join draw d on d.eid = e3.eid
  on conflict (kind, entity_id) do update
    set name = excluded.name, topic_profile = excluded.topic_profile,
        reception = excluded.reception, strength_note = excluded.strength_note,
        weak_signal = excluded.weak_signal, refreshed_at = excluded.refreshed_at
    where ed.topic_profile is distinct from excluded.topic_profile
       or ed.reception is distinct from excluded.reception
       or ed.strength_note is distinct from excluded.strength_note;
  get diagnostics v_n = row_count;
  o_kind := 'event'; o_rows := v_n; return next;

  with ch as (
    select ma.at_fields_chapter chname, e.topic, avg(e.score) ascore, count(*) n
    from (select ma2.at_member_id,
                 digest.attr_clean(mp.at_fields->>'Chapter Affiliation') at_fields_chapter
          from digest.member_attributes ma2
          join digest.member_profiles mp on mp.at_member_id = ma2.at_member_id
          where digest.is_active_member_status(ma2.membership_status)) ma
    join digest.member_expertise e on e.at_member_id = ma.at_member_id
    where ma.at_fields_chapter is not null and ma.at_fields_chapter <> 'No Chapter Affiliation'
      and coalesce(e.weakness_score,0) = 0 and e.score > 0
    group by ma.at_fields_chapter, e.topic
  ), prof as (
    select c.chname, jsonb_object_agg(c.topic, round(least(1.0,(c.ascore/10.0))::numeric,3)
                                      order by c.ascore desc) tp,
           sum(c.n) tot
    from (select *, row_number() over (partition by chname order by ascore desc) rn from ch) c
    where c.rn <= 5
    group by c.chname
  )
  insert into digest.entity_dossier as ed (kind, entity_id, name, topic_profile, reception, strength_note, weak_signal, refreshed_at)
  select 'chapter', p.chname, p.chname, p.tp,
         jsonb_build_object('expertise_rows', p.tot),
         null, null, now()
  from prof p
  on conflict (kind, entity_id) do update
    set topic_profile = excluded.topic_profile, reception = excluded.reception,
        refreshed_at = excluded.refreshed_at
    where ed.topic_profile is distinct from excluded.topic_profile
       or ed.reception is distinct from excluded.reception;
  get diagnostics v_n = row_count;
  o_kind := 'chapter'; o_rows := v_n; return next;
end $function$
