-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.registration_status(p_member text, p_event text)
 RETURNS TABLE(is_registered boolean, matched_via text, roster_synced_at timestamp with time zone, roster_stale_days integer)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  -- #147: one implementation lives in registration_status_v2. This keeps the original four-column
  -- shape for callers that only ever needed the roster answer (event_who, the gates), so the two can
  -- never drift apart — same rows, same alias bridge, same freshness fields.
  select v.has_ticket, v.matched_via, v.roster_synced_at, v.roster_stale_days
  from digest.registration_status_v2(p_member, p_event) v
$function$
