-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.registration_status_v2(p_member text, p_event text)
 RETURNS TABLE(is_registered boolean, has_ticket boolean, is_attending boolean, matched_via text, attending_via text, roster_synced_at timestamp with time zone, roster_stale_days integer, attendees_synced_at timestamp with time zone)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  -- #147 (Andy 2026-09-10: "AT roster, but we need to read the data from Supa, not AT since at has
  -- bottle necks"). ONE function, TWO facets, so no two lanes can contradict each other:
  --   has_ticket    the Airtable roster, read from its Supabase mirror. GATES who-to-meet and
  --                 attendee names. `is_registered` is kept as an alias of it so every existing
  --                 caller keeps its exact meaning and the leak gate's control stays intact.
  --   is_attending  the GroupOS attendee export, plus anyone holding a ticket. Drives the PERSONAL
  --                 AGENDA: a speaker or partner attends without a member ticket, and taking their
  --                 schedule away to tidy one number would be a regression for a real person.
  -- Both sides resolve a person through member_alias_ids + member_email_alias, so a duplicate member
  -- record cannot split one human across the two answers. p_event accepts either the Airtable record
  -- id or the GroupOS event id; events_catalog bridges them.
  with me as (select nullif(btrim(p_member), '') as at_member_id),
  my_ids as (select unnest(digest.member_alias_ids(p_member)) as at_member_id),
  my_emails as (
    select distinct lower(btrim(a.email)) as email
      from digest.member_email_alias a, me
     where a.at_member_id = me.at_member_id
       and nullif(btrim(a.email), '') is not null
  ),
  ev as (
    select c.at_record_id, c.app_event_id
      from digest.events_catalog c
     where c.at_record_id = nullif(btrim(p_event), '')
        or c.app_event_id = nullif(btrim(p_event), '')
     limit 1
  ),
  roster as (
    select r.member_at_id, lower(btrim(r.email)) as email, r.synced_at
      from digest.event_registrations_live r
     where r.event_at_id = coalesce((select at_record_id from ev), nullif(btrim(p_event), ''))
  ),
  hit as (
    select
      bool_or(r.member_at_id is not null
              and r.member_at_id = (select at_member_id from me))              as by_own_id,
      bool_or(r.member_at_id is not null
              and r.member_at_id in (select at_member_id from my_ids))         as by_alias_id,
      bool_or(r.email is not null and r.email in (select email from my_emails)) as by_email,
      max(r.synced_at)                                                          as synced_at
    from roster r
  ),
  att as (
    select
      bool_or(p.at_member_id is not null
              and p.at_member_id in (select at_member_id from my_ids))          as by_id,
      bool_or(lower(btrim(p.email)) in (select email from my_emails))           as by_email,
      max(p.synced_at)                                                          as synced_at
    from event.attendees a
    join event.people p on p.id = a.person_id
    where a.event_id = coalesce((select app_event_id from ev), nullif(btrim(p_event), ''))
  )
  select
    coalesce(h.by_own_id or h.by_alias_id or h.by_email, false)                    as is_registered,
    coalesce(h.by_own_id or h.by_alias_id or h.by_email, false)                    as has_ticket,
    coalesce(h.by_own_id or h.by_alias_id or h.by_email
             or a.by_id or a.by_email, false)                                      as is_attending,
    case
      when coalesce(h.by_own_id, false)   then 'member_id'
      when coalesce(h.by_alias_id, false) then 'alias_member_id'
      when coalesce(h.by_email, false)    then 'alias_email'
    end                                                                            as matched_via,
    case
      when coalesce(h.by_own_id or h.by_alias_id or h.by_email, false) then 'roster_ticket'
      when coalesce(a.by_id, false)    then 'groupos_member_id'
      when coalesce(a.by_email, false) then 'groupos_email'
    end                                                                            as attending_via,
    h.synced_at                                                                    as roster_synced_at,
    case when h.synced_at is not null
         then greatest(0, extract(day from (now() - h.synced_at))::integer) end     as roster_stale_days,
    a.synced_at                                                                    as attendees_synced_at
  from hit h cross join att a
$function$
