-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.report_create(p_phone text, p_text text, p_context text DEFAULT NULL::text)
 RETURNS TABLE(ok boolean, report_id bigint, note text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare v_name text; v_at text; v_id bigint;
begin
  select m.name, m.at_member_id into v_name, v_at
  from digest.members m
  where m.phone = p_phone and digest.is_active_member_status(m.membership_status)
  limit 1;
  if v_name is null then return; end if;                      -- fail closed
  if length(trim(coalesce(p_text,''))) < 3 then
    return query select false, null::bigint, 'empty report'::text; return;
  end if;
  -- idempotent: the loop sometimes double-calls its tools; same member + same text
  -- within 15 min is ONE report (probe 2026-08-01 filed rows 10+11 from one command)
  select r.id into v_id from digest.olivia_reports r
  where r.phone = p_phone and r.report_text = left(trim(p_text), 4000)
    and r.created_at > now() - interval '15 minutes'
  order by r.id desc limit 1;
  if v_id is not null then
    return query select true, v_id, 'already filed — the MDS team sees it in the Olivia portal'::text; return;
  end if;
  insert into digest.olivia_reports(phone, member_name, at_member_id, report_text, context)
  values (p_phone, v_name, v_at, left(trim(p_text), 4000), left(p_context, 1000))
  returning id into v_id;
  return query select true, v_id, 'saved — the MDS team sees it in the Olivia portal'::text;
end $function$
