-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.resolve_asker_by_uid(p_user_id text)
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'public'
AS $function$
  select w.at_member_id
    from digest.member_wa_ids w
    join digest.member_attributes a on a.at_member_id = w.at_member_id
   where w.wa_user_id = p_user_id
     and p_user_id is not null
     and digest.is_active_member_status(a.membership_status)
$function$
