-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.resolve_member_by_email(p_email text)
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  with hits as (
    select distinct a.at_member_id,
           digest.is_active_member_status(m.membership_status) as is_active
      from digest.member_email_alias a
      left join digest.member_attributes m on m.at_member_id = a.at_member_id
     where nullif(btrim(p_email), '') is not null
       and lower(btrim(a.email)) = lower(btrim(p_email))
  )
  select case
           when (select count(*) from hits) = 1
             then (select at_member_id from hits)
           when (select count(*) from hits where is_active) = 1
             then (select at_member_id from hits where is_active)
         end
$function$
