-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.resolve_asker(p_phone text)
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  select i.at_member_id
  from digest.member_phone_index i
  join digest.member_attributes a on a.at_member_id = i.at_member_id
  where i.phone10 = right(regexp_replace(coalesce(p_phone, ''), '\D', '', 'g'), 10)
    and length(regexp_replace(coalesce(p_phone, ''), '\D', '', 'g')) >= 10
    and digest.is_active_member_status(a.membership_status)
$function$
