-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.schema_source()
 RETURNS TABLE(kind text, obj_name text, file_name text, definition text)
 LANGUAGE sql
 STABLE
 SET search_path TO 'pg_catalog', 'public'
AS $function$
  with fns as (
    select p.oid,
           p.proname,
           pg_get_function_identity_arguments(p.oid) as args,
           pg_get_functiondef(p.oid)                 as def,
           count(*) over (partition by p.proname)    as n_same_name
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'digest'
  )
  select 'function'::text,
         proname || '(' || args || ')',
         case when n_same_name > 1
              then proname || '__' || substr(md5(args), 1, 8)
              else proname
         end || '.sql',
         def
  from fns
  union all
  select 'view'::text,
         c.relname,
         c.relname || '.sql',
         'create or replace view digest.' || quote_ident(c.relname) || ' as' || E'\n'
           || pg_get_viewdef(c.oid, true)
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'digest' and c.relkind = 'v'
  union all
  select 'matview'::text,
         c.relname,
         c.relname || '.sql',
         'create materialized view digest.' || quote_ident(c.relname) || ' as' || E'\n'
           || pg_get_viewdef(c.oid, true)
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'digest' and c.relkind = 'm'
  union all
  select 'catalog'::text, 'triggers', 'triggers.sql',
         coalesce((
           select string_agg(pg_get_triggerdef(t.oid, true) || ';', E'\n' order by
                             c.relname, t.tgname)
           from pg_trigger t
           join pg_class c     on c.oid = t.tgrelid
           join pg_namespace n on n.oid = c.relnamespace
           where n.nspname = 'digest' and not t.tgisinternal
         ), '-- no triggers in schema digest')
  union all
  select 'catalog'::text, 'policies', 'policies.sql',
         coalesce((
           select string_agg(
                    format('create policy %I on digest.%I as %s for %s to %s%s%s;',
                           policyname, tablename, permissive, cmd,
                           array_to_string(roles, ', '),
                           coalesce(' using (' || qual || ')', ''),
                           coalesce(' with check (' || with_check || ')', '')),
                    E'\n' order by tablename, policyname)
           from pg_policies where schemaname = 'digest'
         ), '-- no row-level-security policies in schema digest')
  union all
  select 'catalog'::text, 'grants', 'grants.sql',
         coalesce((
           select string_agg(line, E'\n' order by line) from (
             select format('grant execute on function digest.%I(%s) to %s;',
                           p.proname, pg_get_function_identity_arguments(p.oid),
                           coalesce(r.rolname, 'public')) as line
             from pg_proc p
             join pg_namespace n on n.oid = p.pronamespace
             cross join lateral aclexplode(coalesce(p.proacl,
                                acldefault('f', p.proowner))) a
             left join pg_roles r on r.oid = a.grantee
             where n.nspname = 'digest' and a.privilege_type = 'EXECUTE'
             union all
             select format('grant %s on digest.%I to %s;',
                           lower(a.privilege_type), c.relname,
                           coalesce(r.rolname, 'public'))
             from pg_class c
             join pg_namespace n on n.oid = c.relnamespace
             cross join lateral aclexplode(coalesce(c.relacl,
                                acldefault('r', c.relowner))) a
             left join pg_roles r on r.oid = a.grantee
             where n.nspname = 'digest' and c.relkind in ('r', 'v', 'm', 'p')
           ) g
         ), '-- no grants in schema digest')
  union all
  select 'catalog'::text, 'rls', 'rls.sql',
         coalesce((
           select string_agg(
                    case when c.relrowsecurity
                         then format('alter table digest.%I enable row level security;',
                                     c.relname)
                         else format('-- digest.%I: row level security DISABLED',
                                     c.relname) end,
                    E'\n' order by c.relname)
           from pg_class c
           join pg_namespace n on n.oid = c.relnamespace
           where n.nspname = 'digest' and c.relkind in ('r', 'p')
         ), '-- no tables in schema digest')
  union all
  select 'catalog'::text, 'tables', 'tables.sql',
         coalesce((
           select string_agg(block, E'\n\n' order by relname) from (
             select c.relname,
                    format('-- digest.%I', c.relname)
                    || E'\n' || coalesce((
                         select string_agg(
                                  format('--   %-34s %s%s%s', a.attname,
                                         format_type(a.atttypid, a.atttypmod),
                                         case when a.attnotnull then ' not null' else '' end,
                                         coalesce(' default ' || pg_get_expr(d.adbin, d.adrelid), '')),
                                  E'\n' order by a.attnum)
                         from pg_attribute a
                         left join pg_attrdef d on d.adrelid = a.attrelid
                                               and d.adnum   = a.attnum
                         where a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
                       ), '--   (no columns)')
                    || coalesce(E'\n' || (
                         select string_agg(format('alter table digest.%I add constraint %I %s;',
                                                  c.relname, con.conname,
                                                  pg_get_constraintdef(con.oid)),
                                           E'\n' order by con.conname)
                         from pg_constraint con where con.conrelid = c.oid
                       ), '')
                    || coalesce(E'\n' || (
                         select string_agg(pg_get_indexdef(i.indexrelid) || ';',
                                           E'\n' order by pg_get_indexdef(i.indexrelid))
                         from pg_index i where i.indrelid = c.oid
                       ), '') as block
             from pg_class c
             join pg_namespace n on n.oid = c.relnamespace
             where n.nspname = 'digest' and c.relkind in ('r', 'p')
           ) t
         ), '-- no tables in schema digest');
$function$
