-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.selftest_cleanup(p_dry_run boolean DEFAULT true, p_phone text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare
  v_q bigint; v_a bigint; v_seen bigint;
begin
  create temp table _st_q on commit drop as
  select m.id, m.phone,
         coalesce((select min(n.id) from digest.olivia_messages n
                    where n.phone = m.phone and n.role = 'member' and n.id > m.id),
                  9223372036854775807) as next_member_id
    from digest.olivia_messages m
   where m.role = 'member'
     and coalesce(m.wamid,'') like 'wamid.SELFTEST%'
     and (p_phone is null or m.phone = p_phone);

  create temp table _st_a on commit drop as
  select a.id
    from digest.olivia_messages a
    join _st_q q on q.phone = a.phone
   where a.role <> 'member' and a.id > q.id and a.id < q.next_member_id;

  select count(*) into v_q from _st_q;
  select count(*) into v_a from _st_a;
  select count(*) into v_seen from digest.olivia_seen
   where wamid like 'wamid.SELFTEST%'
     and (p_phone is null or wamid like '%' || p_phone || '%' or p_phone is not null);

  if p_dry_run then
    return jsonb_build_object('dry_run', true, 'phone', p_phone,
                              'questions', v_q, 'answers', v_a, 'seen', v_seen);
  end if;

  delete from digest.olivia_messages where id in (select id from _st_a);
  delete from digest.olivia_messages where id in (select id from _st_q);
  if p_phone is null then
    delete from digest.olivia_seen where wamid like 'wamid.SELFTEST%';
  end if;

  return jsonb_build_object('dry_run', false, 'phone', p_phone,
                            'questions', v_q, 'answers', v_a);
end;
$function$
