-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.session_rollup()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
  if new.member is null then
    return new; -- member-less staff-ticket sessions: telemetry only, no rollup target
  end if;
  if tg_op = 'INSERT' then
    update digest.members
      set session_count = coalesce(session_count, 0) + 1,
          portal_last_seen_at = new.last_seen_at
      where airtable_id = new.member;
  elsif tg_op = 'UPDATE' and new.last_seen_at is distinct from old.last_seen_at then
    update digest.members
      set portal_last_seen_at = new.last_seen_at
      where airtable_id = new.member;
  end if;
  return new;
end
$function$
