-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.set_relay_secret(p_secret text)
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'digest', 'vault', 'extensions', 'pg_temp'
AS $function$
declare v_id uuid;
begin
  if p_secret is null or length(btrim(p_secret)) < 32 then
    raise exception 'relay secret must be at least 32 characters';
  end if;

  select id into v_id from vault.secrets where name = 'OLIVIA_RELAY_SECRET';
  if v_id is null then
    perform vault.create_secret(p_secret, 'OLIVIA_RELAY_SECRET',
      '#105: shared secret between the relay (digest.mds.co/api/olivia/webhook) and the n8n WA webhook, so n8n refuses anything that did not come through the relay.');
    return 'created';
  end if;
  perform vault.update_secret(v_id, p_secret);
  return 'rotated';
end;
$function$
