-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.set_health_report_secret(p_secret text)
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'digest', 'vault', 'pg_temp'
AS $function$
declare v_id uuid;
begin
  if p_secret is null or length(btrim(p_secret)) < 24 then
    raise exception 'health report secret must be at least 24 characters';
  end if;
  select id into v_id from vault.secrets where name = 'HEALTH_REPORT_SECRET';
  if v_id is null then
    perform vault.create_secret(p_secret, 'HEALTH_REPORT_SECRET',
      'Shared secret for GET /api/health/report. Accepted alongside the Render env copy.');
    return 'created';
  end if;
  perform vault.update_secret(v_id, p_secret);
  return 'rotated';
end;
$function$
