-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.stamp_event_registrations()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare v_email int; v_name int;
begin
  with emails as (
    select em, min(at_member_id) as aid, count(distinct at_member_id) as n
    from (
      select lower(at_fields->>'Email') as em, at_member_id from digest.member_profiles
        where coalesce(at_fields->>'Email','') <> ''
      union all
      select lower(at_fields->>'Preferred Email'), at_member_id from digest.member_profiles
        where coalesce(at_fields->>'Preferred Email','') <> ''
    ) x group by em
  ),
  upd as (
    update digest.event_registrations er
    set member_at_id = e.aid
    from emails e
    where er.member_at_id is null and coalesce(er.email,'') <> ''
      and e.em = lower(er.email) and e.n = 1
    returning 1)
  select count(*) into v_email from upd;

  with names as (
    select digest.name_fold(full_name) as nm, min(at_member_id) as aid, count(distinct at_member_id) as n
    from digest.member_attributes where coalesce(full_name,'') <> ''
    group by digest.name_fold(full_name)
  ),
  upd as (
    update digest.event_registrations er
    set member_at_id = nm.aid
    from names nm
    where er.member_at_id is null
      and coalesce(er.full_name,'') <> ''
      and nm.nm = digest.name_fold(er.full_name)
      and nm.n = 1
      and (er.ticket_for is null
           or er.ticket_for && array['E-commerce Entrepreneur','MDS Member','Staff','MDS Team','Extension'])
      and not (er.ticket_for && array['Significant Other','Friend','Business Partner','Partner'])
    returning 1)
  select count(*) into v_name from upd;

  return jsonb_build_object('stamped_by_email', v_email, 'stamped_by_name', v_name);
end $function$
