-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.stamp_form_responses()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare v_stamped int;
begin
  with emails as (
    select lower(mp.at_fields->>'Preferred Email') as email,
           min(mp.at_member_id) as at_member_id
    from digest.member_profiles mp
    where nullif(trim(mp.at_fields->>'Preferred Email'), '') is not null
      and mp.at_member_id is not null
    group by 1
    having count(distinct mp.at_member_id) = 1
  )
  update digest.form_responses fr
     set member_at_id = e.at_member_id
    from emails e
   where fr.member_at_id is null
     and fr.email = e.email;
  get diagnostics v_stamped = row_count;
  return jsonb_build_object('stamped_by_email', v_stamped);
end $function$
