-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.state_region_states(p text)
 RETURNS text[]
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'digest', 'pg_temp'
AS $function$
  select case regexp_replace(nullif(trim(lower(coalesce(p,''))), ''), '^(the\s+)|(\s+states?)$', '', 'g')
    when 'south' then array['Texas','Florida','Georgia','Alabama','Mississippi','Louisiana','Tennessee','Kentucky','South Carolina','North Carolina','Virginia','West Virginia','Arkansas','Oklahoma']
    when 'southern' then array['Texas','Florida','Georgia','Alabama','Mississippi','Louisiana','Tennessee','Kentucky','South Carolina','North Carolina','Virginia','West Virginia','Arkansas','Oklahoma']
    when 'southeast' then array['Florida','Georgia','South Carolina','North Carolina','Tennessee','Alabama','Mississippi']
    when 'midwest' then array['Ohio','Michigan','Indiana','Illinois','Wisconsin','Minnesota','Iowa','Missouri','Kansas','Nebraska','South Dakota','North Dakota']
    when 'northeast' then array['New York','New Jersey','Pennsylvania','Connecticut','Rhode Island','Massachusetts','Vermont','New Hampshire','Maine']
    when 'new england' then array['Connecticut','Rhode Island','Massachusetts','Vermont','New Hampshire','Maine']
    when 'west coast' then array['California','Oregon','Washington']
    when 'east coast' then array['Maine','New Hampshire','Massachusetts','Rhode Island','Connecticut','New York','New Jersey','Delaware','Maryland','Virginia','North Carolina','South Carolina','Georgia','Florida','Washington DC']
    when 'pacific northwest' then array['Washington','Oregon']
    when 'southwest' then array['Arizona','New Mexico','Nevada','Utah']
    when 'mountain west' then array['Colorado','Utah','Idaho','Montana','Wyoming','Nevada']
    when 'rockies' then array['Colorado','Utah','Idaho','Montana','Wyoming']
    when 'tri-state' then array['New York','New Jersey','Connecticut']
    when 'tristate' then array['New York','New Jersey','Connecticut']
    when 'dmv' then array['Washington DC','Maryland','Virginia']
    else null end
$function$
