-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.term_cover(at_fields jsonb, q text)
 RETURNS integer
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'digest', 'public', 'extensions'
AS $function$
  select count(*)::int
  from unnest(string_to_array(regexp_replace(lower(coalesce(q,'')), '[^a-z0-9]+', ' ', 'g'), ' ')) w
  where length(w) > 2
    and to_tsvector('english',
          coalesce(digest.attr_clean(at_fields->>'Area of Expertise'), '') || ' ' ||
          coalesce(at_fields->>'About Me', '') || ' ' ||
          coalesce(digest.attr_clean(at_fields->>'Main Niche'), '') || ' ' ||
          coalesce(digest.attr_clean(at_fields->>'Interesting / Fun fact'), ''))
        @@ plainto_tsquery('english', w)
$function$
