-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.tg_member_event_report()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
begin
  begin
    insert into digest.member_events (at_member_id, event_type, source, cadence, occurred_at, meta)
    values (new.at_member_id, 'report_filed', 'olivia', 'live', coalesce(new.created_at, now()),
            jsonb_build_object('report_id', new.id));
  exception when others then null;
  end;
  return null;
end $function$
