-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.tg_member_event_portal_seen()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
begin
  begin
    if new.at_member_id is not null then
      insert into digest.member_events (at_member_id, member, event_type, source, cadence, occurred_at, meta)
      values (new.at_member_id, new.airtable_id, 'portal_seen', 'portal', 'live',
              coalesce(new.portal_last_seen_at, now()), '{}'::jsonb);
    end if;
  exception when others then null;
  end;
  return null;
end $function$
