-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.tg_member_event_olivia_turn()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare v_atid text;
begin
  begin
    if new.role = 'olivia' and coalesce(new.wamid, '') not like 'wamid.SELFTEST%'
       and coalesce(new.wamid, '') not like '%SELFTEST_MANU%' then
      select m.at_member_id into v_atid from digest.members m where m.airtable_id = new.member limit 1;
      insert into digest.member_events (at_member_id, member, event_type, source, cadence, occurred_at, meta)
      values (v_atid, new.member, 'olivia_turn', 'olivia', 'live', coalesce(new.created_at, now()),
              jsonb_strip_nulls(jsonb_build_object('route', new.route,
                'sources_used', new.plan->'sources_used', 'period', new.plan->>'period')));
    end if;
  exception when others then null;  -- fail-open: never break the conversation save
  end;
  return null;
end $function$
