-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.trg_derive_member_attributes()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
begin
  if coalesce(trim(new.at_fields->>'AT Database Status'), '') = ''
     and new.application is null then
    return new;                       -- lead/junk mirror row, nothing to derive
  end if;
  perform digest.derive_member_attributes(new.at_member_id);
  return new;
end $function$
