-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.video_file_for_send(p_phone text, p_file_key text)
 RETURNS TABLE(file_name text, storage_object text, file_kind text, video_title text)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare v_n int;
begin
  if nullif(trim(coalesce(p_file_key, '')), '') is null then return; end if;
  select case when digest.resolve_asker(p_phone) is not null then 1 else 0 end into v_n;
  if v_n <> 1 then return; end if;

  return query
  select f.file_name, f.storage_object, f.file_kind, v.title
    from digest.video_files f
    join digest.videos_catalog v on v.video_id = f.video_id
   where f.file_key = p_file_key
     and f.storage_object is not null
     and f.file_kind not in ('test_data', 'junk', 'unknown')
     and v.status = 'published'
     and v.deleted_at is null
     and v.access_restriction = 'public'   -- the line that matters
   limit 1;
end $function$
