-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.
CREATE OR REPLACE FUNCTION digest.zoom_resolve_attendance()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'digest', 'pg_temp'
AS $function$
declare v_bot int; v_auto int; v_p1 int; v_p2 int; v_rows int;
        v_person int; v_res int;
begin
  create temp table _m on commit drop as
  select ma.at_member_id,
         regexp_replace(regexp_replace(
           lower(translate(ma.full_name,
             'ÁÀÂÄÃÅáàâäãåÉÈÊËéèêëÍÌÎÏíìîïÓÒÔÖÕóòôöõÚÙÛÜúùûüÑñÇç',
             'AAAAAAaaaaaaEEEEeeeeIIIIiiiiOOOOOoooooUUUUuuuuNnCc')),
           '[^a-z0-9 ]', ' ', 'g'), '\s+', ' ', 'g') as folded
  from digest.member_attributes ma
  where digest.is_active_member_status(ma.membership_status)
    and nullif(trim(coalesce(ma.full_name, '')), '') is not null;

  -- tier 0: not a person — AI notetakers and the host account
  insert into digest.zoom_name_alias (name_folded, at_member_id, confidence, decided_by, note)
  select distinct a.name_folded, null, 'bot', 'zoom_resolve_attendance', 'notetaker or host account'
  from digest.call_attendance a
  where a.name_folded ~* '(notetaker|note taker|circleback|fireflies|otter|fathom|timeless|companion|read ai|sembly|recorder|assistant|meeting buddy|\mai\M)'
     or a.name_folded ~* '^(contact mds|discover mds|tomi mds|belen mds)'
  on conflict (name_folded) do nothing;
  get diagnostics v_bot = row_count;

  create temp table _n on commit drop as
  select distinct a.name_folded as f from digest.call_attendance a
  where not exists (select 1 from digest.zoom_name_alias z where z.name_folded = a.name_folded);

  insert into digest.zoom_name_alias (name_folded, at_member_id, confidence, decided_by)
  select n.f, min(m.at_member_id), 'auto', 'zoom_resolve_attendance'
  from _n n join _m m on m.folded = n.f
  group by n.f having count(*) = 1
  on conflict (name_folded) do nothing;
  get diagnostics v_auto = row_count;

  insert into digest.zoom_name_alias (name_folded, at_member_id, confidence, decided_by, note)
  select n.f, min(m.at_member_id), 'partial', 'zoom_resolve_attendance', 'first+last token'
  from _n n
  join _m m on split_part(m.folded, ' ', 1) = split_part(n.f, ' ', 1)
           and split_part(m.folded, ' ', array_length(string_to_array(m.folded, ' '), 1))
             = split_part(n.f, ' ', array_length(string_to_array(n.f, ' '), 1))
  where array_length(string_to_array(n.f, ' '), 1) >= 2
    and not exists (select 1 from digest.zoom_name_alias z where z.name_folded = n.f)
  group by n.f having count(*) = 1
  on conflict (name_folded) do nothing;
  get diagnostics v_p1 = row_count;

  insert into digest.zoom_name_alias (name_folded, at_member_id, confidence, decided_by, note)
  select n.f, min(m.at_member_id), 'partial', 'zoom_resolve_attendance', 'first name + last-token stem'
  from _n n
  join _m m on m.folded like split_part(n.f, ' ', 1) || ' %'
           and length(split_part(n.f, ' ', array_length(string_to_array(n.f, ' '), 1))) >= 4
           and position(left(split_part(n.f, ' ', array_length(string_to_array(n.f, ' '), 1)), 4) in m.folded) > 0
  where array_length(string_to_array(n.f, ' '), 1) >= 2
    and not exists (select 1 from digest.zoom_name_alias z where z.name_folded = n.f)
  group by n.f having count(*) = 1
  on conflict (name_folded) do nothing;
  get diagnostics v_p2 = row_count;

  update digest.call_attendance a
     set at_member_id = z.at_member_id
    from digest.zoom_name_alias z
   where z.name_folded = a.name_folded
     and z.confidence in ('auto', 'human')
     and a.at_member_id is distinct from z.at_member_id;
  get diagnostics v_rows = row_count;

  -- the rate that matters is over PEOPLE, not over rows a bot generated
  select count(*), count(*) filter (where a.at_member_id is not null)
    into v_person, v_res
  from digest.call_attendance a
  left join digest.zoom_name_alias z on z.name_folded = a.name_folded
  where coalesce(z.confidence, '') <> 'bot';

  return jsonb_build_object('bot_names', v_bot, 'alias_exact', v_auto,
    'alias_first_last', v_p1, 'alias_stem', v_p2, 'rows_stamped', v_rows,
    'person_rows', v_person, 'resolved', v_res,
    'resolved_pct', round(100.0 * v_res / nullif(v_person, 0), 1));
end $function$
