#!/usr/bin/env python3
"""#65 — export the SQL layer to files, and fail when the repo and the live DB differ.

The retrieval, the gating, the stats and the whole security boundary live in ~103
Postgres functions. Before this script they existed ONLY inside the running database:
no diff, no review, no restore path independent of the DB.

    python3 scripts/db_export_schema.py            # write db/ from the live database
    python3 scripts/db_export_schema.py --check    # exit 1 if db/ != live database

Read-only in both modes. Reaches the DB through PostgREST (the only path this machine
has) by calling digest.schema_source(), which returns DDL text and nothing else.

Layout:
    db/functions/<name>.sql   one file per function, exact pg_get_functiondef output
    db/views/<name>.sql       one file per view / materialized view
    db/triggers.sql           every trigger, pg_get_triggerdef
    db/policies.sql           every RLS policy (currently none — that is the record)
    db/grants.sql             execute/read/write grants: who may call what
    db/rls.sql                row-level-security flag per table
    db/tables.sql             columns, constraints and indexes — the restore path
"""

import argparse
import difflib
import json
import os
import subprocess
import sys

ENV_PATH = "/Users/Born/mds-digest-web/.env.local"
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB_DIR = os.path.join(REPO, "db")
SUBDIR = {"function": "functions", "view": "views", "matview": "views", "catalog": ""}
HEADER = "-- GENERATED by scripts/db_export_schema.py from the live database. Do not hand-edit.\n"


def load_env():
    env = {}
    with open(ENV_PATH) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                env[k] = v.strip().strip('"').strip("'")
    return env["SUPABASE_URL"].rstrip("/"), env["SUPABASE_SECRET_KEY"]


def fetch(url, key):
    """Call digest.schema_source(). One retry on transport/5xx only."""
    cmd = ["curl", "-s", "-m", "120", "-w", "\n%{http_code}", "-X", "POST",
           f"{url}/rest/v1/rpc/schema_source",
           "-H", f"apikey: {key}", "-H", f"Authorization: Bearer {key}",
           "-H", "Content-Type: application/json", "-H", "Content-Profile: digest",
           "-d", "{}"]
    for attempt in (1, 2):
        p = subprocess.run(cmd, capture_output=True, text=True)
        raw, _, code = p.stdout.rpartition("\n")
        if code.isdigit() and 200 <= int(code) < 500:
            break
    if not code.isdigit() or int(code) != 200:
        sys.exit(f"schema_source() failed (status {code}): {raw[:300]}\n"
                 f"If the function does not exist yet, apply "
                 f"scripts/sql/20260808_schema_source_introspection.sql first.")
    rows = json.loads(raw)
    if not rows:
        sys.exit("schema_source() returned no rows — refusing to wipe db/")
    return rows


def expected_tree(rows):
    """rel-path -> file body. One body per object, deterministic, newline-terminated."""
    tree = {}
    for r in rows:
        rel = os.path.join(SUBDIR[r["kind"]], r["file_name"])
        body = HEADER + r["definition"].rstrip("\n") + "\n"
        if rel in tree and tree[rel] != body:
            sys.exit(f"two live objects both want {rel} — refusing to write a lossy export")
        tree[rel] = body
    return tree


def actual_tree():
    tree = {}
    for root, _, files in os.walk(DB_DIR):
        for fn in files:
            if fn.endswith(".sql"):
                path = os.path.join(root, fn)
                with open(path) as f:
                    tree[os.path.relpath(path, DB_DIR)] = f.read()
    return tree


def write(tree):
    for rel, body in tree.items():
        path = os.path.join(DB_DIR, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write(body)
    for rel in set(actual_tree()) - set(tree):      # object dropped in the DB
        os.remove(os.path.join(DB_DIR, rel))
        print(f"  removed  {rel}  (no longer in the database)")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="do not write; exit 1 if the repo and the live database differ")
    args = ap.parse_args()

    url, key = load_env()
    live = expected_tree(fetch(url, key))

    if not args.check:
        write(live)
        print(f"exported {len(live)} files to db/ "
              f"({sum(1 for k in live if k.startswith('functions/'))} functions, "
              f"{sum(1 for k in live if k.startswith('views/'))} views)")
        return 0

    repo = actual_tree()
    missing = sorted(set(live) - set(repo))         # in the DB, not in git
    extra = sorted(set(repo) - set(live))           # in git, not in the DB
    changed = sorted(k for k in set(live) & set(repo) if live[k] != repo[k])

    if not (missing or extra or changed):
        print(f"DB IN SYNC — {len(live)} files byte-match the live database.")
        return 0

    for k in missing:
        print(f"  MISSING FROM GIT  {k}")
    for k in extra:
        print(f"  NOT IN THE DB     {k}  (dropped live, or a stale file)")
    for k in changed:
        print(f"  DIFFERS           {k}")
        diff = difflib.unified_diff(repo[k].splitlines(), live[k].splitlines(),
                                    "repo", "live", lineterm="", n=1)
        for line in list(diff)[:14]:
            print(f"      {line}")
    print(f"\nDB DRIFT — {len(missing)} missing, {len(extra)} stale, {len(changed)} changed. "
          f"Run scripts/db_export_schema.py to re-export, review the diff, and commit.")
    return 1


if __name__ == "__main__":
    sys.exit(main())
