#!/usr/bin/env python3
"""Submit the Summit-videos-live announcement template (Andy 2026-08-28: "submit the
utility template for meta, since we are notifying you about videos live").

UTILITY: a notification tied to the member's own event attendance — their Summit's
recordings are available — not promotional outreach. Copy approved by Andy on his own
test fill 2026-08-28 ("More sessions are landing daily." line deleted, his edit).

Variables: {{1}} first name · {{2}} session count · {{3}} the personal picks block
(2 sessions with links, or the speaker's own-session line + picks — generated by
scripts/announce_summit_videos.py, links verbatim from videos_catalog).

Token/WABA mirror scripts/olivia_intro_templates_109.py. Submission only — the SEND
wave is a separate, explicitly approved step."""
import json
import subprocess

WABA = "1575708577606583"
ENV_PATH = "/Users/Born/mds-digest-web/.env.local"


def load_token():
    env = {}
    for line in open(ENV_PATH):
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, v = line.split("=", 1)
            env[k] = v.strip().strip('"').strip("'")
    return env["META_WA_TOKEN"]


def curl(method, url, token, body=None):
    cmd = ["curl", "-s", "-X", method, url, "-H", f"Authorization: Bearer {token}"]
    if body is not None:
        cmd += ["-H", "Content-Type: application/json", "-d", json.dumps(body)]
    out = subprocess.run(cmd, capture_output=True, text=True)
    try:
        return json.loads(out.stdout)
    except json.JSONDecodeError:
        return {"raw": out.stdout}


TEMPLATE = {
    "name": "mds_summit_videos_live_v2",
    "category": "UTILITY",
    "language": "en_US",
    "allow_category_change": True,
    # v2 (2026-08-28): Meta rejects newlines inside template VARIABLES at send time
    # (132018, proven on a live test send) though it APPROVED the v1 template whose
    # example carried them. All line breaks live in this fixed skeleton; every
    # variable is single-line. {{3}} is the lead-in ("Picked for you:" or the
    # speaker's own-session line), {{4}}/{{6}} are "Title - Speaker", {{5}}/{{7}} links.
    "components": [
        {"type": "BODY",
         "text": ("\U0001F3AC Hi {{1}} — the first {{2}} session recordings from the "
                  "*MDS Summit Singapore* are live.\n\n{{3}}\n\n"
                  "• *{{4}}*\n{{5}}\n\n"
                  "• *{{6}}*\n{{7}}\n\n"
                  "Full transcripts are searchable too — just ask me here: \"what did Tamar say "
                  "about sampling?\", \"summarize Ivan's AMA\", \"which session should I watch "
                  "first?\" — I'll pull quotes, timestamps and summaries for you.\n\n"
                  "All Summit sessions so far: https://app.mds.co/videos"),
         "example": {"body_text": [[
             "Andy", "16", "Picked for you:",
             "Run Amazon by Exception. Decide at Scale — Ary Selener",
             "https://app.mds.co/videos/6a907a6bd5013ff117eeb3d6",
             "7 AI Workflows Your Business Needs — Damon Sununtnasuk",
             "https://app.mds.co/videos/6a8e4f349614296a636f1d7d"
         ]]}},
        {"type": "BUTTONS", "buttons": [
            {"type": "URL", "text": "Watch in the app", "url": "https://app.mds.co/videos"}
        ]},
    ],
}


def main():
    token = load_token()
    existing = curl("GET", f"https://graph.facebook.com/v22.0/{WABA}/message_templates"
                           "?fields=name,status,category,id&limit=200", token)
    have = {t["name"]: t for t in existing.get("data", [])}
    if TEMPLATE["name"] in have:
        h = have[TEMPLATE["name"]]
        print(f"already submitted: {h['name']} -> {h['status']} ({h['category']})")
        return
    r = curl("POST", f"https://graph.facebook.com/v22.0/{WABA}/message_templates", token, TEMPLATE)
    if r.get("error"):
        print("SUBMIT FAILED:", json.dumps(r["error"], indent=1)[:600])
    else:
        print(f"submitted: id {r.get('id')} status {r.get('status')} category {r.get('category')}")


if __name__ == "__main__":
    main()
